package index

import "testing"

// TestStripsHarnessPlumbing pins what comes out of a transcript that a harness
// wrote to itself. Measured on a real index before this existed: 304 records
// were nothing but plumbing (#551).
func TestStripsHarnessPlumbing(t *testing.T) {
	cases := []struct{ name, in, want string }{
		{"system reminder", "before <system-reminder>do not do X</system-reminder> after", "before  after"},
		{"local command caveat", "<local-command-caveat>Caveat: generated by the user</local-command-caveat>ok", "ok"},
		{"slash command echo", "<command-name>/clear</command-name>\n<command-args></command-args>", ""},
		{"interrupt marker on its own line", "real question\n[Request interrupted by user for tool use]\nmore", "real question\nmore"},
		{"hook envelope line", "UserPromptSubmit hook additional context:\nkept", "kept"},
		{"no visible output", "[Your previous response had no visible output. Please continue]", ""},
	}
	for _, c := range cases {
		if got := stripSelfRecall(c.in); got != c.want {
			t.Errorf("%s: got %q, want %q", c.name, got, c.want)
		}
	}
}

// TestKeepsWhatIsNotPlumbing is the half that matters more: a message that
// merely *mentions* a marker — a bug report, this repository's own tests — must
// survive, and command output must never be touched, because it is the most
// useful thing a transcript holds.
func TestKeepsWhatIsNotPlumbing(t *testing.T) {
	keep := []string{
		"the parser should ignore <system-reminder> tags mid-sentence",
		"we saw [Request interrupted by user] inside a quoted log and it broke",
		"<bash-stdout>ok  github.com/x  1.2s</bash-stdout>",
		"deja indexes UserPromptSubmit hook additional context: as if a person said it",
	}
	for _, in := range keep {
		if got := stripSelfRecall(in); got != in {
			t.Errorf("stripped a mention rather than plumbing:\n in:  %q\n out: %q", in, got)
		}
	}
}
