package digest

import "testing"

// A harness that introduces an envelope before quoting it put truncated
// inter-agent JSON into the session-start block — the first thing an agent
// reads. The tags are not prose: wherever one appears, the message is plumbing.
func TestEnvelopeIsNoiseWhereverItAppears(t *testing.T) {
	wrapped := []string{
		`Another Claude session sent a message: <teammate-message teammate_id="triage2" color="cyan"> {"type":"idle_notification"}`,
		`heads up — <task-notification id="7"> finished`,
		`context follows <system-reminder>do the thing</system-reminder>`,
	}
	for _, m := range wrapped {
		if !noisyMessage(m) {
			t.Errorf("an introduced envelope was kept: %q", m)
		}
	}
	// Prose that merely reads like a caveat is only skipped when it opens the
	// message, so a sentence about one is still the user talking.
	if noisyMessage("the caveat here is that the index lags by a session") {
		t.Error("a sentence mentioning a caveat was dropped as plumbing")
	}
	if !noisyMessage("Caveat: the messages below were generated by the user") {
		t.Error("the harness caveat header was kept")
	}
}
