// Command genlogo draws the SVG assets from the same sprite the terminal banner
// prints, so the mark on a page and the mark in a terminal cannot drift.
//
// They were hand-authored before this existed, which meant editing the sprite
// left the assets behind silently. Run it after any change to internal/mark:
//
//	go run ./scripts/genlogo
//
// The favicon is deliberately not generated. It is not this sprite scaled down —
// the whole animal at 16px is mush, so it was redrawn as the head alone on a
// 16-unit grid where one cell lands on exactly one device pixel.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/vshulcz/deja-vu/internal/mark"
)

const note = `  <!-- Generated by scripts/genlogo from internal/mark. Do not hand-edit: the
     sprite is the source, and the terminal banner draws from the same grid.
     Coat, accent and features are the three colours xterm-256 holds exactly,
     so vector and terminal agree. -->
`

func fills(paths []mark.Path, indent int) string {
	pad := strings.Repeat(" ", indent)
	var b strings.Builder
	for _, p := range paths {
		fmt.Fprintf(&b, "%s<path fill=\"%s\"%s d=\"%s\"/>\n", pad, p.Fill, seal(p.Fill), p.D)
	}
	return b.String()
}

// seal outsets a shape by a hair, in its own colour.
//
// The sprite is a pack of rectangles, and two rectangles that share an edge are
// two shapes the renderer antialiases separately: neither covers its half of the
// boundary pixel completely, and the background shows between them. It never
// showed while the mark was drawn at whole-number scale. It is animated with a
// scale transform now, so it spends most of its time at a fractional size, and
// the measured cost was a row of pixels a tenth darker than the coat, running
// across the head where the ear rows meet the skull.
//
// A stroke of one unit puts half a unit of overlap on either side of every
// shared edge, which is enough to cover a boundary that can land anywhere within
// a pixel. Half that much was measured first and only took the dip from a tenth
// to fourteen thousandths. Against a twelve-unit sprite pixel the silhouette
// grows by four per cent of one pixel.
func seal(fill string) string {
	return fmt.Sprintf(" stroke=%q stroke-width=\"1\"", fill)
}

// movingTail is every cell any wag position touches. The tail hangs clear of the
// body, so those cells are left out of the still layer entirely and each wag
// position draws its own.
//
// The eyes are not handled this way. They sit on the head, and cutting them out
// would leave two holes whenever the blink hides the open pair — the still layer
// carries coat there instead, and the eye groups paint over it.
func movingTail() map[mark.Cell]bool {
	out := map[mark.Cell]bool{}
	for _, pose := range mark.WagCycle {
		for _, c := range mark.Tails[pose] {
			out[c] = true
		}
	}
	// The ears too. Every cell either pose paints comes out of the still layer,
	// so each pose can be drawn as its own group. Filling the dropped ones with
	// the background colour instead worked on the dark icon and put a black
	// notch on the light logo, where the background is neither dark nor there.
	for c := range earCells(mark.Ears["up"]) {
		out[c] = true
	}
	for c := range earCells(mark.Ears["flick"]) {
		out[c] = true
	}
	return out
}

// alive writes the tail and the eyes as animated groups.
//
// The tail is three positions of the same cells, ping-ponged: the tip travels
// out and comes back. Two positions alternating is a twitch, not a gesture. The
// blink is the eye rows swapping, shut for about a tenth of a cycle, which is
// roughly how long a cat's blink is.
//
// The timings match the ones deja stats already uses, so the two pages animate
// the same animal at the same rate rather than at two guesses.
func alive(x0, y0, size int) (css, parts string) {
	// The eyes slide by exactly one cell — one pixel of the sprite. A fraction of
	// a cell was what the first version moved, and at the sizes these are shown
	// that came to half a screen pixel: real in the markup, invisible on the page.
	glance := size
	var b strings.Builder
	seen := map[string]bool{}
	poses := []string{}
	for _, p := range mark.WagCycle {
		if !seen[p] {
			seen[p] = true
			poses = append(poses, p)
		}
	}
	for i, pose := range poses {
		fmt.Fprintf(&b, "  <g class=\"t%d\"><path fill=\"%s\"%s d=\"%s\"/></g>\n",
			i, mark.Hex[mark.Coat], seal(mark.Hex[mark.Coat]),
			mark.CellsD(mark.Tails[pose], x0, y0, size))
	}
	// Every eye state as its own group, all of them inside one that can move.
	// The blink passes through the half-lid rather than cutting from open to
	// shut, which is what an eyelid does; the glance slides the whole group
	// sideways, which is what an eye does.
	b.WriteString("  <g class=\"eyes\">\n")
	for _, eye := range []struct{ class, set string }{
		{"eyes-open", "tall"}, {"eyes-half", "half"}, {"eyes-shut", "closed"},
	} {
		fmt.Fprintf(&b, "    <g class=\"%s\"><path fill=\"%s\" d=\"%s\"/></g>\n",
			eye.class, mark.Hex[mark.Feature],
			mark.CellsD(mark.Eyes[eye.set], x0, y0, size))
	}
	b.WriteString("  </g>\n")

	// Both ear poses, each as its own group, swapped by the flick.
	for _, ear := range []struct {
		class, pose string
	}{{"ear-up", "up"}, {"ear-flick", "flick"}} {
		fmt.Fprintf(&b, "  <g class=\"%s\"><path fill=\"%s\"%s d=\"%s\"/></g>\n",
			ear.class, mark.Hex[mark.Coat], seal(mark.Hex[mark.Coat]),
			mark.CellsD(sortCells(cellList(earCells(mark.Ears[ear.pose]))), x0, y0, size))
	}

	css = `  <style>
    .t1, .t2, .eyes-half, .eyes-shut, .ear-flick { opacity: 0 }
    /* Everything that deforms turns about the point between the front paws, so
       the cat is pressed into the ground rather than moved around above it. */
    .sway, .perk, .breathe { transform-origin: ORIGIN }
    @media (prefers-reduced-motion: no-preference) {
      /* The one continuous motion on the mark. Everything else cuts between
         poses; this eases, and a creature that is never perfectly still is the
         difference between an animal and a diagram. */
      .breathe { animation: dv-breathe 4.9s cubic-bezier(.4,0,.5,1) infinite }
      .perk    { animation: dv-perk 18.7s cubic-bezier(.33,0,.3,1) infinite }
      .sway    { animation: dv-sway 13.7s cubic-bezier(.45,0,.55,1) infinite }
      .t0  { animation: dv-t0 4.7s steps(1, end) infinite }
      .t1  { animation: dv-t1 4.7s steps(1, end) infinite }
      .t2  { animation: dv-t2 4.7s steps(1, end) infinite }
      .eyes-open { animation: dv-open 7.3s steps(1, end) infinite }
      .eyes-half { animation: dv-half 7.3s steps(1, end) infinite }
      .eyes-shut { animation: dv-shut 7.3s steps(1, end) infinite }
      .eyes { animation: dv-glance 9.7s cubic-bezier(.4,0,.5,1) infinite }
      .ear-up    { animation: dv-ear-up 11.3s steps(1, end) infinite }
      .ear-flick { animation: dv-ear 11.3s steps(1, end) infinite }
    }
    /* Draw in, hold at the top a moment, let it out. Taller is narrower: a body
       that gains height without losing width is inflating, not breathing. The
       pause at the top is what separates a breath from a pendulum. */
    @keyframes dv-breathe { 0% { transform: scale(1, 1) } 40%, 56% { transform: scale(.978, 1.026) } 100% { transform: scale(1, 1) } }
    /* Once every eighteen seconds or so it gathers itself and pops up, then
       rocks to a stop. Squash first, stretch second: the dip before a movement
       is what makes it read as intent rather than as a jolt, and the two
       shrinking bounces afterwards are what makes it read as weight. */
    @keyframes dv-perk {
      0%, 86% { transform: scale(1, 1) }
      88.4%   { transform: scale(1.055, .945) }
      90.8%   { transform: scale(.955, 1.068) }
      93.2%   { transform: scale(1.028, .975) }
      95.4%   { transform: scale(.988, 1.014) }
      97.4%, 100% { transform: scale(1, 1) }
    }
    /* And now and then it leans, once each way. The whole animal tips about its
       paws; there is no neck on this sprite to turn a head on. */
    @keyframes dv-sway { 0%, 26% { transform: rotate(0) } 38%, 47% { transform: rotate(2.1deg) } 58%, 66% { transform: rotate(0) } 76%, 85% { transform: rotate(-2.1deg) } 96%, 100% { transform: rotate(0) } }
    /* The tail rests for four fifths of its cycle, then sweeps out and back. */
    @keyframes dv-t0 { 0%, 79.9% { opacity: 1 } 80%, 96.9% { opacity: 0 } 97%, 100% { opacity: 1 } }
    @keyframes dv-t1 { 0%, 79.9% { opacity: 0 } 80%, 84.9% { opacity: 1 } 85%, 91.9% { opacity: 0 } 92%, 96.9% { opacity: 1 } 97%, 100% { opacity: 0 } }
    @keyframes dv-t2 { 0%, 84.9% { opacity: 0 } 85%, 91.9% { opacity: 1 } 92%, 100% { opacity: 0 } }
    /* One blink a cycle, down through the half-lid and back up: about a tenth
       of a second on each lid position and a sixth shut. Two blinks half a
       second apart, which is what this was, reads as a flutter. */
    @keyframes dv-open { 0%, 89.9% { opacity: 1 } 90%, 95.7% { opacity: 0 } 95.8%, 100% { opacity: 1 } }
    @keyframes dv-half { 0%, 89.9% { opacity: 0 } 90%, 91.6% { opacity: 1 } 91.7%, 94.1% { opacity: 0 } 94.2%, 95.7% { opacity: 1 } 95.8%, 100% { opacity: 0 } }
    @keyframes dv-shut { 0%, 91.6% { opacity: 0 } 91.7%, 94.1% { opacity: 1 } 94.2%, 100% { opacity: 0 } }
    /* Looks aside, holds it a moment, looks back. */
    @keyframes dv-glance { 0%, 70% { transform: translateX(0) } 74%, 84% { transform: translateX(GLANCEpx) } 88%, 100% { transform: translateX(0) } }
    @keyframes dv-ear { 0%, 96.9% { opacity: 0 } 97%, 99.4% { opacity: 1 } 99.5%, 100% { opacity: 0 } }
    @keyframes dv-ear-up { 0%, 96.9% { opacity: 1 } 97%, 99.4% { opacity: 0 } 99.5%, 100% { opacity: 1 } }
  </style>
`
	// Between the front paws: half the sprite across, all of it down.
	origin := fmt.Sprintf("%dpx %dpx", x0+12*size, y0+22*size)
	css = strings.ReplaceAll(css, "ORIGIN", origin)
	css = strings.ReplaceAll(css, "GLANCEpx", fmt.Sprintf("%dpx", glance))
	return css, b.String()
}

// earCells turns an ear pose's rows into the set of cells it paints.
func earCells(rows []string) map[mark.Cell]bool {
	out := map[mark.Cell]bool{}
	src := rows
	if src == nil {
		src = mark.Body[:4]
	}
	for r, row := range src {
		for c, ch := range row {
			if ch == '#' {
				out[mark.Cell{Row: r, Col: c}] = true
			}
		}
	}
	return out
}

func cellList(set map[mark.Cell]bool) []mark.Cell {
	out := make([]mark.Cell, 0, len(set))
	for c := range set {
		out = append(out, c)
	}
	return out
}

func sortCells(in []mark.Cell) []mark.Cell {
	sort.Slice(in, func(i, j int) bool {
		if in[i].Row != in[j].Row {
			return in[i].Row < in[j].Row
		}
		return in[i].Col < in[j].Col
	})
	return in
}

// livingCat is the whole animal with everything that moves on it.
//
// Every motion is a transform of the entire body about the point between its
// front paws, so it deforms as one soft thing and its feet stay on the ground.
// Two earlier versions moved a slab of rows instead: the first took the paws up
// with it and hovered, the second left them behind and stretched the face away
// from the nose. A slice of a body sliding is not a deformation, it is a cut,
// and the eye reads it as one.
//
// Squash and stretch carry the volume: taller is narrower, shorter is wider. It
// is the whole of why a bouncing shape reads as flesh rather than as a box on a
// timer, and it cannot be had by translating anything.
func livingCat(x0, y0, size int) string {
	tail := movingTail()
	still := mark.Ready
	still.EyeSet = "none"
	body := mark.Paths(still, x0, y0, size, func(c mark.Cell) bool { return tail[c] })
	moving, breathing := alive(x0, y0, size)
	// One group per animation: two animations on one element would each be
	// setting transform, and only the last one declared would survive.
	return moving +
		"  <g class=\"sway\">\n   <g class=\"perk\">\n    <g class=\"breathe\">\n" +
		fills(body, 5) + breathing + "    </g>\n   </g>\n  </g>\n"
}

func logo(ink string, animate bool) string {
	const x0, y0, size = 36, 19, 6
	cat := fills(mark.Paths(mark.Ready, x0, y0, size, nil), 2)
	if animate {
		cat = livingCat(x0, y0, size)
	}
	return `<svg xmlns="http://www.w3.org/2000/svg" width="620" height="170" viewBox="0 0 620 170" role="img" aria-label="deja-vu">
` + note + cat +
		`  <g font-family="SF Mono, JetBrains Mono, Fira Code, Menlo, monospace">
    <text x="208" y="105" font-size="72" font-weight="700" fill="` + ink + `">deja-vu</text>
  </g>
</svg>
`
}

// The icon does not move. It is used as an avatar and an app icon, sizes where a
// travelling two-pixel tip is a flicker rather than a gesture.
func icon() string {
	const x0, y0, size = 56, 68, 12
	return `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" viewBox="0 0 400 400" role="img" aria-label="deja-vu">
  <rect width="400" height="400" rx="88" fill="#1d1b2e"/>
` + note + fills(mark.Paths(mark.Ready, x0, y0, size, nil), 2) + "</svg>\n"
}

// liveIcon is the app icon with the cat alive in it: the same wag and blink the
// wordmark carries. The site needs a file rather than inline markup, because an
// SVG referenced by <img> still runs its own CSS animations — which is how the
// header mark moves without the page owning a second copy of the sprite.
func liveIcon() string {
	const x0, y0, size = 56, 68, 12
	return `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" viewBox="0 0 400 400" role="img" aria-label="deja-vu">
  <rect width="400" height="400" rx="88" fill="#1d1b2e"/>
` + note + livingCat(x0, y0, size) + "</svg>\n"
}

// stillIcon is the app icon in a named mood, for the moments the site wants the
// cat to react: asleep while the tab is in the background, surprised when the
// demo search lands a hit. The page swaps the file rather than reaching into
// the drawing, which keeps the sprite in one place.
func stillIcon(m mark.Mood) string {
	const x0, y0, size = 56, 68, 12
	return `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" viewBox="0 0 400 400" role="img" aria-label="deja-vu">
  <rect width="400" height="400" rx="88" fill="#1d1b2e"/>
` + note + fills(mark.Paths(m, x0, y0, size, nil), 2) + "</svg>\n"
}

func main() {
	check := flag.Bool("check", false, "fail if the committed assets differ from the sprite")
	static := flag.Bool("static", false, "draw the ready pose without the wag")
	flag.Parse()

	darkLogo := logo("#e8e6f0", !*static)
	appIcon := icon()
	assets := map[string]string{
		"assets/logo.svg":      logo("#1d1b2e", !*static),
		"assets/logo-dark.svg": darkLogo,
		"assets/icon.svg":      appIcon,
		// The site serves docs/ as its root, so it cannot reach the files
		// above. Written from the same sprite in the same run rather than
		// copied, because a copy is what goes stale — this is the drift the
		// whole command exists to stop.
		"docs/assets/logo-dark.svg":  darkLogo,
		"docs/assets/icon.svg":       appIcon,
		"docs/assets/icon-live.svg":  liveIcon(),
		"docs/assets/icon-sleep.svg": stillIcon(mark.Asleep),
		"docs/assets/icon-wow.svg":   stillIcon(mark.Surprised),
	}
	paths := make([]string, 0, len(assets))
	for p := range assets {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	// -check is what keeps the assets honest. Editing the sprite and forgetting
	// to regenerate is silent otherwise: the banner changes, the logo does not,
	// and nothing says which one is the product.
	stale := false
	for _, p := range paths {
		if *check {
			have, err := os.ReadFile(p)
			if err != nil {
				fmt.Fprintln(os.Stderr, err)
				os.Exit(1)
			}
			if string(have) != assets[p] {
				fmt.Fprintf(os.Stderr, "%s is stale: run go run ./scripts/genlogo\n", p)
				stale = true
			}
			continue
		}
		if err := os.WriteFile(p, []byte(assets[p]), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		fmt.Println("wrote", p)
	}
	if stale {
		os.Exit(1)
	}
}
