// Command genlogo draws the SVG assets from the same sprite the terminal banner
// prints, so the mark on a page and the mark in a terminal cannot drift.
//
// They were hand-authored before this existed, which meant editing the sprite
// left the assets behind silently. Run it after any change to internal/mark:
//
//	go run ./scripts/genlogo
//
// The favicon is deliberately not generated. It is not this sprite scaled down —
// the whole animal at 16px is mush, so it was redrawn as the head alone on a
// 16-unit grid where one cell lands on exactly one device pixel.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/vshulcz/deja-vu/internal/mark"
)

// pixel is one sprite cell placed on an SVG canvas.
type pixel struct{ x, y, size int }

// runs walks the grid and returns, per palette colour, the horizontal runs it
// covers. One path per colour rather than one rect per pixel: at fractional
// scale a per-row fill leaves a hairline of background between the rows, which
// is the seam the first hand-drawn assets had.
func runs(g [][]byte, coat, x0, y0, size int, skip func(mark.Cell) bool) map[int][]pixel {
	out := map[int][]pixel{}
	for r, row := range g {
		for c := 0; c < len(row); c++ {
			col, ok := mark.Colour(row[c], coat)
			if !ok || (skip != nil && skip(mark.Cell{Row: r, Col: c})) {
				continue
			}
			out[col] = append(out[col], pixel{x0 + c*size, y0 + r*size, size})
		}
	}
	return out
}

// path writes the pixels as one path, merging horizontally adjacent cells into a
// single rectangle so the file stays small and the fill stays continuous.
func path(px []pixel) string {
	var b strings.Builder
	for i := 0; i < len(px); {
		j := i
		for j+1 < len(px) && px[j+1].y == px[i].y && px[j+1].x == px[j].x+px[j].size {
			j++
		}
		w := (j - i + 1) * px[i].size
		fmt.Fprintf(&b, "M%d %dh%dv%dh-%dZ", px[i].x, px[i].y, w, px[i].size, w)
		i = j + 1
	}
	return b.String()
}

// order keeps the colours in a fixed sequence: coat, features, nose. A map walk
// would reorder the paths on every run and turn a no-op regeneration into a diff.
var order = []int{mark.Coat, mark.Feature, mark.Accent}

func body(g [][]byte, coat, x0, y0, size, indent int, skip func(mark.Cell) bool) string {
	byColour := runs(g, coat, x0, y0, size, skip)
	pad := strings.Repeat(" ", indent)
	var b strings.Builder
	for _, col := range order {
		if px := byColour[col]; len(px) > 0 {
			fmt.Fprintf(&b, "%s<path fill=\"%s\" d=\"%s\"/>\n", pad, mark.Hex[col], path(px))
		}
	}
	return b.String()
}

const note = `  <!-- Generated by scripts/genlogo from internal/mark. Do not hand-edit: the
     sprite is the source, and the terminal banner draws from the same grid.
     Coat, accent and features are the three colours xterm-256 holds exactly,
     so vector and terminal agree. -->
`

// The tail's two poses differ by two cells at the tip. Animating exactly those
// is the same wag the banner and the demo do, rather than a second idea of what
// the cat is doing.
func wagCells() (up, mid mark.Cell) {
	inUp := map[mark.Cell]bool{}
	for _, c := range mark.Tails["up"] {
		inUp[c] = true
	}
	inMid := map[mark.Cell]bool{}
	for _, c := range mark.Tails["mid"] {
		inMid[c] = true
	}
	for _, c := range mark.Tails["up"] {
		if !inMid[c] {
			up = c
		}
	}
	for _, c := range mark.Tails["mid"] {
		if !inUp[c] {
			mid = c
		}
	}
	return up, mid
}

// wag returns the two tip cells as their own paths plus the stylesheet that
// alternates them. Without a motion preference the page gets the static ready
// pose, which is the pose everything else is drawn in.
func wag(x0, y0, size int) string {
	up, mid := wagCells()
	cell := func(c mark.Cell) string {
		return path([]pixel{{x0 + c.Col*size, y0 + c.Row*size, size}})
	}
	return fmt.Sprintf(`  <path class="tip-up" fill="%s" d="%s"/>
  <path class="tip-out" fill="%s" d="%s"/>
  <style>
    .tip-out { opacity: 0 }
    @media (prefers-reduced-motion: no-preference) {
      .tip-up { animation: wag 1.4s steps(1) infinite }
      .tip-out { animation: wag 1.4s steps(1) infinite reverse }
    }
    @keyframes wag { 0%%, 49.99%% { opacity: 1 } 50%%, 100%% { opacity: 0 } }
  </style>
`, mark.Hex[mark.Coat], cell(up), mark.Hex[mark.Coat], cell(mid))
}

func logo(ink string, animate bool) string {
	const x0, y0, size = 36, 19, 6
	g := mark.Grid(mark.Ready)
	up, mid := wagCells()
	var skip func(mark.Cell) bool
	var tail string
	if animate {
		skip = func(c mark.Cell) bool { return c == up || c == mid }
		tail = wag(x0, y0, size)
	}
	return `<svg xmlns="http://www.w3.org/2000/svg" width="620" height="170" viewBox="0 0 620 170" role="img" aria-label="deja-vu">
` + note + body(g, mark.Coat, x0, y0, size, 2, skip) + tail +
		`  <g font-family="SF Mono, JetBrains Mono, Fira Code, Menlo, monospace">
    <text x="208" y="105" font-size="72" font-weight="700" fill="` + ink + `">deja-vu</text>
  </g>
</svg>
`
}

// The icon does not wag. It is used as an avatar and an app icon, sizes where a
// moving two-pixel tip is a flicker rather than a gesture.
func icon() string {
	const x0, y0, size = 56, 68, 12
	return `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" viewBox="0 0 400 400" role="img" aria-label="deja-vu">
  <rect width="400" height="400" rx="88" fill="#1d1b2e"/>
` + note + body(mark.Grid(mark.Ready), mark.Coat, x0, y0, size, 2, nil) + "</svg>\n"
}

func main() {
	check := flag.Bool("check", false, "fail if the committed assets differ from the sprite")
	static := flag.Bool("static", false, "draw the ready pose without the wag")
	flag.Parse()

	assets := map[string]string{
		"assets/logo.svg":      logo("#1d1b2e", !*static),
		"assets/logo-dark.svg": logo("#e8e6f0", !*static),
		"assets/icon.svg":      icon(),
	}
	paths := make([]string, 0, len(assets))
	for p := range assets {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	// -check is what keeps the assets honest. Editing the sprite and forgetting
	// to regenerate is silent otherwise: the banner changes, the logo does not,
	// and nothing says which one is the product.
	stale := false
	for _, p := range paths {
		if *check {
			have, err := os.ReadFile(p)
			if err != nil {
				fmt.Fprintln(os.Stderr, err)
				os.Exit(1)
			}
			if string(have) != assets[p] {
				fmt.Fprintf(os.Stderr, "%s is stale: run go run ./scripts/genlogo\n", p)
				stale = true
			}
			continue
		}
		if err := os.WriteFile(p, []byte(assets[p]), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		fmt.Println("wrote", p)
	}
	if stale {
		os.Exit(1)
	}
}
