package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// pi has no hooks; it has an extension API. Extensions in
// ~/.pi/agent/extensions/*.ts are auto-discovered, so installing is one file
// and no settings edit.
//
// before_agent_start is the injection point: it fires after the user submits a
// prompt, carries the prompt text, and can return a message that is stored in
// the session and sent to the model. That gives us both halves of what Claude
// Code splits across SessionStart and UserPromptSubmit.
//
// pi also has a real channel to the human — ctx.ui.notify — so the recall line
// and the "index still building" note go there instead of into the prompt.
func installPiExtension(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(sources.PiConfigDir(), "extensions")
	path := filepath.Join(dir, "deja.ts")
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.Remove(path); err != nil {
			return installResult{}, err
		}
		return installResult{Path: path, Action: "removed"}, nil
	}
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	next := []byte(piExtensionTS(exe))
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

func piExtensionTS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install pi-auto
import { execFileSync } from "node:child_process";

const DEJA = %q;

function run(args: string[], input: string, timeout = 10000): string {
  try {
    return execFileSync(DEJA, args, {
      input,
      encoding: "utf8",
      timeout,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

export default function (pi: any) {
  let injected = false;
  let toldBuilding = false;

  // pi keeps a footer status line: while the first index builds, that is
  // where the user can see it happening instead of wondering why recall is
  // quiet. Cleared as soon as the build finishes.
  const showBuild = (ctx: any) => {
    const status = run(["warmup-status"], "");
    if (status) {
      ctx.ui.setStatus("deja", status);
      return true;
    }
    ctx.ui.setStatus("deja", "");
    return false;
  };

  pi.on("session_start", async (_event: any, ctx: any) => {
    try {
      showBuild(ctx);
    } catch {
      // memory is optional: never break the session over it
    }
  });

  // pi surfaces registered commands in the prompt box, which is how someone
  // who never read the docs finds this at all.
  pi.registerCommand("deja", {
    description: "Search your own past coding sessions",
    handler: async (args: string, ctx: any) => {
      const query = (args || "").trim();
      if (!query) {
        ctx.ui.notify("Usage: /deja <what you are looking for>", "info");
        return;
      }
      // The user is waiting on this one, so it may outlive the hook budget:
      // a first search can rebuild the index.
      //
      // "--" when the query names one of deja's own flags: searching for
      // "--json" or "--all-matches" otherwise dies in flag parsing and comes
      // back as an empty history.
      const args = query.startsWith("-") ? ["search", "--", query] : ["search", query];
      const found = run(args, "", 120000);
      ctx.ui.notify(found || "Nothing in your history matches " + query, "info");
    },
  });

  pi.on("before_agent_start", async (event: any, ctx: any) => {
    try {
      if (!injected) {
        const raw = run(["hook-context"], "");
        let digest = "";
        let receipt = "";
        try {
          const parsed = JSON.parse(raw);
          digest = parsed?.hookSpecificOutput?.additionalContext || "";
          receipt = parsed?.systemMessage || "";
        } catch {
          digest = raw;
        }
        if (digest) {
          injected = true;
          ctx.ui.setStatus("deja", "");
          // The receipt is what tells the user memory arrived; without it the
          // recall is invisible and reads as the model guessing.
          if (receipt) ctx.ui.notify(receipt, "info");
          // pi keeps the footer until it is cleared, so the session carries a
          // quiet reminder that memory is on rather than a one-off toast.
          const stats = run(["statusline"], "");
          if (stats) ctx.ui.setStatus("deja", stats);
          return { message: { customType: "deja-recall", content: digest, display: false } };
        }
        // Nothing to recall: either there is no history yet, or the first
        // index is still building. Only the second is worth saying, once.
        if (!toldBuilding && showBuild(ctx)) {
          toldBuilding = true;
          ctx.ui.notify(run(["warmup-status"], ""), "info");
        }
        return;
      }
      // The session id lets recall skip what it already showed this session;
      // without one it repeats itself on every message.
      const sessionID = event.sessionId || event.session_id || ctx?.session?.id || "";
      const raw = run(["hook-prompt"], JSON.stringify({ prompt: event.prompt || "", session_id: sessionID }));
      if (!raw) return;
      const resp = JSON.parse(raw);
      if (resp && resp.systemMessage) ctx.ui.notify(resp.systemMessage, "info");
      const extra = resp && resp.hookSpecificOutput && resp.hookSpecificOutput.additionalContext;
      if (!extra) return;
      return { message: { customType: "deja-recall", content: extra, display: false } };
    } catch {
      // memory is optional: never break the session over it
    }
  });
}
`, exe)
}
