package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// VS Code shows a status bar item only from an extension
// (window.createStatusBarItem), and Copilot Chat 0.68 has no status line of its
// own. So vscode-auto writes a small local extension that runs `deja
// statusline` and shows the line on the right of the status bar.
//
// A folder dropped into the extensions directory is not enough: once
// extensions.json exists, VS Code 1.140 lists only the extensions named there
// (`code --list-extensions` against a stand). The entry goes in beside the
// reader's own, in the shape VS Code writes for one it found itself.

const (
	vsCodeStatusID      = "vshulcz.deja-status"
	vsCodeStatusVersion = "1.0.0"
)

// vsCodeExtensionDirs is the extensions directory of each VS Code host deja
// wires: ~/.vscode, ~/.vscode-insiders or ~/.vscode-oss beside the User folder
// that is there, or the stable one when none is yet. VSCODE_EXTENSIONS moves
// the stable one, as it does for VS Code.
func vsCodeExtensionDirs() []string {
	byHost := map[string]string{"Code": ".vscode", "Code - Insiders": ".vscode-insiders", "VSCodium": ".vscode-oss"}
	var out []string
	add := func(name string) {
		dir := filepath.Join(sources.Home(), name, "extensions")
		if name == ".vscode" {
			if v := strings.TrimSpace(os.Getenv("VSCODE_EXTENSIONS")); v != "" {
				dir = v
			}
		}
		if !slices.Contains(out, dir) {
			out = append(out, dir)
		}
	}
	for _, user := range vsCodeUserDirs() {
		name, ok := byHost[filepath.Base(filepath.Dir(user))]
		if !ok {
			name = ".vscode"
		}
		add(name)
	}
	if len(out) == 0 {
		add(".vscode")
	}
	return out
}

func vsCodeStatusPackageJSON() string {
	return `{
  "name": "deja-status",
  "displayName": "deja status",
  "description": "deja's status line in the status bar. Written by deja install vscode-auto; remove with deja uninstall vscode-auto.",
  "publisher": "vshulcz",
  "version": "` + vsCodeStatusVersion + `",
  "license": "MIT",
  "engines": { "vscode": "^1.57.0" },
  "main": "./extension.js",
  "activationEvents": ["onStartupFinished"]
}
`
}

// vsCodeStatusJS refreshes the item every 10 seconds. stdin is closed with the
// workspace folder as cwd, so the line does not wait for a payload.
func vsCodeStatusJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install vscode-auto; remove with: deja uninstall vscode-auto
"use strict";
const vscode = require("vscode");
const { execFile } = require("child_process");

const DEJA = %q;

function activate(context) {
  const item = vscode.window.createStatusBarItem("deja.status", vscode.StatusBarAlignment.Right, 100);
  item.name = "deja";
  item.tooltip = "deja: memory served to your agents";
  let busy = false;
  const refresh = () => {
    if (busy) return;
    busy = true;
    const folder = (vscode.workspace.workspaceFolders || [])[0];
    let child;
    try {
      child = execFile(DEJA, ["statusline"], { timeout: 5000, windowsHide: true, maxBuffer: 65536 }, (err, stdout) => {
        busy = false;
        const line = String(stdout || "").split("\n")[0].replace(/\x1b\[[0-9;]*m/g, "").trim();
        if (err || !line) {
          item.hide();
          return;
        }
        item.text = line;
        item.show();
      });
    } catch {
      busy = false;
      return;
    }
    if (child.stdin) {
      // deja can exit before reading stdin; the EPIPE that follows is not an error here.
      child.stdin.on("error", () => {});
      child.stdin.end(JSON.stringify({ cwd: folder ? folder.uri.fsPath : "" }));
    }
  };
  refresh();
  const timer = setInterval(refresh, 10000);
  context.subscriptions.push(item, { dispose: () => clearInterval(timer) });
}

module.exports = { activate, deactivate() {} };
`, exe)
}

// vsCodeURIPath is the path half of the file URI VS Code records: forward
// slashes, and on Windows a leading slash and a lower-case drive.
func vsCodeURIPath(goos, p string) string {
	if goos != "windows" {
		return filepath.ToSlash(p)
	}
	p = strings.ReplaceAll(p, `\`, "/")
	if len(p) >= 2 && p[1] == ':' {
		p = "/" + strings.ToLower(p[:1]) + p[1:]
	}
	return p
}

// setVSCodeExtensionEntry adds deja's entry to extensions.json, or takes it
// out, leaving every other entry byte for byte.
func setVSCodeExtensionEntry(extDir, dirName string, uninstall bool) (string, error) {
	path := filepath.Join(extDir, "extensions.json")
	old, err := readConfig(path)
	if err != nil {
		return "", err
	}
	var entries []json.RawMessage
	if len(strings.TrimSpace(string(old))) > 0 {
		if err := json.Unmarshal(old, &entries); err != nil {
			return "", configParseError(path, err)
		}
	}
	entry, err := json.Marshal(map[string]any{
		"identifier":       map[string]string{"id": vsCodeStatusID},
		"version":          vsCodeStatusVersion,
		"location":         map[string]any{"$mid": 1, "path": vsCodeURIPath(runtime.GOOS, filepath.Join(extDir, dirName)), "scheme": "file"},
		"relativeLocation": dirName,
	})
	if err != nil {
		return "", err
	}
	kept := entries[:0:0]
	same := false
	for _, e := range entries {
		var id struct {
			Identifier struct {
				ID string `json:"id"`
			} `json:"identifier"`
		}
		if json.Unmarshal(e, &id) == nil && strings.EqualFold(id.Identifier.ID, vsCodeStatusID) {
			same = same || string(e) == string(entry)
			continue
		}
		kept = append(kept, e)
	}
	ours := len(kept) < len(entries)
	// Nothing to take out, or our entry already there as it would be written:
	// the file stays as VS Code last wrote it.
	if uninstall && !ours || !uninstall && same && len(entries)-len(kept) == 1 {
		return "unchanged", nil
	}
	if !uninstall {
		kept = append(kept, entry)
	}
	next, err := json.Marshal(kept)
	if err != nil {
		return "", err
	}
	return writeIfChanged(path, old, next)
}

// installVSCodeStatusItem writes the extension into every host's extensions
// directory and names it in extensions.json; uninstall takes both back.
func installVSCodeStatusItem(exe string, uninstall bool) (installResult, error) {
	dirName := vsCodeStatusID + "-" + vsCodeStatusVersion
	var results []installResult
	for _, extDir := range vsCodeExtensionDirs() {
		dir := filepath.Join(extDir, dirName)
		if uninstall {
			had := isRealDir(dir)
			a, err := setVSCodeExtensionEntry(extDir, dirName, true)
			if err != nil {
				return installResult{}, err
			}
			results = append(results, installResult{Path: filepath.Join(extDir, "extensions.json"), Action: a})
			if err := os.RemoveAll(dir); err != nil {
				return installResult{}, err
			}
			action := "unchanged"
			if had {
				action = "removed"
				pruneCreatedDir(extDir)
			}
			results = append(results, installResult{Path: dir, Action: action})
			continue
		}
		pkg, err := readConfig(filepath.Join(dir, "package.json"))
		if err != nil {
			return installResult{}, err
		}
		a1, err := writeIfChanged(filepath.Join(dir, "package.json"), pkg, []byte(vsCodeStatusPackageJSON()))
		if err != nil {
			return installResult{}, err
		}
		js, err := readConfig(filepath.Join(dir, "extension.js"))
		if err != nil {
			return installResult{}, err
		}
		a2, err := writeIfChanged(filepath.Join(dir, "extension.js"), js, []byte(vsCodeStatusJS(hookExeFor(exe, false))))
		if err != nil {
			return installResult{}, err
		}
		a3, err := setVSCodeExtensionEntry(extDir, dirName, false)
		if err != nil {
			return installResult{}, err
		}
		action := a1
		if action == "unchanged" {
			action = a2
		}
		results = append(results, installResult{Path: dir, Action: action},
			installResult{Path: filepath.Join(extDir, "extensions.json"), Action: a3})
	}
	return wroteAll(results...), nil
}
