package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// The bootstrap hook recalls once, against the session, and only in gateway
// mode. OpenClaw's plugin runtime has the other half: before_prompt_build is
// handed the prompt the user just typed and returns context that goes in front
// of the model, and it fires under `openclaw agent --local` too.
//
// Learned by running it against OpenClaw 2026.7.1-2:
//   - A plugin needs both package.json with openclaw.extensions and
//     openclaw.plugin.json. Either one alone fails the install with a
//     validation error rather than being ignored.
//   - plugins.allow is advisory. Leaving it alone costs a warning on startup,
//     and writing to it would be deja deciding what the user trusts.
//   - The entry under plugins.entries is what enables the plugin; extensions/
//     is a discovery root, so no `openclaw plugins install` step is needed.
const openclawPluginID = "deja"

func installOpenClawPlugin(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(sources.OpenClawStateDir(), "extensions", openclawPluginID)
	if uninstall {
		if err := os.RemoveAll(dir); err != nil {
			return installResult{}, err
		}
		if _, err := setOpenClawPluginEnabled(false); err != nil {
			return installResult{}, err
		}
		return installResult{Path: dir, Action: "removed"}, nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return installResult{}, err
	}
	for _, f := range []struct{ name, body string }{
		{"package.json", openclawPluginPackage()},
		{"openclaw.plugin.json", openclawPluginManifest()},
	} {
		path := filepath.Join(dir, f.name)
		old, err := readConfig(path)
		if err != nil {
			return installResult{}, err
		}
		if _, err := writeIfChanged(path, old, []byte(f.body)); err != nil {
			return installResult{}, err
		}
	}
	entry := filepath.Join(dir, "index.mjs")
	old, err := readConfig(entry)
	if err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(entry, old, []byte(openclawPluginJS(exe)))
	if err != nil {
		return installResult{}, err
	}
	if _, err := setOpenClawPluginEnabled(true); err != nil {
		return installResult{}, err
	}
	return installResult{Path: entry, Action: a}, nil
}

// setOpenClawPluginEnabled adds or removes our entry under plugins.entries,
// leaving every other plugin — and the user's allow list — untouched.
func setOpenClawPluginEnabled(on bool) (string, error) {
	path := filepath.Join(sources.OpenClawStateDir(), "openclaw.json")
	old, err := readConfig(path)
	if err != nil {
		return "", err
	}
	var root map[string]any
	if len(bytes.TrimSpace(old)) == 0 {
		if !on {
			return "unchanged", nil
		}
		root = map[string]any{}
	} else if err := json.Unmarshal(old, &root); err != nil {
		return "", configParseError(path, err)
	}
	plugins, _ := root["plugins"].(map[string]any)
	entries, _ := mapAt(plugins, "entries")
	if !on {
		if entries == nil {
			return "unchanged", nil
		}
		delete(entries, openclawPluginID)
		if len(entries) == 0 {
			delete(plugins, "entries")
		}
		if len(plugins) == 0 {
			delete(root, "plugins")
		}
	} else {
		if plugins == nil {
			plugins = map[string]any{}
			root["plugins"] = plugins
		}
		if entries == nil {
			entries = map[string]any{}
			plugins["entries"] = entries
		}
		entries[openclawPluginID] = map[string]any{"enabled": true}
	}
	next, err := marshalConfigLike(old, root)
	if err != nil {
		return "", err
	}
	next = append(next, '\n')
	return writeIfChanged(path, old, next)
}

func openclawPluginPackage() string {
	return `{
  "name": "openclaw-deja",
  "version": "1.0.0",
  "type": "module",
  "private": true,
  "openclaw": {
    "extensions": ["./index.mjs"]
  }
}
`
}

func openclawPluginManifest() string {
	return `{
  "id": "` + openclawPluginID + `",
  "name": "deja recall",
  "description": "Recall the user's own past sessions for the question they just asked",
  "activation": {
    "onStartup": true
  },
  "configSchema": {
    "type": "object",
    "additionalProperties": false
  }
}
`
}

func openclawPluginJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install openclaw-auto
import { execFileSync } from "node:child_process";

const DEJA = %q;

export default {
  id: %q,
  name: "deja recall",
  register(api) {
    api.on(
      "before_prompt_build",
      async (event) => {
        const prompt = typeof event?.prompt === "string" ? event.prompt.trim() : "";
        if (!prompt) return;
        // Recall skips what it already showed this agent session, keyed by the
        // session id. A payload without one turns that off: measured on a real
        // store, half of all injections were then a word-for-word repeat.
        const sessionID = event?.sessionId || event?.session_id || event?.session?.id || "";
        let recall = "";
        try {
          recall = execFileSync(DEJA, ["hook-prompt", "--plain"], {
            input: JSON.stringify({ prompt, session_id: sessionID, cwd: process.cwd() }),
            encoding: "utf8",
            timeout: 10000,
            maxBuffer: 4 * 1024 * 1024,
            stdio: ["pipe", "pipe", "ignore"],
          }).trim();
        } catch {
          // Memory is optional: never take the turn down with it.
          return;
        }
        // Silence is the common case — the hook speaks only when the user's
        // own history answers what they just asked.
        if (!recall) return;
        return { prependContext: recall };
      },
      { timeoutMs: 15000 },
    );
  },
};
`, exe, openclawPluginID)
}
