package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// pi has no hooks; it has an extension API. Extensions in
// ~/.pi/agent/extensions/*.ts are auto-discovered, so installing is one file
// and no settings edit.
//
// before_agent_start is the injection point: it fires after the user submits a
// prompt, carries the prompt text, and can return a message that is stored in
// the session and sent to the model. That gives us both halves of what Claude
// Code splits across SessionStart and UserPromptSubmit.
//
// pi also has a real channel to the human — ctx.ui.notify — so the recall line
// and the "index still building" note go there instead of into the prompt.
func installPiExtension(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(sources.PiConfigDir(), "extensions")
	path := filepath.Join(dir, "deja.ts")
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.Remove(path); err != nil {
			return installResult{}, err
		}
		return installResult{Path: path, Action: "removed"}, nil
	}
	old, _ := os.ReadFile(path)
	next := []byte(piExtensionTS(exe))
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

func piExtensionTS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install pi-auto
import { execFileSync } from "node:child_process";

const DEJA = %q;

function run(args: string[], input: string): string {
  try {
    return execFileSync(DEJA, args, {
      input,
      encoding: "utf8",
      timeout: 10000,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

export default function (pi: any) {
  let injected = false;
  let toldBuilding = false;

  pi.on("before_agent_start", async (event: any, ctx: any) => {
    try {
      if (!injected) {
        const digest = run(["hook-context", "--plain"], "");
        if (digest) {
          injected = true;
          return { message: { customType: "deja-recall", content: digest, display: false } };
        }
        // Nothing to recall: either there is no history yet, or the first
        // index is still building. Only the second is worth saying, once.
        if (!toldBuilding) {
          const status = run(["warmup-status"], "");
          if (status) {
            toldBuilding = true;
            ctx.ui.notify(status, "info");
          }
        }
        return;
      }
      const raw = run(["hook-prompt"], JSON.stringify({ prompt: event.prompt || "" }));
      if (!raw) return;
      const resp = JSON.parse(raw);
      if (resp && resp.systemMessage) ctx.ui.notify(resp.systemMessage, "info");
      const extra = resp && resp.hookSpecificOutput && resp.hookSpecificOutput.additionalContext;
      if (!extra) return;
      return { message: { customType: "deja-recall", content: extra, display: false } };
    } catch {
      // memory is optional: never break the session over it
    }
  });
}
`, exe)
}
