package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// Codex (v0.114+) ships lifecycle hooks with the same JSON contract as
// Claude Code, so the existing `deja hook-context` output works unchanged.
// We merge one SessionStart entry into ~/.codex/hooks.json and leave
// everything else in the file alone.
func installCodexHooks(exe string, uninstall bool) (installResult, error) {
	h, _ := os.UserHomeDir()
	path := filepath.Join(h, ".codex", "hooks.json")
	old, _ := os.ReadFile(path)
	var root map[string]any
	if len(bytes.TrimSpace(old)) == 0 {
		root = map[string]any{}
	} else if err := json.Unmarshal(old, &root); err != nil {
		return installResult{}, err
	}
	cmd := exe + " hook-context"
	hooks, _ := root["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
		root["hooks"] = hooks
	}
	entries, _ := hooks["SessionStart"].([]any)
	var kept []any
	found := false
	for _, entryAny := range entries {
		entry, _ := entryAny.(map[string]any)
		if entry != nil && entryHasCommand(entry, cmd) {
			if uninstall {
				continue
			}
			// Take the entry over rather than leaving it as it was: an install
			// from a new binary path, or from a version that gained a field,
			// has to update ours in place or the change never reaches anyone
			// who already had it.
			found = true
			adoptCodexHookEntry(entry, cmd)
		}
		kept = append(kept, entryAny)
	}
	if !uninstall && !found {
		kept = append(kept, map[string]any{
			"matcher": "startup|resume",
			"hooks": []any{map[string]any{
				"type": "command", "command": cmd, "timeout": 10,
				// Codex surfaces statusMessage in its hook run summary.
				"statusMessage": hookStatusMessage("SessionStart"),
			}},
		})
	}
	if len(kept) == 0 {
		delete(hooks, "SessionStart")
	} else {
		hooks["SessionStart"] = kept
	}
	if len(hooks) == 0 {
		delete(root, "hooks")
	}
	next, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return installResult{}, err
	}
	next = append(next, '\n')
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

// entryHasCommand matches on the trailing subcommand rather than the whole
// string, so an install from a new binary path replaces our old entry instead
// of leaving it to fire alongside the new one.
// adoptCodexHookEntry rewrites the command and status message of an entry deja
// already owns.
func adoptCodexHookEntry(entry map[string]any, cmd string) {
	hs, _ := entry["hooks"].([]any)
	for _, hAny := range hs {
		h, _ := hAny.(map[string]any)
		if h == nil || h["type"] != "command" || !isDejaHookCommand(h["command"], cmd) {
			continue
		}
		h["command"] = cmd
		if msg := hookStatusMessage("SessionStart"); msg != "" {
			h["statusMessage"] = msg
		}
	}
}

func entryHasCommand(entry map[string]any, cmd string) bool {
	hs, _ := entry["hooks"].([]any)
	for _, hAny := range hs {
		h, _ := hAny.(map[string]any)
		if h != nil && h["type"] == "command" && isDejaHookCommand(h["command"], cmd) {
			return true
		}
	}
	return false
}

// opencode has no session-start hook; its plugin API can push text onto the
// system prompt per request. The generated plugin shells out to
// `deja hook-context --plain` once per session and caches the result.
func installOpencodePlugin(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(opencodeConfigHome(), "opencode", "plugins")
	path := filepath.Join(dir, "deja.js")
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.Remove(path); err != nil {
			return installResult{}, err
		}
		return installResult{Path: path, Action: "removed"}, nil
	}
	old, _ := os.ReadFile(path)
	next := []byte(opencodePluginJS(exe))
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

func opencodePluginJS(exe string) string {
	// opencode's hook output goes into the model's context, so a progress
	// note cannot ride along with it — it would be prompt noise. The TUI
	// toast is the channel meant for the human, so the build announces itself
	// there instead, once per session so it does not nag on every turn.
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install opencode-auto
export const DejaRecall = async ({ $, client }) => {
  const cache = new Map()
  const told = new Set()
  return {
    "experimental.chat.system.transform": async (input, output) => {
      try {
        const key = input.sessionID || "default"
        if (!cache.has(key)) {
          const raw = await $%s%q %s%s.text()
          let ctx = "", receipt = ""
          try {
            const parsed = JSON.parse(raw)
            ctx = parsed?.hookSpecificOutput?.additionalContext || ""
            receipt = parsed?.systemMessage || ""
          } catch {
            ctx = raw.trim()
          }
          cache.set(key, ctx)
          // The receipt is the only sign the user gets that memory arrived.
          // Once per session: repeating it every turn is wallpaper.
          if (receipt && !told.has(key)) {
            told.add(key)
            await client.tui.showToast({ body: { message: receipt, variant: "info", duration: 6000 } })
          }
        }
        const ctx = cache.get(key)
        if (ctx) {
          output.system.push(ctx)
          return
        }
        // Nothing to recall: either there is no history yet, or the first
        // index is still being built. Only the second is worth saying.
        if (told.has(key)) return
        const status = (await $%s%q %s%s.text()).trim()
        if (!status) return
        told.add(key)
        cache.delete(key)
        await client.tui.showToast({ body: { message: status, variant: "info", duration: 6000 } })
      } catch {
        // memory is optional: never break the session over it
      }
    },
    // Compaction is about to throw away the working transcript. Claude Code
    // gets the same treatment through PreCompact: index what exists now, so
    // the session survives in memory even after the window is collapsed.
    "experimental.session.compacting": async () => {
      try {
        await $%s%q hook-precompact%s.quiet()
      } catch {
        // memory is optional: never break a compaction over it
      }
    },
    // Per-prompt recall, the same relevance pass Claude Code gets on
    // UserPromptSubmit: the session digest is ranked by the project, this is
    // ranked by what the user just asked. Silent when nothing matches.
    "experimental.chat.messages.transform": async (_input, output) => {
      try {
        const msgs = output.messages || []
        let last
        for (let i = msgs.length - 1; i >= 0; i--) {
          if (msgs[i]?.info?.role === "user") { last = msgs[i]; break }
        }
        if (!last) return
        const parts = (last.parts || []).filter((p) => p?.type === "text" && p.text)
        const prompt = parts.map((p) => p.text).join("\n").trim()
        if (!prompt) return
        const raw = await $%secho ${JSON.stringify({ prompt })} | %s%q hook-prompt%s.text()
        if (!raw.trim()) return
        const extra = JSON.parse(raw)?.hookSpecificOutput?.additionalContext
        if (!extra) return
        parts[parts.length - 1].text += "\n\n" + extra
      } catch {
        // memory is optional: never break the session over it
      }
    },
  }
}
`, "`", exe, "hook-context", "`", "`", exe, "warmup-status", "`", "`", exe, "`", "`", "", exe, "`")
}

// Gemini CLI and Qwen Code both run a command before the agent loop, which is
// the same injection point Claude Code's SessionStart gives us — so
// auto-recall works there too, not just MCP on demand.
//
// They are not the same shape, and both differences were found by running
// them rather than by reading their bundles:
//
//   - Gemini calls the event BeforeAgent (it has no SessionStart) and reads
//     `timeout` in MILLISECONDS. A Claude-style `"timeout": 10` is ten
//     milliseconds there, and the hook is killed before it can answer.
//   - Qwen forked from an older Gemini and kept SessionStart with a matcher,
//     with `timeout` in seconds.
func installGeminiAuto(exe string, uninstall bool) (installResult, error) {
	// Clear the settings.json hook older versions wrote: it never fired, and
	// leaving it behind makes a dead integration look installed.
	if _, err := installSettingsHook(
		filepath.Join(sources.GeminiHome(), "settings.json"),
		"BeforeAgent", "", 10000, exe, true); err != nil {
		return installResult{}, err
	}
	return installGeminiExtension(exe, uninstall)
}

// Qwen took two wrong readings to get right. Its `timeout` is MILLISECONDS,
// like Gemini's — the 10 deja used to write killed the hook ten milliseconds
// in, which is indistinguishable from a harness that has no hooks. And while
// SessionStart does fire, only UserPromptSubmit consumes additionalContext
// (appendUserPromptExpansionAdditionalContext), and Qwen checks that the
// hookEventName in the reply matches the event — so the SessionStart-shaped
// output of `hook-context` was dropped without a word.
func installQwenAuto(exe string, uninstall bool) (installResult, error) {
	return installSettingsHookCmd(
		filepath.Join(sources.QwenConfigDir(), "settings.json"),
		"UserPromptSubmit", "", 60000, exe+" hook-prompt", uninstall)
}

// installSettingsHook merges one hook entry into a settings.json that the
// host also uses for everything else, leaving the rest of the file alone.
func installSettingsHook(path, event, matcher string, timeout int, exe string, uninstall bool) (installResult, error) {
	return installSettingsHookCmd(path, event, matcher, timeout, exe+" hook-context", uninstall)
}

func installSettingsHookCmd(path, event, matcher string, timeout int, cmd string, uninstall bool) (installResult, error) {
	old, _ := os.ReadFile(path)
	var root map[string]any
	if len(bytes.TrimSpace(old)) == 0 {
		root = map[string]any{}
	} else if err := json.Unmarshal(old, &root); err != nil {
		return installResult{}, err
	}
	hooks, _ := root["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
		root["hooks"] = hooks
	}
	entries, _ := hooks[event].([]any)
	var kept []any
	found := false
	for _, entryAny := range entries {
		entry, _ := entryAny.(map[string]any)
		if entry != nil && entryHasCommand(entry, cmd) {
			if uninstall {
				continue
			}
			// Take the entry over rather than leaving it as it was: an install
			// from a new binary path, or from a version that gained a field,
			// has to update ours in place or the change never reaches anyone
			// who already had it.
			found = true
			adoptCodexHookEntry(entry, cmd)
		}
		kept = append(kept, entryAny)
	}
	if !uninstall && !found {
		entry := map[string]any{
			"hooks": []any{map[string]any{"type": "command", "command": cmd, "timeout": timeout}},
		}
		if matcher != "" {
			entry["matcher"] = matcher
		}
		kept = append(kept, entry)
	}
	if len(kept) == 0 {
		delete(hooks, event)
	} else {
		hooks[event] = kept
	}
	if len(hooks) == 0 {
		delete(root, "hooks")
	}
	next, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return installResult{}, err
	}
	next = append(next, '\n')
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

// kimiHookMarker identifies our block in a config the user also edits by
// hand. Kimi keeps hooks in config.toml as an array of tables, so removal
// cannot key on a table name the way the MCP block does — several [[hooks]]
// entries are legal and only one of them is ours.
const kimiHookMarker = "# deja: auto-recall (managed by `deja install kimi-auto`)"

// Kimi Code runs SessionStart hooks, so auto-recall works there too. Its
// config is TOML, not JSON, and the entry is a flat table rather than the
// nested matcher/hooks shape Claude uses.
// Kimi injects the hook's plain stdout, not a JSON field — its structured
// output only carries permission decisions. And only UserPromptSubmit does it:
// a SessionStart hook runs and its output goes nowhere, which is what made
// this look like a harness that cannot take context at all.
func installKimiAuto(exe string, uninstall bool) (installResult, error) {
	path := filepath.Join(sources.KimiConfigDir(), "config.toml")
	old, _ := os.ReadFile(path)
	s := strings.TrimRight(removeKimiHookBlock(string(old)), "\n")
	if !uninstall {
		block := kimiHookMarker + "\n[[hooks]]\nevent = \"UserPromptSubmit\"\ncommand = " +
			strconv.Quote(exe+" hook-prompt --plain") + "\ntimeout = 30\n"
		if s != "" {
			s += "\n\n"
		}
		s += block
	} else if s != "" {
		s += "\n"
	}
	a, err := writeIfChanged(path, old, []byte(s))
	return installResult{Path: path, Action: a}, err
}

// removeKimiHookBlock drops our marked entry and nothing else: the next table
// header ends it, so a hand-written [[hooks]] below survives.
func removeKimiHookBlock(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	for i := 0; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) != kimiHookMarker {
			out = append(out, lines[i])
			continue
		}
		i++ // skip the marker
		if i < len(lines) && strings.HasPrefix(strings.TrimSpace(lines[i]), "[[hooks]]") {
			i++
		}
		for i < len(lines) && !strings.HasPrefix(strings.TrimSpace(lines[i]), "[") {
			i++
		}
		i-- // the loop's own i++ steps onto the next table header
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n") + "\n"
}
