package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// prime-agent is pi's lineage — same JSONL envelope, same extension API — so
// the wiring is pi's with the parts prime-agent does not deliver left out.
//
// Measured on prime-agent 0.9.1 with a probe extension and a recording
// endpoint:
//   - before_agent_start fires and the message it returns arrives in the
//     provider request, which is the channel the digest and per-prompt recall
//     ride.
//   - session_start fires, so the footer can say the first index is building.
//   - tool_call and tool_result never fire in --print, although the extension
//     docs list them. Without tool_result there is nowhere to put the repair
//     that follows a failed command, so that half is not wired here rather
//     than wired to an event that stays quiet.
//   - MCP servers are read from ~/.prime/agent/settings.json, and the shared
//     ~/.agents/skills directory is loaded — `deja install` writes the skill
//     there already.
func installPrimeMCP(exe string, uninstall bool) (installResult, error) {
	return installPrimeMCPAt(primeSettingsPath(), exe, uninstall)
}

func primeSettingsPath() string {
	return filepath.Join(sources.PrimeConfigDir(), "settings.json")
}

func installPrimeMCPAt(path, exe string, uninstall bool) (installResult, error) {
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	// A JSONC file goes through the text writer, so a comment the reader
	// kept stays; re-marshalling the object dropped it for good (#3243).
	if len(bytes.TrimSpace(old)) > 0 && configIsJSONC(old) {
		command, args := mcpCommandArgs(exe)
		return writeJSONCEntry(path, old, "mcpServers",
			map[string]any{"type": "stdio", "command": command, "args": args}, uninstall)
	}
	var root map[string]any
	if len(bytes.TrimSpace(old)) == 0 {
		if uninstall {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		root = map[string]any{}
	} else if err := json.Unmarshal([]byte(jsoncToJSON(string(old))), &root); err != nil {
		return installResult{}, configParseError(path, err)
	}
	servers, _ := root["mcpServers"].(map[string]any)
	if servers == nil {
		if uninstall {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		servers = map[string]any{}
		root["mcpServers"] = servers
	}
	if uninstall {
		delete(servers, "deja")
		if len(servers) == 0 {
			delete(root, "mcpServers")
		}
	} else {
		command, args := mcpCommandArgs(exe)
		// type: "stdio" explicitly: prime-agent's settings carry both stdio and
		// http servers under the same key, and its docs write the type out.
		servers["deja"] = map[string]any{"type": "stdio", "command": command, "args": args}
	}
	next, err := marshalConfigLike(old, root)
	if err != nil {
		return installResult{}, err
	}
	next = append(next, '\n')
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

// installPrimeAuto writes the extension and the MCP server both, for the same
// reason pi does: a digest with no tool to follow it up with is half an install.
func installPrimeAuto(exe string, uninstall bool) (installResult, error) {
	mcp, err := installPrimeMCP(exe, uninstall)
	if err != nil {
		return installResult{}, err
	}
	ext, err := installPrimeExtension(exe, uninstall)
	if err != nil {
		return installResult{}, err
	}
	return wroteAll(mcp, ext), nil
}

func primeExtensionPath() string {
	return filepath.Join(sources.PrimeConfigDir(), "extensions", "deja.ts")
}

func installPrimeExtension(exe string, uninstall bool) (installResult, error) {
	path := primeExtensionPath()
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.Remove(path); err != nil {
			return installResult{}, err
		}
		return installResult{Path: path, Action: "removed"}, nil
	}
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(path, old, []byte(primeExtensionTS(exe)))
	return installResult{Path: path, Action: a}, err
}

func primeExtensionTS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install prime-auto
import { execFileSync } from "node:child_process";

const DEJA = %q;

function run(args: string[], input: string, timeout = 10000): string {
  try {
    return execFileSync(DEJA, args, {
      input,
      encoding: "utf8",
      timeout,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

export default function (pi: any) {
  let injected = false;
  let toldBuilding = false;
  // No event carries a session id; the session manager does, and every handler
  // reaches it through ctx. Recall dedupes per session, so without one the same
  // block goes out on every message.
  let session = "";
  const remember = (ctx: any) => {
    try {
      const m = ctx && ctx.sessionManager;
      const id = m && (m.getSessionId ? m.getSessionId() : m.sessionId);
      if (id) session = String(id);
    } catch {}
  };
  const sessionID = () => session;

  // prime-agent keeps a footer status line: while the first index builds, that
  // is where the user can see it happening instead of wondering why recall is
  // quiet.
  const showBuild = (ctx: any) => {
    const status = run(["warmup-status"], "");
    if (status) {
      ctx.ui.setStatus("deja", status);
      return true;
    }
    ctx.ui.setStatus("deja", "");
    return false;
  };

  pi.on("session_start", async (_event: any, ctx: any) => {
    try {
      remember(ctx);
      showBuild(ctx);
    } catch {
      // memory is optional: never break the session over it
    }
  });

  // Registered commands show up in the prompt box, which is how someone who
  // never read the docs finds this at all.
  pi.registerCommand("deja", {
    description: "Search your own past coding sessions",
    handler: async (args: string, ctx: any) => {
      const query = (args || "").trim();
      if (!query) {
        ctx.ui.notify("Usage: /deja <what you are looking for>", "info");
        return;
      }
      // The user is waiting on this one, so it gets a longer budget than a
      // hook: a first search can rebuild the index. "--" keeps a query that
      // starts with a dash out of deja's own flag parsing.
      const commandArgs = query.startsWith("-") ? ["search", "--", query] : ["search", query];
      const found = run(commandArgs, "", 120000);
      ctx.ui.notify(found || "Nothing in your history matches " + query, "info");
    },
  });

  // The one channel that reaches the model here: what it returns is stored in
  // the session and sent with the turn. The first run carries the project
  // digest, every one after it the recall for the question just asked.
  pi.on("before_agent_start", async (event: any, ctx: any) => {
    try {
      remember(ctx);
      if (!injected) {
        const raw = run(["hook-context"], "");
        let digest = "";
        let receipt = "";
        try {
          const parsed = JSON.parse(raw);
          digest = parsed?.hookSpecificOutput?.additionalContext || "";
          receipt = parsed?.systemMessage || "";
        } catch {
          digest = raw;
        }
        if (digest) {
          injected = true;
          ctx.ui.setStatus("deja", "");
          // The receipt is what tells the user memory arrived; without it the
          // recall is invisible and reads as the model guessing.
          if (receipt) ctx.ui.notify(receipt, "info");
          const stats = run(["statusline"], "");
          if (stats) ctx.ui.setStatus("deja", stats);
          return { message: { customType: "deja-recall", content: digest, display: false } };
        }
        // Nothing to recall: either there is no history yet, or the first
        // index is still building. Only the second is worth saying, once.
        if (!toldBuilding && showBuild(ctx)) {
          toldBuilding = true;
          ctx.ui.notify(run(["warmup-status"], ""), "info");
        }
        return;
      }
      const raw = run(["hook-prompt"], JSON.stringify({ prompt: event.prompt || "", session_id: sessionID() }));
      if (!raw) return;
      const resp = JSON.parse(raw);
      if (resp && resp.systemMessage) ctx.ui.notify(resp.systemMessage, "info");
      const extra = resp && resp.hookSpecificOutput && resp.hookSpecificOutput.additionalContext;
      if (!extra) return;
      return { message: { customType: "deja-recall", content: extra, display: false } };
    } catch {
      // memory is optional: never break the session over it
    }
  });

  // Compaction throws away the blocks this session was shown, and the list that
  // stops them repeating outlives them. Forgetting is a side effect, which is
  // all this event can carry.
  pi.on("session_compact", async (_event: any) => {
    try {
      run(["hook-precompact"], JSON.stringify({ session_id: sessionID() }));
    } catch {}
  });
}
`, exe)
}
