package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// Amp keeps everything in one settings file: MCP servers under the dotted key
// amp.mcpServers, which `amp mcp add` writes and `amp mcp doctor` reads back.
// The key is a literal with a dot in it, not a nested object, so it cannot go
// through the nested-path writer.
func installAmpMCP(exe string, uninstall bool) (installResult, error) {
	return installAmpMCPAt(sources.AmpSettingsFile(), exe, uninstall)
}

func installAmpMCPAt(path, exe string, uninstall bool) (installResult, error) {
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	// A JSONC file goes through the text writer, so the reader's comments and
	// key order stay through an install and an uninstall, as for prime (#4357).
	// The dot is escaped: one literal key, not an "amp" object.
	if len(bytes.TrimSpace(old)) > 0 && configIsJSONC(old) {
		return writeJSONCEntry(path, old, strings.ReplaceAll(ampServersKey, ".", `\.`), ampServerEntry(exe), uninstall)
	}
	var root map[string]any
	if len(bytes.TrimSpace(old)) == 0 {
		if uninstall {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		root = map[string]any{}
	} else if err := json.Unmarshal([]byte(jsoncToJSON(string(old))), &root); err != nil {
		return installResult{}, configParseError(path, err)
	}
	servers, _ := root[ampServersKey].(map[string]any)
	if servers == nil {
		if uninstall {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		servers = map[string]any{}
		root[ampServersKey] = servers
	}
	var note string
	if uninstall {
		delete(servers, "deja")
		removeAdoptedDejaEntries(path, strings.ReplaceAll(ampServersKey, ".", `\.`), servers)
		note = leftDejaEntriesNote(servers)
		if len(servers) == 0 {
			delete(root, ampServersKey)
		}
	} else {
		// deja under another name is adopted, not doubled (#4556). Recorded
		// under the escaped key, the spelling the JSONC writer records.
		key := dejaEntryKey(servers)
		if key != "deja" {
			noteBlockAdded(path, strings.ReplaceAll(ampServersKey, ".", `\.`)+"."+key)
		}
		servers[key] = ampServerEntry(exe)
		note = withOtherDejaEntries("", servers, key)
	}
	next, err := marshalConfigLike(old, root)
	if err != nil {
		return installResult{}, err
	}
	next = append(next, '\n')
	noteCreatedDirs(filepath.Dir(path))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a, Note: note}, err
}

// The key is one literal string with a dot in it — the way Amp's own
// `amp mcp add` writes it — not a nested "amp" object.
const ampServersKey = "amp.mcpServers"

func ampServerEntry(exe string) map[string]any {
	command, args := mcpCommandArgs(exe)
	return map[string]any{"command": command, "args": args}
}

// installAmpAuto writes the plugin and the MCP server both: the plugin puts
// memory in front of the model unasked, and the server is what the model calls
// when the block makes it curious.
func installAmpAuto(exe string, uninstall bool) (installResult, error) {
	mcp, err := installAmpMCP(exe, uninstall)
	if err != nil {
		return installResult{}, err
	}
	plugin, err := installAmpPlugin(exe, uninstall)
	if err != nil {
		return installResult{}, err
	}
	return wroteAll(mcp, plugin), nil
}

// ampPluginPath is Amp's system-plugin directory: ~/.config/amp/plugins/*.ts,
// auto-discovered, so installing is one file and no settings edit.
func ampPluginPath() string {
	return filepath.Join(sources.AmpConfigDir(), "plugins", "deja.ts")
}

func installAmpPlugin(exe string, uninstall bool) (installResult, error) {
	// The launcher, not this binary: a generated plugin is as much a
	// config as a hooks.json, and one that names the build it was
	// installed from stops working the day that build moves (#3682).
	exe = hookExeFor(exe, uninstall)
	path := ampPluginPath()
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.Remove(path); err != nil {
			return installResult{}, err
		}
		// And the plugins directory deja made for it (#3698).
		pruneCreatedDir(filepath.Dir(path))
		return installResult{Path: path, Action: "removed"}, nil
	}
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	noteCreatedDirs(filepath.Dir(path))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(path, old, []byte(ampPluginTS(exe)))
	return installResult{Path: path, Action: a}, err
}

func ampPluginTS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install amp-auto
import { execFileSync } from "node:child_process"
import { mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"

export const description = "Recall from this machine's past coding sessions, across every AI tool used here"

const DEJA = %q
// Amp keeps threads on its server; the plugin writes each one it sees here, in
// the thread file shape deja reads.
const THREADS = %q

// A thread as the plugin API reads it, 20 messages a call. full: true reads
// the turns a compaction took out of the model's view as well.
async function readMessages(thread: any, full: boolean, limit = 5000): Promise<any[]> {
  const out: any[] = []
  for (let offset = 0; offset < limit; offset += 20) {
    const page = await thread.messages({ from: "start", offset, limit: 20, full })
    if (!Array.isArray(page)) break
    out.push(...page)
    if (page.length < 20) break
  }
  return out
}

function resultText(output: any): string {
  if (typeof output === "string") return output
  if (!Array.isArray(output)) return ""
  return output.filter((b: any) => b && b.type === "text").map((b: any) => b.text).join("\n")
}

// The thread file Amp itself wrote before threads moved to its server.
function threadFile(id: string, messages: any[], created: number): string {
  const blocks = (m: any) => (Array.isArray(m.content) ? m.content : []).flatMap((b: any) => {
    if (!b) return []
    if (b.type === "text") return [{ type: "text", text: b.text }]
    if (b.type === "tool_use") return [{ type: "tool_use", id: b.id, name: b.name, input: b.input }]
    if (b.type === "tool_result") return [{ type: "tool_result", toolUseID: b.toolUseID, run: { status: b.status, result: resultText(b.output) } }]
    return []
  })
  return JSON.stringify({
    id,
    title: "",
    created,
    env: { initial: { trees: [{ uri: "file://" + process.cwd() }] } },
    messages: messages.filter((m: any) => m && (m.role === "user" || m.role === "assistant")).map((m: any) => ({ role: m.role, content: blocks(m) })),
  })
}

function createdOf(path: string): number {
  try {
    const n = JSON.parse(readFileSync(path, "utf8")).created
    if (typeof n === "number" && n > 0) return n
  } catch {}
  return Date.now()
}

function run(args: string[], input: string, timeout = 10000): string {
  try {
    return execFileSync(DEJA, args, {
      input,
      encoding: "utf8",
      timeout,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim()
  } catch {
    // Memory is optional: a plugin that throws here would take the turn with it.
    return ""
  }
}

export default function (amp: any) {
  // The thread that has had its digest. Amp keeps one process across threads,
  // and a flag set once per process left every thread after the first with no
  // memory (#3263).
  let injected = ""
  // Amp's events carry the thread, and the thread id is what recall dedupes on:
  // without it the same block goes out on every message of the session.
  let thread = ""
  const threadID = (event: any) => {
    const id = event && event.thread && event.thread.id
    if (id) thread = String(id)
    return thread
  }

  // Fire-and-forget: the only thing session.start can do is talk to the user,
  // and while a first index builds that is worth saying once.
  amp.on("session.start", async (event: any, ctx: any) => {
    try {
      threadID(event)
      const status = run(["warmup-status"], "")
      if (status) await ctx.ui.notify(status)
    } catch {}
  })

  // agent.start is the injection point. It carries the prompt and its return
  // value is appended to the user message, which is both halves of what Claude
  // Code splits across SessionStart and UserPromptSubmit.
  // Amp has no compaction event. After one, the messages a new turn sees open
  // with the summary, while full: true still starts at the thread's first
  // turn; the turns before the first message kept are what the compaction
  // took away. deja captures them once, and the packet rides hook-prompt.
  const compactions = new Set<string>()
  const catchUp = async (id: string, thread: any) => {
    if (!id || !thread || typeof thread.messages !== "function") return
    const view = await thread.messages({ from: "start", limit: 2 })
    const first = await thread.messages({ from: "start", limit: 1, full: true })
    if (!view || !view[0] || !first || !first[0] || view[0].id === first[0].id) return
    const kept = view[1] ? view[1].id : undefined
    const key = id + ":" + String(view[0].id) + ":" + String(kept)
    if (compactions.has(key)) return
    compactions.add(key)
    const all = await readMessages(thread, true)
    const cut = kept === undefined ? all.length : all.findIndex((m: any) => m && m.id === kept)
    if (cut <= 0) return
    const tmp = join(tmpdir(), "deja-amp-" + process.pid + "-" + Date.now() + ".json")
    try {
      writeFileSync(tmp, threadFile(id, all.slice(0, cut), createdOf(join(THREADS, id + ".json"))))
      run(["hook-precompact"], JSON.stringify({
        session_id: id, transcript_path: tmp, cwd: process.cwd(), harness: "amp", deja_catch_up: true,
      }), 30000)
    } finally {
      try {
        unlinkSync(tmp)
      } catch {}
    }
  }

  amp.on("agent.start", async (event: any, ctx: any) => {
    try {
      const id = threadID(event)
      try {
        await catchUp(id, ctx && ctx.thread)
      } catch {}
      if (injected !== (id || "*")) {
        injected = id || "*"
        // The thread goes with it, so deja's own once-per-session mark holds
        // across a restart of the process the way it does for Claude Code.
        const raw = run(["hook-context"], JSON.stringify({
          session_id: id,
          cwd: process.cwd(),
          deja_once: true,
        }))
        let digest = raw
        let receipt = ""
        try {
          const parsed = JSON.parse(raw)
          digest = (parsed && parsed.hookSpecificOutput && parsed.hookSpecificOutput.additionalContext) || ""
          receipt = (parsed && parsed.systemMessage) || ""
        } catch {}
        if (digest) {
          // The receipt is what tells the user memory arrived; without it the
          // recall is invisible and reads as the model guessing.
          if (receipt) {
            try {
              await ctx.ui.notify(receipt)
            } catch {}
          }
          return { message: { content: digest, display: false } }
        }
      }
      const raw = run(["hook-prompt", "--plain"], JSON.stringify({
        prompt: event.message || "",
        session_id: id,
        cwd: process.cwd(),
      }))
      // Silence is the common case: the hook speaks only when this machine's
      // history answers what was just asked.
      if (!raw) return
      return { message: { content: raw, display: false } }
    } catch {}
  })

  // The point of action. A command has just failed and this machine has fixed
  // that same error before; tool.result hands over the output the model is
  // about to read and takes a replacement back, so the repair arrives beside
  // the error instead of a turn later. tool.call cannot carry it: its result is
  // allow, reject, modify-input or synthesize — none of them add context.
  const repaired: Record<string, string> = {}
  // A file's history goes the same way, after Read, the step before an edit,
  // and after edit_file and create_file for the edits after it. deja answers
  // once per thread per fact.
  const FILE_TOOLS: Record<string, string> = { Read: "read", edit_file: "edit", create_file: "write" }
  amp.on("tool.result", async (event: any) => {
    try {
      if (!event) return
      const fileTool = FILE_TOOLS[event.tool]
      if (fileTool) {
        if (event.status !== "done" || typeof event.output !== "string") return
        const path = String((event.input && (event.input.path || event.input.file_path)) || "")
        if (!path) return
        const id = "file:" + String(event.toolUseID || "")
        if (!(id in repaired)) {
          repaired[id] = run(["hook-tool", "--plain"], JSON.stringify({
            tool_name: fileTool,
            tool_input: { file_path: path },
            session_id: threadID(event),
            cwd: process.cwd(),
          }))
        }
        const line = repaired[id]
        if (!line) return
        return { status: "done", output: event.output + "\n\n" + line }
      }
      if (event.status !== "error") return
      if (event.tool !== "shell_command" && event.tool !== "Bash") return
      const output = typeof event.output === "string" ? event.output : JSON.stringify(event.output ?? "")
      const text = (output || "") + (event.error ? "\n" + event.error : "")
      if (!text.trim()) return
      const id = String(event.toolUseID || "")
      if (!(id in repaired)) {
        repaired[id] = run(["hook-tool-after", "--plain"], JSON.stringify({
          tool_name: "bash",
          tool_response: text,
          session_id: threadID(event),
          cwd: process.cwd(),
        }))
      }
      const line = repaired[id]
      if (!line) return
      return { status: "error", error: event.error, output: text + "\n" + line }
    } catch {
      // never turn a failed command into a failed thread
    }
  })

  // A turn is over when the agent ends: the thread's live stamp goes, so
  // another thread's MCP recall can answer with it now rather than twenty
  // minutes from now, and its next agent.start stamps it again. Amp has no
  // event for a thread ending; a plugin disposed with the process ends the
  // last one it served. agent.end's answer decides whether the agent goes on,
  // so this one gives Amp's own default back.
  const endThread = (id: string) => {
    if (id) run(["hook-session-end"], JSON.stringify({ session_id: id }), 2000)
  }
  // The thread goes to the store as it stands, whole, so deja indexes it like
  // any other session; written aside and renamed, a reader never sees half.
  const exportThread = async (id: string, thread: any) => {
    if (!id || !thread || typeof thread.messages !== "function") return
    const all = await readMessages(thread, true)
    if (all.length === 0) return
    mkdirSync(THREADS, { recursive: true })
    const path = join(THREADS, id + ".json")
    const tmp = path + ".tmp-" + process.pid
    writeFileSync(tmp, threadFile(id, all, createdOf(path)))
    renameSync(tmp, path)
  }

  // A status item beside the prompt editor: deja's one line on what it has
  // recalled today, refreshed after every turn.
  let status: any = null
  const showStatus = () => {
    try {
      const text = run(["statusline"], "", 2000)
      if (!text) return
      if (status) status.update({ text })
      else status = amp.createStatusItem({ text })
    } catch {}
  }
  showStatus()

  amp.on("agent.end", async (event: any, ctx: any) => {
    try {
      endThread(threadID(event))
    } catch {}
    try {
      await exportThread(threadID(event), ctx && ctx.thread)
    } catch {}
    showStatus()
    return { action: "done" }
  })
  try {
    amp.onDispose(() => endThread(thread))
  } catch {}

  // Amp surfaces registered commands in its command palette, which is how
  // someone who never read the docs finds this at all.
  amp.registerCommand(
    "deja",
    { title: "search past sessions", category: "deja", description: "Search your own past coding sessions" },
    async (ctx: any) => {
      const query = String((await ctx.ui.input({
        title: "deja",
        helpText: "What are you looking for in your own past sessions?",
      })) || "").trim()
      if (!query) return
      // The user is waiting on this one, so it gets a longer budget than a
      // hook: a first search can rebuild the index. "--" keeps a query that
      // starts with a dash out of deja's own flag parsing.
      const args = query.startsWith("-") ? ["search", "--", query] : ["search", query]
      const found = run(args, "", 120000)
      await ctx.ui.notify(found || "Nothing in your history matches " + query)
    },
  )
}
`, exe, sources.AmpRoot())
}
