package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// Cline's hooks cannot carry context: TaskStart and UserPromptSubmit are
// spawned detached with stdout closed, PreToolUse keeps only cancel and
// overrideInput, PreCompact is mapped to no event at all, and --hooks-dir is
// read by nothing. Verified against CLI 3.0.46.
//
// Plugins are the channel that works. A registered rule takes a function for
// its content, resolved when the session builds its instructions — which is
// session-start recall by another name — and a registered command puts /deja
// in the same session.
//
// A rule is handed nothing, so it recalls against the session rather than the
// question. registerMessageBuilder is the prompt-aware half: its build is
// called with the messages on their way to the model, and a new array returned
// from it is what gets sent. Editing the array in place is discarded, as is a
// string or a {messages} wrapper — verified against CLI 3.0.54.
func installClineAuto(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(sources.ClinePluginsDir(), "deja")
	path := filepath.Join(dir, "index.js")
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.RemoveAll(dir); err != nil {
			return installResult{}, err
		}
		return installResult{Path: path, Action: "removed"}, nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return installResult{}, err
	}
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(path, old, []byte(clinePluginJS(exe)))
	if err != nil {
		return installResult{}, err
	}
	// Cline discovers skills bundled in the plugin package, which is the only
	// channel it has for one: it has no user-level instructions file, so until
	// now it got the recall rule and no manual at all. Written after index.js
	// so a failure here leaves a working plugin rather than a directory the
	// uninstall path would not recognise.
	skill := filepath.Join(dir, "skills", "deja-history")
	if err := os.MkdirAll(skill, 0o755); err != nil {
		return installResult{}, err
	}
	oldSkill, err := readConfig(filepath.Join(skill, "SKILL.md"))
	if err != nil {
		return installResult{}, err
	}
	if _, err := writeGuidanceFile(filepath.Join(skill, "SKILL.md"), oldSkill, []byte(skillFile(skillBody))); err != nil {
		return installResult{}, err
	}
	return installResult{Path: path, Action: a}, nil
}

func clinePluginJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install cline-auto
import { execFileSync } from "node:child_process";

const DEJA = %q;

function run(args, input = "", timeout = 10000) {
  try {
    return execFileSync(DEJA, args, {
      input,
      encoding: "utf8",
      timeout,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    // Memory is optional: a plugin that throws here takes the session with it.
    return "";
  }
}

// Cline wraps what the user typed in a mode tag before it becomes a message.
function userText(message) {
  if (!message || message.role !== "user" || !Array.isArray(message.content)) return "";
  const text = message.content
    .filter((part) => part && part.type === "text" && typeof part.text === "string")
    .map((part) => part.text)
    .join("\n");
  return text.replace(/<\/?user_input[^>]*>/g, "").trim();
}

export default {
  name: "deja",
  manifest: { capabilities: ["rules", "commands", "skills"] },
  setup(api, ctx) {
    const sessionID = (ctx && ctx.session && ctx.session.sessionId) || "";
    // build runs more than once for a single prompt — cline calls it again
    // with the message list it is about to send — and only the last return is
    // used. So the answer is cached per prompt rather than skipped after the
    // first call, which would inject into the copy nobody sends.
    let asked = "";
    let recalled = "";
    api.registerMessageBuilder({
      id: "deja:prompt",
      source: "deja-vu",
      build: (messages) => {
        if (!Array.isArray(messages)) return;
        let at = -1;
        for (let i = messages.length - 1; i >= 0; i--) {
          if (messages[i] && messages[i].role === "user") {
            at = i;
            break;
          }
        }
        if (at < 0) return;
        const prompt = userText(messages[at]);
        if (!prompt) return;
        if (prompt !== asked) {
          asked = prompt;
          recalled = run(["hook-prompt", "--plain"], JSON.stringify({
            prompt,
            session_id: sessionID,
            cwd: process.cwd(),
          }));
        }
        // Silence is the common case: the hook only speaks when the history
        // actually answers the question.
        const recall = recalled;
        if (!recall) return;
        const out = messages.slice();
        out[at] = {
          ...messages[at],
          content: [{ type: "text", text: recall }, ...messages[at].content],
        };
        return out;
      },
    });
    api.registerRule({
      id: "deja:recall",
      source: "deja-vu",
      // A function, not a string: it runs when the session assembles its
      // instructions, so every session gets current history rather than
      // whatever was on disk at install time.
      content: () => run(["hook-context", "--plain"]),
    });
    api.registerCommand({
      name: "deja",
      description: "Search your own past coding sessions",
      handler: (input) => {
        const query = (input || "").trim();
        if (!query) return "Usage: /deja <what you are looking for>";
        // A command the user just typed can wait: the first search may have
        // to build the index, which a hook never gets to do.
        const found = run(["search", query], "", 120000);
        return found || `+"`No past session matches ${query}.`"+`;
      },
    });
  },
};
`, exe)
}
