package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// omp loads extension modules from the active agent directory's extensions/,
// one directory per module. An extension registers handlers on omp's event bus,
// and the one that matters here is `context`: a handler returning `{ messages }`
// replaces what goes to the provider, which is the only seam that reaches the
// model before it answers.
//
// Which event, and that a returned list is honoured at all, came from running a
// probe extension against omp 17.4.1 and watching what fired: `input` never
// does in print mode, `before_agent_start` carries the prompt but not the
// context, and a marker prepended in `context` came back out of the model.

func ompExtensionDir() string {
	return filepath.Join(sources.OmpConfigDir(), "extensions", "deja")
}

// installOmpAuto writes the extension and the MCP server both: `deja install
// --auto` installs the -auto target alone, so an -auto that skipped the server
// would leave the agent with injected memory and no tool to follow it up with.
func installOmpAuto(exe string, uninstall bool) (installResult, error) {
	// The MCP half rides in the result rather than being dropped: the report
	// is what says which files were touched, and mcp.json was written without
	// ever being named (#3254).
	mcp, err := installMCPJSON(filepath.Join(sources.OmpConfigDir(), "mcp.json"), exe, uninstall)
	if err != nil {
		return installResult{}, err
	}
	dir := ompExtensionDir()
	path := filepath.Join(dir, "index.js")
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return wroteAll(installResult{Path: path, Action: "unchanged"}, mcp), nil
		}
		if err := os.RemoveAll(dir); err != nil {
			return installResult{}, err
		}
		// And the directories deja made above it, while each is empty and
		// the record says it is deja's (#3698).
		pruneCreatedDir(filepath.Dir(dir))
		return wroteAll(installResult{Path: path, Action: "removed"}, mcp), nil
	}
	noteCreatedDirs(dir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return installResult{}, err
	}
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	// The launcher for the extension, the binary for the server above: an
	// extension that names the build it was installed from stops working the
	// day that build moves (#3682).
	a, err := writeIfChanged(path, old, []byte(ompExtensionJS(hookExeFor(exe, uninstall))))
	if err != nil {
		return installResult{}, err
	}
	return wroteAll(installResult{Path: path, Action: a}, mcp), nil
}

func ompExtensionJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install omp-auto
import { execFileSync } from "node:child_process";

const DEJA = %q;

function run(args, input, timeout = 10000) {
  try {
    return execFileSync(DEJA, args, {
      input,
      encoding: "utf8",
      timeout,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    // Memory is optional: an extension that throws here takes the session with
    // it, because extensions run in-process with no isolation.
    return "";
  }
}

function userText(message) {
  if (!message || message.role !== "user" || !Array.isArray(message.content)) return "";
  return message.content
    .filter((part) => part && part.type === "text" && typeof part.text === "string")
    .map((part) => part.text)
    .join("\n")
    .trim();
}

export default function extension(pi) {
  // The same prompt reaches the context event more than once in a turn — once per
  // provider request — so the answer is cached rather than asked again.
  let asked = "";
  let recalled = "";
  // No event carries a session id; the session manager does, and every handler
  // reaches it through ctx. Recall skips what it already showed a session, so
  // without the id the same block goes out on every message.
  let session = "";
  let sessionFile = "";
  const remember = (ctx) => {
    try {
      const m = ctx && ctx.sessionManager;
      const id = m && (m.getSessionId ? m.getSessionId() : m.sessionId);
      if (id) session = String(id);
      const file = m && (m.getSessionFile ? m.getSessionFile() : m.sessionFile);
      if (file) sessionFile = String(file);
    } catch {}
  };
  const sessionID = () => session;

  pi.on("session_start", async (_event, ctx) => {
    try {
      remember(ctx);
      const status = run(["warmup-status"], "");
      // omp keeps a footer line, so a first index that is still building is
      // visible instead of looking like memory that does not work.
      ctx.ui.setStatus("deja", status || run(["statusline"], ""));
    } catch {}
  });

  // Registered commands show up in omp's prompt box, which is how someone who
  // never read the docs finds this at all.
  pi.registerCommand("deja", {
    description: "Search your own past coding sessions",
    handler: async (args, ctx) => {
      const query = (args || "").trim();
      if (!query) {
        ctx.ui.notify("Usage: /deja <what you are looking for>", "info");
        return;
      }
      // The user is waiting on this one, so it gets a longer budget than a
      // hook: a first search can rebuild the index. "--" keeps a query that
      // starts with a dash out of deja's own flag parsing.
      const commandArgs = query.startsWith("-") ? ["search", "--", query] : ["search", query];
      const found = run(commandArgs, "", 120000);
      ctx.ui.notify(found || "Nothing in your history matches " + query, "info");
    },
  });

  // Once per session, before the first answer: what this project's recent
  // sessions were about. omp stores what a before_agent_start handler returns
  // as a message of its own, so the digest is in the conversation rather than
  // stapled onto the user's first prompt.
  //
  // Once per session, not once per process: /new, a resume and a fork keep the
  // process and switch the session, and a flag set on the first one left every
  // later session with no digest. The set is keyed by the session manager's id,
  // read fresh on each turn.
  const injected = new Set();
  pi.on("session_switch", async (_event, ctx) => {
    try {
      remember(ctx);
    } catch {}
  });
  pi.on("before_agent_start", async (_event, ctx) => {
    try {
      remember(ctx);
      const key = sessionID();
      if (injected.has(key)) return;
      injected.add(key);
      // The session goes with it: hook-context marks the one starting as
      // live, which keeps it out of its own MCP recall on this first turn
      // (#4394, as #4246 and #4273 did for Hermes and opencode).
      const raw = run(["hook-context"], JSON.stringify({ session_id: sessionID(), cwd: process.cwd() }));
      if (!raw) return;
      let digest = raw;
      let receipt = "";
      try {
        const parsed = JSON.parse(raw);
        digest = (parsed && parsed.hookSpecificOutput && parsed.hookSpecificOutput.additionalContext) || "";
        receipt = (parsed && parsed.systemMessage) || "";
      } catch {}
      if (!digest) return;
      // Without the receipt the recall is invisible and reads as the model
      // guessing; with it the user knows where the answer came from.
      if (receipt) ctx.ui.notify(receipt, "info");
      const stats = run(["statusline"], "");
      if (stats) ctx.ui.setStatus("deja", stats);
      return { message: { customType: "deja-recall", content: digest, display: false } };
    } catch {}
  });

  pi.on("context", async (event, ctx) => {
    remember(ctx);
    const messages = Array.isArray(event && event.messages) ? event.messages : null;
    if (!messages || messages.length === 0) return;
    let at = -1;
    for (let i = messages.length - 1; i >= 0; i--) {
      if (messages[i] && messages[i].role === "user") {
        at = i;
        break;
      }
    }
    if (at < 0) return;
    const prompt = userText(messages[at]);
    if (!prompt) return;
    if (prompt !== asked) {
      asked = prompt;
      recalled = run(["hook-prompt", "--plain"], JSON.stringify({
        prompt,
        session_id: sessionID(),
        cwd: (ctx && ctx.cwd) || process.cwd(),
      }));
    }
    // Silence is the common case: the hook speaks only when this machine's
    // history actually answers the question.
    if (!recalled) return;
    const out = messages.slice();
    out[at] = {
      ...messages[at],
      content: [{ type: "text", text: recalled }, ...messages[at].content],
    };
    return { messages: out };
  });

  // The point of action: a command just failed, and this machine has fixed that
  // same error before. tool_result hands over the content the model is about to
  // read and takes a replacement back, so the repair arrives beside the error in
  // the same turn instead of a turn later.
  const repaired = {};
  pi.on("tool_result", async (event) => {
    try {
      if (!event) return;
      // A file the agent just opened is the step before it changes that file,
      // and omp has no handler that runs earlier whose return the model reads.
      // So the file's own history goes out here — what past sessions decided
      // about it. deja answers once per session per fact, so re-reading the
      // same file stays quiet. An edit or a write without a read before it
      // gets the same line, for the edits after it.
      if (event.toolName === "read" || event.toolName === "edit" || event.toolName === "write") {
        // omp's edit names its file only in the anchor its input opens with,
        // "[path#HASH]".
        const anchor = /^\s*\[([^\]#]+)#/.exec(String((event.input && event.input.input) || ""));
        const path = String((event.input && (event.input.path || event.input.file_path)) || (anchor && anchor[1]) || "");
        if (!path) return;
        const parts = Array.isArray(event.content) ? event.content : [];
        const id = "file:" + String(event.toolCallId || "");
        if (!(id in repaired)) {
          repaired[id] = run(["hook-tool", "--plain"], JSON.stringify({
            tool_name: event.toolName,
            tool_input: { file_path: path },
            session_id: sessionID(),
            cwd: process.cwd(),
          }));
        }
        const note = repaired[id];
        if (!note) return;
        return { content: parts.concat([{ type: "text", text: note }]) };
      }
      if (event.toolName !== "bash") return;
      // omp's bash tool reports a non-zero exit in details.exitCode and leaves
      // isError false — gating on isError alone stays silent on every failed
      // build.
      const failed = event.isError === true ||
        (event.details && typeof event.details.exitCode === "number" && event.details.exitCode !== 0);
      if (!failed) return;
      const parts = Array.isArray(event.content) ? event.content : [];
      const output = parts
        .filter((p) => p && p.type === "text" && typeof p.text === "string")
        .map((p) => p.text)
        .join("\n");
      if (!output.trim()) return;
      const id = String(event.toolCallId || "");
      if (!(id in repaired)) {
        repaired[id] = run(["hook-tool-after", "--plain"], JSON.stringify({
          tool_name: "bash",
          tool_response: output,
          session_id: sessionID(),
          cwd: process.cwd(),
        }));
      }
      const line = repaired[id];
      if (!line) return;
      return { content: parts.concat([{ type: "text", text: line }]) };
    } catch {
      // never turn a failed command into a failed session
    }
  });

  // Compaction throws away the blocks this session was shown, and the list that
  // stops them repeating outlives them. The session file still holds the turns
  // the summary replaced: deja reads them from it, and the next prompt's recall
  // carries what the agent was in the middle of.
  pi.on("session_compact", async (_event, ctx) => {
    try {
      remember(ctx);
      run(["hook-precompact"], JSON.stringify({ session_id: sessionID(), transcript_path: sessionFile, cwd: process.cwd(), harness: "omp" }));
    } catch {}
  });

  // A session is over when omp exits or switches to another one (/new,
  // /resume, a fork). Its live stamp goes with it, so the next session's MCP
  // recall can answer with it now rather than twenty minutes from now (#4210).
  // On a switch the id remembered so far is the session left behind.
  const endSession = () => {
    const id = sessionID();
    if (id) run(["hook-session-end"], JSON.stringify({ session_id: id }), 2000);
  };
  pi.on("session_switch", async (_event, ctx) => {
    try {
      endSession();
      remember(ctx);
    } catch {}
  });
  pi.on("session_shutdown", async (_event) => {
    try {
      endSession();
    } catch {}
  });
}
`, exe)
}
