package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// Command Code keeps every user-scoped surface under `~/.commandcode`, and all
// four of them are shapes deja already writes:
//
//	mcp.json                        the server, `mcpServers`
//	settings.json                   hooks, under a `hooks` key in Claude's shape
//	skills/<name>/SKILL.md          Anthropic-style skills
//	commands/<name>.md              slash commands, name from the basename
//
// The CLI is closed, so none of this was read out of its source. Two
// independent integrations agree on it and both cite the vendor's own docs:
// rulesync's `src/constants/commandcode-paths.ts` and
// `src/types/hooks.ts` (four documented events — PreToolUse, PostToolUse,
// Stop, SessionStart — `command` hooks only, timeout in seconds), and
// akitaonrails/ai-memory's support matrix, which reports the same MCP file and
// says its SessionStart injects. Nothing here is verified on the machine deja
// was written on, and the registry entry says so (#3651).
func commandCodeConfigDir() string {
	return filepath.Join(homeDir(), ".commandcode")
}

func commandCodeMCPPath() string  { return filepath.Join(commandCodeConfigDir(), "mcp.json") }
func commandCodeSettings() string { return filepath.Join(commandCodeConfigDir(), "settings.json") }

func commandCodeSkillPath() string {
	return filepath.Join(commandCodeConfigDir(), "skills", "deja-history", "SKILL.md")
}

// commandCodeHookWiring is what deja has to say at each of the events Command
// Code documents. There is no per-prompt event — the four are PreToolUse,
// PostToolUse, Stop and SessionStart — so the digest rides SessionStart and
// the rest is the tool-time pair.
//
// The matcher is a regex over the tool's display name, and those names are its
// own: SHELL, READ, EDIT, WRITE, SEARCH, GLOB, LIST. A Claude-shaped `Bash`
// matcher never fires here, which is the trap the same adapter warns about.
var commandCodeHookWiring = []struct{ Event, Sub, Matcher string }{
	{"SessionStart", "hook-context", ""},
	{"PreToolUse", "hook-tool", "SHELL|EDIT|WRITE"},
	{"PostToolUse", "hook-tool-after", "SHELL"},
}

func installCommandCode(exe string, uninstall bool) (installResult, error) {
	server, err := installMCPJSON(commandCodeMCPPath(), exe, uninstall)
	if err != nil {
		return installResult{}, err
	}
	skill, err := installSkillFile(commandCodeSkillPath(), uninstall)
	if err != nil {
		return installResult{}, err
	}
	command, err := installCommandFile("commandcode", exe, uninstall)
	if err != nil {
		return installResult{}, err
	}
	return wroteAll(server, skill, command), nil
}

func installCommandCodeAuto(exe string, uninstall bool) (installResult, error) {
	// The server and the rest first: `deja install --auto` installs the -auto
	// target alone, and hooks without a server would leave the tool half-wired.
	base, err := installCommandCode(exe, uninstall)
	if err != nil {
		return installResult{}, err
	}
	hookExe := hookExeFor(exe, uninstall)
	results := []installResult{base}
	for _, h := range commandCodeHookWiring {
		// Seconds here, not milliseconds: Command Code's timeout unit is
		// seconds (default 30, max 600), so the numbers the other
		// settings.json targets pass would be ten minutes each.
		r, err := installSettingsHookCmd(commandCodeSettings(), h.Event, h.Matcher, 30,
			hookRun(hookExe, h.Sub), uninstall)
		if err != nil {
			return installResult{}, err
		}
		results = append(results, r)
	}
	mod, err := installCommandCodeMod(hookExe, uninstall)
	if err != nil {
		return installResult{}, err
	}
	return wroteAll(append(results, mod)...), nil
}

// commandCodeModPath is a personal mod: Command Code loads every file in
// ~/.commandcode/mods at the start of a session, untrusted or not (1.77.0,
// stand).
func commandCodeModPath() string { return filepath.Join(commandCodeConfigDir(), "mods", "deja.ts") }

// installCommandCodeMod writes the mod that carries what the four shell hooks
// cannot: the session's end (onSessionEnd) and the footer line
// (cmd.ui.setStatus, a segment under the input in the TUI).
func installCommandCodeMod(exe string, uninstall bool) (installResult, error) {
	path := commandCodeModPath()
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.Remove(path); err != nil {
			return installResult{}, err
		}
		pruneCreatedDir(filepath.Dir(path))
		return installResult{Path: path, Action: "removed"}, nil
	}
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	noteCreatedDirs(filepath.Dir(path))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(path, old, []byte(commandCodeModTS(exe)))
	return installResult{Path: path, Action: a}, err
}

func commandCodeModTS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install commandcode-auto
import { execFileSync } from "node:child_process"

const DEJA = %q

function run(args: string[], input: string, timeout = 5000): string {
  try {
    return execFileSync(DEJA, args, {
      input,
      encoding: "utf8",
      timeout,
      maxBuffer: 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim()
  } catch {
    // Memory is optional: a mod that throws here would only log a mod_error.
    return ""
  }
}

// The text of a message the person typed, "" for tool results and the
// harness's own turns.
function typed(m: any): string {
  if (!m || m.role !== "user" || (m.meta && (m.meta.isMeta || m.meta.isSummary))) return ""
  if (typeof m.content === "string") return m.content
  if (!Array.isArray(m.content) || m.content.some((b: any) => b && b.type === "tool_result")) return ""
  return m.content.filter((b: any) => b && b.type === "text").map((b: any) => b.text).join("\n")
}

export default function (cmd: any) {
  let session = ""
  // The recall for each question, asked once. transformContext runs on every
  // model call of a turn and never writes back, so the same block goes into
  // the question on each of them and the prompt prefix stays the same.
  const recalls = new Map<string, string>()
  const status = () => {
    try {
      cmd.ui.setStatus(run(["statusline"], "", 2000) || null)
    } catch {}
  }
  cmd.on("run_start", (event: any) => {
    if (event && event.sessionId) session = String(event.sessionId)
  })
  cmd.hooks({
    onSessionStart: (event: any) => {
      if (event && event.sessionId) session = String(event.sessionId)
      status()
    },
    // The four shell hooks have no end of session. Its live stamp goes here,
    // so another session's recall can answer with it now.
    onSessionEnd: () => {
      if (session) run(["hook-session-end"], JSON.stringify({ session_id: session, cwd: cmd.cwd }), 2000)
      try {
        cmd.ui.setStatus(null)
      } catch {}
    },
    onRunEnd: () => status(),
    // The shell hooks have no per-prompt event, and a PreToolUse reads a
    // transcript the turn is not yet written to. The question is here.
    transformContext: ({ messages }: any) => {
      if (!Array.isArray(messages)) return messages
      let at = -1
      for (let i = messages.length - 1; i >= 0; i--) {
        if (typed(messages[i])) {
          at = i
          break
        }
      }
      if (at < 0) return messages
      const m = messages[at]
      const text = typed(m)
      const key = String((m.meta && m.meta.messageId) || at) + "\n" + text
      if (!recalls.has(key)) {
        recalls.set(key, run(["hook-prompt", "--plain"], JSON.stringify({ prompt: text, session_id: session, cwd: cmd.cwd }), 10000))
      }
      const recall = recalls.get(key)
      if (!recall) return messages
      const content = typeof m.content === "string" ? [{ type: "text", text: m.content }] : m.content
      const out = messages.slice()
      out[at] = { ...m, content: [...content, { type: "text", text: recall }] }
      return out
    },
  })
}
`, exe)
}

// commandCodeFirstRoot is what says Command Code is on this machine: its own
// project store, which only exists once it has run.
func commandCodeFirstRoot() string { return sources.CommandCodeRoot() }
