package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// A snapshot that holds nothing but deja's own block is deja's, and the
// uninstall said it was a config the reader already had. The rule was there —
// writeIfChanged drops a backup that mentionsDeja — but the two "removed" fast
// paths return before the defer that applies it, and taking deja's whole block
// out of a file deja wrote is exactly that path (#3340).
func TestUninstallDropsASnapshotThatIsOnlyDejas(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "cordis.patch.yml")
	own := "# deja mcp:start — generated by deja install, safe to delete\n- insert:\n    - id: mcp-deja\n# deja mcp:end\n"
	if err := os.WriteFile(path, []byte(own), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path+".bak", []byte(own), 0o644); err != nil {
		t.Fatal(err)
	}

	removingWiring = true
	defer func() { removingWiring = false }()

	got, err := writeIfChanged(path, []byte(own), nil)
	if err != nil {
		t.Fatal(err)
	}
	if got != "removed" {
		t.Fatalf("state = %q, want removed", got)
	}
	if _, err := os.Stat(path + ".bak"); err == nil {
		t.Error("the snapshot of deja's own block is still there, and uninstall calls it a config the reader already had")
	}
}

// And the other side, unchanged since #2604: a snapshot of the reader's own
// config stays, whatever deja does to the live file.
func TestUninstallKeepsASnapshotThatIsTheReadersOwn(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "cordis.patch.yml")
	if err := os.WriteFile(path, []byte("# deja mcp:start\n- insert: []\n# deja mcp:end\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	theirs := "plugins:\n  - name: something-of-mine\n"
	if err := os.WriteFile(path+".bak", []byte(theirs), 0o644); err != nil {
		t.Fatal(err)
	}
	removingWiring = true
	defer func() { removingWiring = false }()

	if _, err := writeIfChanged(path, nil, nil); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(path + ".bak")
	if err != nil {
		t.Fatalf("the reader's own snapshot was deleted: %v", err)
	}
	if !strings.Contains(string(b), "something-of-mine") {
		t.Errorf("snapshot = %q, want the reader's own config", b)
	}
}
