package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// Cline's hooks cannot carry context: TaskStart and UserPromptSubmit are
// spawned detached with stdout closed, PreToolUse keeps only cancel and
// overrideInput, PreCompact is mapped to no event at all, and --hooks-dir is
// read by nothing. Verified against CLI 3.0.46.
//
// Plugins are the channel that works. A registered rule takes a function for
// its content, resolved when the session builds its instructions — which is
// session-start recall by another name — and a registered command puts /deja
// in the same session.
func installClineAuto(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(sources.ClinePluginsDir(), "deja")
	path := filepath.Join(dir, "index.js")
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.RemoveAll(dir); err != nil {
			return installResult{}, err
		}
		return installResult{Path: path, Action: "removed"}, nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return installResult{}, err
	}
	old, _ := os.ReadFile(path)
	a, err := writeIfChanged(path, old, []byte(clinePluginJS(exe)))
	if err != nil {
		return installResult{}, err
	}
	// Cline discovers skills bundled in the plugin package, which is the only
	// channel it has for one: it has no user-level instructions file, so until
	// now it got the recall rule and no manual at all. Written after index.js
	// so a failure here leaves a working plugin rather than a directory the
	// uninstall path would not recognise.
	skill := filepath.Join(dir, "skills", "deja-history")
	if err := os.MkdirAll(skill, 0o755); err != nil {
		return installResult{}, err
	}
	oldSkill, _ := os.ReadFile(filepath.Join(skill, "SKILL.md"))
	if _, err := writeIfChanged(filepath.Join(skill, "SKILL.md"), oldSkill, []byte(skillFile(skillBody))); err != nil {
		return installResult{}, err
	}
	return installResult{Path: path, Action: a}, nil
}

func clinePluginJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install cline-auto
import { execFileSync } from "node:child_process";

const DEJA = %q;

function run(args, input = "", timeout = 10000) {
  try {
    return execFileSync(DEJA, args, {
      input,
      encoding: "utf8",
      timeout,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    // Memory is optional: a plugin that throws here takes the session with it.
    return "";
  }
}

export default {
  name: "deja",
  manifest: { capabilities: ["rules", "commands", "skills"] },
  setup(api) {
    api.registerRule({
      id: "deja:recall",
      source: "deja-vu",
      // A function, not a string: it runs when the session assembles its
      // instructions, so every session gets current history rather than
      // whatever was on disk at install time.
      content: () => run(["hook-context", "--plain"]),
    });
    api.registerCommand({
      name: "deja",
      description: "Search your own past coding sessions",
      handler: (input) => {
        const query = (input || "").trim();
        if (!query) return "Usage: /deja <what you are looking for>";
        // A command the user just typed can wait: the first search may have
        // to build the index, which a hook never gets to do.
        const found = run(["search", query], "", 120000);
        return found || `+"`No past session matches ${query}.`"+`;
      },
    });
  },
};
`, exe)
}
