package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// Amp keeps everything in one settings file: MCP servers under the dotted key
// amp.mcpServers, which `amp mcp add` writes and `amp mcp doctor` reads back.
// The key is a literal with a dot in it, not a nested object, so it cannot go
// through the nested-path writer.
func installAmpMCP(exe string, uninstall bool) (installResult, error) {
	return installAmpMCPAt(sources.AmpSettingsFile(), exe, uninstall)
}

func installAmpMCPAt(path, exe string, uninstall bool) (installResult, error) {
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	var root map[string]any
	if len(bytes.TrimSpace(old)) == 0 {
		if uninstall {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		root = map[string]any{}
	} else if err := json.Unmarshal([]byte(jsoncToJSON(string(old))), &root); err != nil {
		return installResult{}, configParseError(path, err)
	}
	servers, _ := root[ampServersKey].(map[string]any)
	if servers == nil {
		if uninstall {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		servers = map[string]any{}
		root[ampServersKey] = servers
	}
	if uninstall {
		delete(servers, "deja")
		if len(servers) == 0 {
			delete(root, ampServersKey)
		}
	} else {
		servers["deja"] = ampServerEntry(exe)
	}
	next, err := marshalConfigLike(old, root)
	if err != nil {
		return installResult{}, err
	}
	next = append(next, '\n')
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

// The key is one literal string with a dot in it — the way Amp's own
// `amp mcp add` writes it — not a nested "amp" object.
const ampServersKey = "amp.mcpServers"

func ampServerEntry(exe string) map[string]any {
	command, args := mcpCommandArgs(exe)
	return map[string]any{"command": command, "args": args}
}

// installAmpAuto writes the plugin and the MCP server both: the plugin puts
// memory in front of the model unasked, and the server is what the model calls
// when the block makes it curious.
func installAmpAuto(exe string, uninstall bool) (installResult, error) {
	mcp, err := installAmpMCP(exe, uninstall)
	if err != nil {
		return installResult{}, err
	}
	plugin, err := installAmpPlugin(exe, uninstall)
	if err != nil {
		return installResult{}, err
	}
	return wroteAll(mcp, plugin), nil
}

// ampPluginPath is Amp's system-plugin directory: ~/.config/amp/plugins/*.ts,
// auto-discovered, so installing is one file and no settings edit.
func ampPluginPath() string {
	return filepath.Join(sources.AmpConfigDir(), "plugins", "deja.ts")
}

func installAmpPlugin(exe string, uninstall bool) (installResult, error) {
	path := ampPluginPath()
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.Remove(path); err != nil {
			return installResult{}, err
		}
		return installResult{Path: path, Action: "removed"}, nil
	}
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(path, old, []byte(ampPluginTS(exe)))
	return installResult{Path: path, Action: a}, err
}

func ampPluginTS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install amp-auto
import { execFileSync } from "node:child_process"

export const description = "Recall from this machine's past coding sessions, across every AI tool used here"

const DEJA = %q

function run(args: string[], input: string, timeout = 10000): string {
  try {
    return execFileSync(DEJA, args, {
      input,
      encoding: "utf8",
      timeout,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim()
  } catch {
    // Memory is optional: a plugin that throws here would take the turn with it.
    return ""
  }
}

export default function (amp: any) {
  // The thread that has had its digest. Amp keeps one process across threads,
  // and a flag set once per process left every thread after the first with no
  // memory (#3263).
  let injected = ""
  // Amp's events carry the thread, and the thread id is what recall dedupes on:
  // without it the same block goes out on every message of the session.
  let thread = ""
  const threadID = (event: any) => {
    const id = event && event.thread && event.thread.id
    if (id) thread = String(id)
    return thread
  }

  // Fire-and-forget: the only thing session.start can do is talk to the user,
  // and while a first index builds that is worth saying once.
  amp.on("session.start", async (event: any, ctx: any) => {
    try {
      threadID(event)
      const status = run(["warmup-status"], "")
      if (status) await ctx.ui.notify(status)
    } catch {}
  })

  // agent.start is the injection point. It carries the prompt and its return
  // value is appended to the user message, which is both halves of what Claude
  // Code splits across SessionStart and UserPromptSubmit.
  amp.on("agent.start", async (event: any, ctx: any) => {
    try {
      const id = threadID(event)
      if (injected !== (id || "*")) {
        injected = id || "*"
        // The thread goes with it, so deja's own once-per-session mark holds
        // across a restart of the process the way it does for Claude Code.
        const raw = run(["hook-context"], JSON.stringify({
          session_id: id,
          cwd: process.cwd(),
          deja_once: true,
        }))
        let digest = raw
        let receipt = ""
        try {
          const parsed = JSON.parse(raw)
          digest = (parsed && parsed.hookSpecificOutput && parsed.hookSpecificOutput.additionalContext) || ""
          receipt = (parsed && parsed.systemMessage) || ""
        } catch {}
        if (digest) {
          // The receipt is what tells the user memory arrived; without it the
          // recall is invisible and reads as the model guessing.
          if (receipt) {
            try {
              await ctx.ui.notify(receipt)
            } catch {}
          }
          return { message: { content: digest, display: false } }
        }
      }
      const raw = run(["hook-prompt", "--plain"], JSON.stringify({
        prompt: event.message || "",
        session_id: id,
        cwd: process.cwd(),
      }))
      // Silence is the common case: the hook speaks only when this machine's
      // history answers what was just asked.
      if (!raw) return
      return { message: { content: raw, display: false } }
    } catch {}
  })

  // The point of action. A command has just failed and this machine has fixed
  // that same error before; tool.result hands over the output the model is
  // about to read and takes a replacement back, so the repair arrives beside
  // the error instead of a turn later. tool.call cannot carry it: its result is
  // allow, reject, modify-input or synthesize — none of them add context.
  const repaired: Record<string, string> = {}
  amp.on("tool.result", async (event: any) => {
    try {
      if (!event || event.status !== "error") return
      if (event.tool !== "shell_command" && event.tool !== "Bash") return
      const output = typeof event.output === "string" ? event.output : JSON.stringify(event.output ?? "")
      const text = (output || "") + (event.error ? "\n" + event.error : "")
      if (!text.trim()) return
      const id = String(event.toolUseID || "")
      if (!(id in repaired)) {
        repaired[id] = run(["hook-tool-after", "--plain"], JSON.stringify({
          tool_name: "bash",
          tool_response: text,
          session_id: threadID(event),
          cwd: process.cwd(),
        }))
      }
      const line = repaired[id]
      if (!line) return
      return { status: "error", error: event.error, output: text + "\n" + line }
    } catch {
      // never turn a failed command into a failed thread
    }
  })

  // Amp surfaces registered commands in its command palette, which is how
  // someone who never read the docs finds this at all.
  amp.registerCommand(
    "deja",
    { title: "search past sessions", category: "deja", description: "Search your own past coding sessions" },
    async (ctx: any) => {
      const query = String((await ctx.ui.input({
        title: "deja",
        helpText: "What are you looking for in your own past sessions?",
      })) || "").trim()
      if (!query) return
      // The user is waiting on this one, so it gets a longer budget than a
      // hook: a first search can rebuild the index. "--" keeps a query that
      // starts with a dash out of deja's own flag parsing.
      const args = query.startsWith("-") ? ["search", "--", query] : ["search", query]
      const found = run(args, "", 120000)
      await ctx.ui.notify(found || "Nothing in your history matches " + query)
    },
  )
}
`, exe)
}
