package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// Hermes takes plugins as a directory under ~/.hermes/plugins with a
// plugin.yaml manifest and an __init__.py exporting register(ctx). Of its
// hooks only pre_llm_call can inject: whatever it returns under "context" is
// appended to the user message, which is also where Hermes wants it — the
// system prompt stays byte-identical so provider caching survives.
func installHermesPlugin(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(sources.HermesHome(), "plugins", "deja")
	if uninstall {
		if _, err := os.Stat(dir); err != nil {
			return installResult{Path: dir, Action: "unchanged"}, nil
		}
		if err := os.RemoveAll(dir); err != nil {
			return installResult{}, err
		}
		if err := setHermesPluginEnabled(false); err != nil {
			return installResult{}, err
		}
		return installResult{Path: dir, Action: "removed"}, nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return installResult{}, err
	}
	manifestPath := filepath.Join(dir, "plugin.yaml")
	oldManifest, _ := os.ReadFile(manifestPath)
	if _, err := writeIfChanged(manifestPath, oldManifest, []byte(hermesPluginManifest)); err != nil {
		return installResult{}, err
	}
	codePath := filepath.Join(dir, "__init__.py")
	oldCode, _ := os.ReadFile(codePath)
	a, err := writeIfChanged(codePath, oldCode, []byte(hermesPluginPy(exe)))
	if err != nil {
		return installResult{}, err
	}
	// A discovered plugin is listed as "not enabled" and never loaded until
	// its name is in plugins.enabled, so the installer puts it there rather
	// than leaving the user a second step nothing tells them about.
	if err := setHermesPluginEnabled(true); err != nil {
		return installResult{}, err
	}
	return installResult{Path: dir, Action: a}, nil
}

const hermesPluginManifest = `name: deja
version: 0.1.0
description: Recall your own past coding sessions before answering
provides_hooks:
  - pre_llm_call
provides_commands:
  - deja
`

func hermesPluginPy(exe string) string {
	return fmt.Sprintf(`"""Generated by deja install — safe to delete; regenerate with: deja install hermes-auto."""

import json
import subprocess

DEJA = %s


def _deja(args, payload="", timeout=10):
    """Never let memory break a turn: a failure here returns nothing."""
    try:
        done = subprocess.run(
            [DEJA, *args],
            input=payload,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return done.stdout.strip()
    except Exception:
        return ""


def recall(session_id=None, user_message=None, is_first_turn=False, **kwargs):
    # First turn gets the session digest, ranked by the project; every turn
    # after gets the relevance pass over what was just asked. Silence is the
    # normal answer — a hook that talks every turn is wallpaper.
    if is_first_turn:
        digest = _deja(["hook-context", "--plain"])
        if digest:
            return {"context": digest}
    if not user_message:
        return None
    payload = json.dumps({"prompt": user_message, "session_id": session_id or ""})
    hit = _deja(["hook-prompt", "--plain"], payload)
    return {"context": hit} if hit else None


def search(raw_args):
    """/deja <query> — search past sessions without waiting for a recall."""
    query = (raw_args or "").strip()
    if not query:
        return "Usage: /deja <what you are looking for>"
    # A hook must not stall a turn, but a command the user just typed can
    # wait: a first search may rebuild the index, which took 18s here.
    found = _deja(["search", query], timeout=120)
    return found or f"Nothing in your history matches {query!r}."


def register(ctx):
    ctx.register_hook("pre_llm_call", recall)
    # Hermes surfaces registered commands in every session and gateway, which
    # is the cheapest way to be found by someone who has not read the docs.
    ctx.register_command(
        "deja",
        handler=search,
        description="Search your own past coding sessions",
    )
`, pyQuote(exe))
}

// pyQuote renders a Python string literal. A Windows path or one with a quote
// in it would otherwise produce a plugin that fails to import.
func pyQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}

// yamlQuote renders a YAML double-quoted scalar. An unquoted exe path breaks the
// file the moment it holds a YAML metacharacter — a ": " reads as a nested key,
// a " #" starts a comment, a Windows "C:\..." is at least fragile — and the
// harness then cannot parse its own config. Double-quoting escapes only \ and ",
// which is all a double-quoted scalar needs.
func yamlQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}

// installHermesMCP edits config.yaml by hand rather than through a YAML
// round-trip: the file ships with section comments a re-serialise would drop,
// and `hermes mcp add` prompts before saving, which an installer cannot answer.
func installHermesMCP(exe string, uninstall bool) (installResult, error) {
	path := filepath.Join(sources.HermesHome(), "config.yaml")
	old, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return installResult{}, err
	}
	next := removeHermesMCPBlock(string(old))
	if !uninstall {
		entry := "  deja:\n    command: " + yamlQuote(exe) + "\n    args:\n      - mcp\n    enabled: true\n"
		if i := strings.Index(next, "\nmcp_servers:\n"); i >= 0 {
			at := i + len("\nmcp_servers:\n")
			next = next[:at] + entry + next[at:]
		} else {
			if next != "" && !strings.HasSuffix(next, "\n") {
				next += "\n"
			}
			next += "\nmcp_servers:\n" + entry
		}
	}
	a, werr := writeIfChanged(path, old, []byte(next))
	return installResult{Path: path, Action: a}, werr
}

// removeHermesMCPBlock drops our entry and nothing else: the block ends at the
// next line that is not more indented, so a neighbouring server survives.
func removeHermesMCPBlock(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	skipping := false
	for _, l := range lines {
		if skipping {
			if strings.HasPrefix(l, "    ") || strings.TrimSpace(l) == "" && len(out) > 0 && strings.HasPrefix(out[len(out)-1], "    ") {
				continue
			}
			skipping = false
		}
		if strings.TrimSpace(l) == "deja:" && strings.HasPrefix(l, "  ") && !strings.HasPrefix(l, "   ") {
			skipping = true
			continue
		}
		out = append(out, l)
	}
	return strings.Join(out, "\n")
}

// setHermesPluginEnabled adds or removes deja from plugins.enabled, touching
// only that one list entry so the rest of the file — comments included —
// stays byte-identical.
func setHermesPluginEnabled(on bool) error {
	path := filepath.Join(sources.HermesHome(), "config.yaml")
	old, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) && !on {
			return nil
		}
		if !os.IsNotExist(err) {
			return err
		}
	}
	s := string(old)
	listed := strings.Contains(s, "\n    - deja\n")
	switch {
	case on && listed, !on && !listed:
		return nil
	case !on:
		s = strings.Replace(s, "\n    - deja", "", 1)
	case strings.Contains(s, "\nplugins:\n  enabled:\n"):
		s = strings.Replace(s, "\nplugins:\n  enabled:\n", "\nplugins:\n  enabled:\n    - deja\n", 1)
	case strings.Contains(s, "\nplugins:\n  enabled: []\n"):
		s = strings.Replace(s, "\nplugins:\n  enabled: []\n", "\nplugins:\n  enabled:\n    - deja\n", 1)
	default:
		if s != "" && !strings.HasSuffix(s, "\n") {
			s += "\n"
		}
		s += "\nplugins:\n  enabled:\n    - deja\n"
	}
	_, err = writeIfChanged(path, old, []byte(s))
	return err
}
