package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// Codex (v0.114+) ships lifecycle hooks with the same JSON contract as
// Claude Code, so the existing `deja hook-context` output works unchanged.
// We merge one SessionStart entry into ~/.codex/hooks.json and leave
// everything else in the file alone.
func installCodexHooks(exe string, uninstall bool) (installResult, error) {
	h, _ := os.UserHomeDir()
	path := filepath.Join(h, ".codex", "hooks.json")
	old, _ := os.ReadFile(path)
	var root map[string]any
	if len(bytes.TrimSpace(old)) == 0 {
		root = map[string]any{}
	} else if err := json.Unmarshal(old, &root); err != nil {
		return installResult{}, err
	}
	cmd := exe + " hook-context"
	hooks, _ := root["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
		root["hooks"] = hooks
	}
	entries, _ := hooks["SessionStart"].([]any)
	var kept []any
	found := false
	for _, entryAny := range entries {
		entry, _ := entryAny.(map[string]any)
		if entry != nil && entryHasCommand(entry, cmd) {
			found = true
			if uninstall {
				continue
			}
		}
		kept = append(kept, entryAny)
	}
	if !uninstall && !found {
		kept = append(kept, map[string]any{
			"matcher": "startup|resume",
			"hooks":   []any{map[string]any{"type": "command", "command": cmd, "timeout": 10}},
		})
	}
	if len(kept) == 0 {
		delete(hooks, "SessionStart")
	} else {
		hooks["SessionStart"] = kept
	}
	if len(hooks) == 0 {
		delete(root, "hooks")
	}
	next, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return installResult{}, err
	}
	next = append(next, '\n')
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

func entryHasCommand(entry map[string]any, cmd string) bool {
	hs, _ := entry["hooks"].([]any)
	for _, hAny := range hs {
		h, _ := hAny.(map[string]any)
		if h != nil && h["type"] == "command" && h["command"] == cmd {
			return true
		}
	}
	return false
}

// opencode has no session-start hook; its plugin API can push text onto the
// system prompt per request. The generated plugin shells out to
// `deja hook-context --plain` once per session and caches the result.
func installOpencodePlugin(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(opencodeConfigHome(), "opencode", "plugins")
	path := filepath.Join(dir, "deja.js")
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.Remove(path); err != nil {
			return installResult{}, err
		}
		return installResult{Path: path, Action: "removed"}, nil
	}
	old, _ := os.ReadFile(path)
	next := []byte(opencodePluginJS(exe))
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

func opencodePluginJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install opencode-auto
export const DejaRecall = async ({ $ }) => {
  const cache = new Map()
  return {
    "experimental.chat.system.transform": async (input, output) => {
      try {
        const key = input.sessionID || "default"
        if (!cache.has(key)) {
          const blob = await $%s%q %s%s.text()
          cache.set(key, blob.trim())
        }
        const ctx = cache.get(key)
        if (ctx) output.system.push(ctx)
      } catch {
        // memory is optional: never break the session over it
      }
    },
  }
}
`, "`", exe, "hook-context --plain", "`")
}
