package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// Hermes takes plugins as a directory under ~/.hermes/plugins with a
// plugin.yaml manifest and an __init__.py exporting register(ctx). Of its
// hooks only pre_llm_call can inject: whatever it returns under "context" is
// appended to the user message, which is also where Hermes wants it — the
// system prompt stays byte-identical so provider caching survives.
func installHermesPlugin(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(sources.HermesHome(), "plugins", "deja")
	if uninstall {
		if _, err := os.Stat(dir); err != nil {
			return installResult{Path: dir, Action: "unchanged"}, nil
		}
		if err := os.RemoveAll(dir); err != nil {
			return installResult{}, err
		}
		if err := setHermesPluginEnabled(false); err != nil {
			return installResult{}, err
		}
		return installResult{Path: dir, Action: "removed"}, nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return installResult{}, err
	}
	manifestPath := filepath.Join(dir, "plugin.yaml")
	oldManifest, err := readConfig(manifestPath)
	if err != nil {
		return installResult{}, err
	}
	if _, err := writeIfChanged(manifestPath, oldManifest, []byte(hermesPluginManifest)); err != nil {
		return installResult{}, err
	}
	codePath := filepath.Join(dir, "__init__.py")
	oldCode, err := readConfig(codePath)
	if err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(codePath, oldCode, []byte(hermesPluginPy(exe)))
	if err != nil {
		return installResult{}, err
	}
	// A discovered plugin is listed as "not enabled" and never loaded until
	// its name is in plugins.enabled, so the installer puts it there rather
	// than leaving the user a second step nothing tells them about.
	if err := setHermesPluginEnabled(true); err != nil {
		return installResult{}, err
	}
	return installResult{Path: dir, Action: a}, nil
}

const hermesPluginManifest = `name: deja
version: 0.1.0
description: Recall your own past coding sessions before answering
provides_hooks:
  - pre_llm_call
provides_commands:
  - deja
`

func hermesPluginPy(exe string) string {
	return fmt.Sprintf(`"""Generated by deja install — safe to delete; regenerate with: deja install hermes-auto."""

import json
import subprocess

DEJA = %s


def _deja(args, payload="", timeout=10):
    """Never let memory break a turn: a failure here returns nothing."""
    try:
        done = subprocess.run(
            [DEJA, *args],
            input=payload,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return done.stdout.strip()
    except Exception:
        return ""


def _provider_active():
    """True when deja is the configured memory provider (memory.provider in
    config.yaml): the provider then injects the same recall before each turn,
    and a hook that repeats it would hand the model everything twice."""
    try:
        from hermes_cli.config import cfg_get, load_config
        return cfg_get(load_config(), "memory", "provider") == "deja-memory"
    except Exception:
        return False


def recall(session_id=None, user_message=None, is_first_turn=False, **kwargs):
    # First turn gets the session digest, ranked by the project; every turn
    # after gets the relevance pass over what was just asked. Silence is the
    # normal answer — a hook that talks every turn is wallpaper.
    if _provider_active():
        return None
    if is_first_turn:
        digest = _deja(["hook-context", "--plain"])
        if digest:
            return {"context": digest}
    if not user_message:
        return None
    payload = json.dumps({"prompt": user_message, "session_id": session_id or ""})
    hit = _deja(["hook-prompt", "--plain"], payload)
    return {"context": hit} if hit else None


def search(raw_args):
    """/deja <query> — search past sessions without waiting for a recall."""
    query = (raw_args or "").strip()
    if not query:
        return "Usage: /deja <what you are looking for>"
    # A hook must not stall a turn, but a command the user just typed can
    # wait: a first search may rebuild the index, which took 18s here.
    #
    # "--" when the query names one of deja's own flags: searching for
    # "--json" or "--all-matches" otherwise dies in flag parsing and comes back
    # as an empty history.
    args = ["search", "--", query] if query.startswith("-") else ["search", query]
    found = _deja(args, timeout=120)
    return found or f"Nothing in your history matches {query!r}."


def register(ctx):
    ctx.register_hook("pre_llm_call", recall)
    # Hermes surfaces registered commands in every session and gateway, which
    # is the cheapest way to be found by someone who has not read the docs.
    ctx.register_command(
        "deja",
        handler=search,
        description="Search your own past coding sessions",
    )
`, pyQuote(exe))
}

// pyQuote renders a Python string literal. A Windows path or one with a quote
// in it would otherwise produce a plugin that fails to import.
func pyQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}

// yamlQuote renders a YAML double-quoted scalar. An unquoted exe path breaks the
// file the moment it holds a YAML metacharacter — a ": " reads as a nested key,
// a " #" starts a comment, a Windows "C:\..." is at least fragile — and the
// harness then cannot parse its own config. Double-quoting escapes only \ and ",
// which is all a double-quoted scalar needs.
func yamlQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}

// installHermesMCP edits config.yaml by hand rather than through a YAML
// round-trip: the file ships with section comments a re-serialise would drop,
// and `hermes mcp add` prompts before saving, which an installer cannot answer.
func installHermesMCP(exe string, uninstall bool) (installResult, error) {
	path := filepath.Join(sources.HermesHome(), "config.yaml")
	old, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return installResult{}, err
	}
	next := removeHermesMCPBlock(lfText(old))
	if !uninstall {
		pad, ok := hermesBlockIndent(next)
		if !ok {
			pad = "  "
		}
		entry := pad + "deja:\n" + pad + pad + "command: " + yamlQuote(exe) + "\n" +
			pad + pad + "args:\n" + pad + pad + pad + "- mcp\n" + pad + pad + "enabled: true\n"
		if i := strings.Index(next, "\nmcp_servers:\n"); i >= 0 {
			at := i + len("\nmcp_servers:\n")
			next = next[:at] + entry + next[at:]
		} else {
			if next != "" && !strings.HasSuffix(next, "\n") {
				next += "\n"
			}
			next += "\nmcp_servers:\n" + entry
			noteBlockAdded(path, "mcp_servers")
		}
	} else if blockWasAdded(path, "mcp_servers") {
		// The container goes with the entry when deja is what put it there —
		// a config the reader owned came back carrying an `mcp_servers:` they
		// never wrote (#2606, the shape #2604 fixed for the JSON writers). One
		// they wrote stays, with or without entries under it.
		if trimmed := dropEmptyYAMLKey(next, "mcp_servers:"); trimmed != next {
			next = trimmed
			forgetBlockAdded(path, "mcp_servers")
		}
	}
	// The file's own final newline, the way both goose writers keep it: this
	// was the only writer that did not, so a config whose deja block ended it
	// came back without one (#2606, #2730).
	a, werr := writeIfChanged(path, old, []byte(keepTrailingNewline(lfText(old), next)))
	return installResult{Path: path, Action: a}, werr
}

// removeHermesMCPBlock drops our entry and nothing else: the block ends at the
// next line that is not more indented, so a neighbouring server survives.
func removeHermesMCPBlock(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	// Inside `mcp_servers:` and at its own child indent — nothing else. Reading
	// `deja:` at any depth emptied a server of somebody else's whose env holds
	// a key by that name, which is a config deja broke while claiming to
	// uninstall itself (#2730).
	inBlock := false
	child := -1
	for i := 0; i < len(lines); i++ {
		line := lines[i]
		if strings.TrimSpace(line) == "mcp_servers:" && yamlIndentWidth(line) == 0 {
			inBlock, child = true, -1
			out = append(out, line)
			continue
		}
		if inBlock && strings.TrimSpace(line) != "" && yamlIndentWidth(line) == 0 {
			inBlock, child = false, -1
		}
		if inBlock && child < 0 && strings.TrimSpace(line) != "" {
			child = yamlIndentWidth(line)
		}
		if !inBlock || strings.TrimSpace(line) != "deja:" || yamlIndentWidth(line) != child {
			out = append(out, line)
			continue
		}
		pad := yamlIndentWidth(line)
		i++
		for i < len(lines) {
			if strings.TrimSpace(lines[i]) == "" {
				// A blank line is inside the block only if the block goes on
				// after it. The one that separates deja's block from what
				// follows belongs to the file, and eating it made a second
				// install differ from the first.
				j := i
				for j < len(lines) && strings.TrimSpace(lines[j]) == "" {
					j++
				}
				if j < len(lines) && yamlIndentWidth(lines[j]) > pad {
					i = j
					continue
				}
				break
			}
			if yamlIndentWidth(lines[i]) <= pad {
				break
			}
			i++
		}
		i--
	}
	return strings.Join(out, "\n")
}

// hermesBlockIndent is the indent the servers under `mcp_servers:` are written
// at, and whether there is a block to read one from. deja wrote its own entry
// at two whatever the file used, so on a config indented at three or four the
// entry landed shallower than its siblings — and the uninstall that reads
// "indented further than deja's key" then took those siblings with it (#2730).
func hermesBlockIndent(s string) (string, bool) {
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if strings.TrimSpace(line) != "mcp_servers:" || yamlIndentWidth(line) != 0 {
			continue
		}
		for _, next := range lines[i+1:] {
			if strings.TrimSpace(next) == "" {
				continue
			}
			if yamlIndentWidth(next) == 0 {
				return "", false
			}
			return next[:len(next)-len(strings.TrimLeft(next, " \t"))], true
		}
		return "", false
	}
	return "", false
}

// setHermesPluginEnabled adds or removes deja from plugins.enabled, touching
// only that one list entry so the rest of the file — comments included —
// stays byte-identical.
func setHermesPluginEnabled(on bool) error {
	path := filepath.Join(sources.HermesHome(), "config.yaml")
	old, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) && !on {
			return nil
		}
		if !os.IsNotExist(err) {
			return err
		}
	}
	s := lfText(old)
	listed := strings.Contains(s, "\n    - deja\n")
	switch {
	case on && listed, !on && !listed:
		return nil
	case !on:
		s = strings.Replace(s, "\n    - deja", "", 1)
		// And the block itself, when deja is what put it there. Taking back
		// only the entry left `plugins:\n  enabled:` behind on every machine
		// that had no plugins block — an empty key that parses as null — while
		// the MCP writer one function above already drops what it created
		// (#2604, #2672). A block the reader wrote stays, empty or not.
		if blockWasAdded(path, "plugins") {
			s = strings.Replace(s, "\nplugins:\n  enabled:\n", "\n", 1)
			s = strings.TrimSuffix(s, "\n\n") + "\n"
			forgetBlockAdded(path, "plugins")
		}
	case strings.Contains(s, "\nplugins:\n  enabled:\n"):
		s = strings.Replace(s, "\nplugins:\n  enabled:\n", "\nplugins:\n  enabled:\n    - deja\n", 1)
	case strings.Contains(s, "\nplugins:\n  enabled: []\n"):
		s = strings.Replace(s, "\nplugins:\n  enabled: []\n", "\nplugins:\n  enabled:\n    - deja\n", 1)
	default:
		if s != "" && !strings.HasSuffix(s, "\n") {
			s += "\n"
		}
		s += "\nplugins:\n  enabled:\n    - deja\n"
		noteBlockAdded(path, "plugins")
	}
	_, err = writeIfChanged(path, old, []byte(s))
	return err
}
