package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// Codex (v0.114+) ships lifecycle hooks with the same JSON contract as
// Claude Code, so the existing `deja hook-context` output works unchanged.
// We merge one SessionStart entry into ~/.codex/hooks.json and leave
// everything else in the file alone.
func installCodexHooks(exe string, uninstall bool) (installResult, error) {
	h, _ := os.UserHomeDir()
	path := filepath.Join(h, ".codex", "hooks.json")
	old, _ := os.ReadFile(path)
	var root map[string]any
	if len(bytes.TrimSpace(old)) == 0 {
		root = map[string]any{}
	} else if err := json.Unmarshal(old, &root); err != nil {
		return installResult{}, err
	}
	cmd := exe + " hook-context"
	hooks, _ := root["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
		root["hooks"] = hooks
	}
	entries, _ := hooks["SessionStart"].([]any)
	var kept []any
	found := false
	for _, entryAny := range entries {
		entry, _ := entryAny.(map[string]any)
		if entry != nil && entryHasCommand(entry, cmd) {
			found = true
			if uninstall {
				continue
			}
		}
		kept = append(kept, entryAny)
	}
	if !uninstall && !found {
		kept = append(kept, map[string]any{
			"matcher": "startup|resume",
			"hooks":   []any{map[string]any{"type": "command", "command": cmd, "timeout": 10}},
		})
	}
	if len(kept) == 0 {
		delete(hooks, "SessionStart")
	} else {
		hooks["SessionStart"] = kept
	}
	if len(hooks) == 0 {
		delete(root, "hooks")
	}
	next, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return installResult{}, err
	}
	next = append(next, '\n')
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

func entryHasCommand(entry map[string]any, cmd string) bool {
	hs, _ := entry["hooks"].([]any)
	for _, hAny := range hs {
		h, _ := hAny.(map[string]any)
		if h != nil && h["type"] == "command" && h["command"] == cmd {
			return true
		}
	}
	return false
}

// opencode has no session-start hook; its plugin API can push text onto the
// system prompt per request. The generated plugin shells out to
// `deja hook-context --plain` once per session and caches the result.
func installOpencodePlugin(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(opencodeConfigHome(), "opencode", "plugins")
	path := filepath.Join(dir, "deja.js")
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.Remove(path); err != nil {
			return installResult{}, err
		}
		return installResult{Path: path, Action: "removed"}, nil
	}
	old, _ := os.ReadFile(path)
	next := []byte(opencodePluginJS(exe))
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

func opencodePluginJS(exe string) string {
	// opencode's hook output goes into the model's context, so a progress
	// note cannot ride along with it — it would be prompt noise. The TUI
	// toast is the channel meant for the human, so the build announces itself
	// there instead, once per session so it does not nag on every turn.
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install opencode-auto
export const DejaRecall = async ({ $, client }) => {
  const cache = new Map()
  const told = new Set()
  return {
    "experimental.chat.system.transform": async (input, output) => {
      try {
        const key = input.sessionID || "default"
        if (!cache.has(key)) {
          const blob = await $%s%q %s%s.text()
          cache.set(key, blob.trim())
        }
        const ctx = cache.get(key)
        if (ctx) {
          output.system.push(ctx)
          return
        }
        // Nothing to recall: either there is no history yet, or the first
        // index is still being built. Only the second is worth saying.
        if (told.has(key)) return
        const status = (await $%s%q %s%s.text()).trim()
        if (!status) return
        told.add(key)
        cache.delete(key)
        await client.tui.showToast({ body: { message: status, variant: "info", duration: 6000 } })
      } catch {
        // memory is optional: never break the session over it
      }
    },
  }
}
`, "`", exe, "hook-context --plain", "`", "`", exe, "warmup-status", "`")
}

// Gemini CLI and Qwen Code both run a command before the agent loop, which is
// the same injection point Claude Code's SessionStart gives us — so
// auto-recall works there too, not just MCP on demand.
//
// They are not the same shape, and both differences were found by running
// them rather than by reading their bundles:
//
//   - Gemini calls the event BeforeAgent (it has no SessionStart) and reads
//     `timeout` in MILLISECONDS. A Claude-style `"timeout": 10` is ten
//     milliseconds there, and the hook is killed before it can answer.
//   - Qwen forked from an older Gemini and kept SessionStart with a matcher,
//     with `timeout` in seconds.
func installGeminiAuto(exe string, uninstall bool) (installResult, error) {
	return installSettingsHook(
		filepath.Join(sources.GeminiHome(), "settings.json"),
		"BeforeAgent", "", 10000, exe, uninstall)
}

func installQwenAuto(exe string, uninstall bool) (installResult, error) {
	return installSettingsHook(
		filepath.Join(sources.QwenConfigDir(), "settings.json"),
		"SessionStart", "startup|resume", 10, exe, uninstall)
}

// installSettingsHook merges one hook entry into a settings.json that the
// host also uses for everything else, leaving the rest of the file alone.
func installSettingsHook(path, event, matcher string, timeout int, exe string, uninstall bool) (installResult, error) {
	old, _ := os.ReadFile(path)
	var root map[string]any
	if len(bytes.TrimSpace(old)) == 0 {
		root = map[string]any{}
	} else if err := json.Unmarshal(old, &root); err != nil {
		return installResult{}, err
	}
	cmd := exe + " hook-context"
	hooks, _ := root["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
		root["hooks"] = hooks
	}
	entries, _ := hooks[event].([]any)
	var kept []any
	found := false
	for _, entryAny := range entries {
		entry, _ := entryAny.(map[string]any)
		if entry != nil && entryHasCommand(entry, cmd) {
			found = true
			if uninstall {
				continue
			}
		}
		kept = append(kept, entryAny)
	}
	if !uninstall && !found {
		entry := map[string]any{
			"hooks": []any{map[string]any{"type": "command", "command": cmd, "timeout": timeout}},
		}
		if matcher != "" {
			entry["matcher"] = matcher
		}
		kept = append(kept, entry)
	}
	if len(kept) == 0 {
		delete(hooks, event)
	} else {
		hooks[event] = kept
	}
	if len(hooks) == 0 {
		delete(root, "hooks")
	}
	next, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return installResult{}, err
	}
	next = append(next, '\n')
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

// kimiHookMarker identifies our block in a config the user also edits by
// hand. Kimi keeps hooks in config.toml as an array of tables, so removal
// cannot key on a table name the way the MCP block does — several [[hooks]]
// entries are legal and only one of them is ours.
const kimiHookMarker = "# deja: auto-recall (managed by `deja install kimi-auto`)"

// Kimi Code runs SessionStart hooks, so auto-recall works there too. Its
// config is TOML, not JSON, and the entry is a flat table rather than the
// nested matcher/hooks shape Claude uses.
func installKimiAuto(exe string, uninstall bool) (installResult, error) {
	path := filepath.Join(sources.KimiConfigDir(), "config.toml")
	old, _ := os.ReadFile(path)
	s := removeKimiHookBlock(string(old))
	s = strings.TrimRight(s, "\n")
	if !uninstall {
		block := kimiHookMarker + "\n[[hooks]]\nevent = \"SessionStart\"\ncommand = " +
			strconv.Quote(exe+" hook-context") + "\ntimeout = 10\n"
		if s != "" {
			s += "\n\n"
		}
		s += block
	} else if s != "" {
		s += "\n"
	}
	a, err := writeIfChanged(path, old, []byte(s))
	return installResult{Path: path, Action: a}, err
}

// removeKimiHookBlock drops our marked entry and nothing else: the next table
// header ends it, so a hand-written [[hooks]] below survives.
func removeKimiHookBlock(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	for i := 0; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) != kimiHookMarker {
			out = append(out, lines[i])
			continue
		}
		i++ // skip the marker
		if i < len(lines) && strings.HasPrefix(strings.TrimSpace(lines[i]), "[[hooks]]") {
			i++
		}
		for i < len(lines) && !strings.HasPrefix(strings.TrimSpace(lines[i]), "[") {
			i++
		}
		i-- // the loop's own i++ steps onto the next table header
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n") + "\n"
}
