package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// OpenClaw has its own internal hook system: a pack is a directory with
// HOOK.md (frontmatter) plus handler.js, and ~/.openclaw/hooks is a discovery
// root, so no `openclaw plugins install` step is needed.
//
// The injection point is the agent:bootstrap event, whose context carries
// bootstrapFiles — the Project Context set. Appending an entry there puts the
// digest in front of the model without writing anything to the workspace.
//
// Two things this cost an hour to learn, both by running it:
//   - The event only fires in gateway mode, and only when the agent workspace
//     is first bootstrapped — not once per session. `openclaw agent --local`
//     never emits it at all, so the pack looks dead when tested that way.
//   - Internal hooks are off wholesale until hooks.internal.enabled is set, and
//     a pack that is listed as "ready" still never runs until then.
//
// OpenClaw's default backend is claude-cli, which already inherits deja's
// Claude Code hook; this pack is what covers its other providers.
const openclawHookName = "deja-recall"

func installOpenClawHooks(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(sources.OpenClawStateDir(), "hooks", openclawHookName)
	if uninstall {
		if err := os.RemoveAll(dir); err != nil {
			return installResult{}, err
		}
		if _, err := setOpenClawHookEnabled(false); err != nil {
			return installResult{}, err
		}
		return installResult{Path: dir, Action: "removed"}, nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return installResult{}, err
	}
	docPath := filepath.Join(dir, "HOOK.md")
	oldDoc, err := readConfig(docPath)
	if err != nil {
		return installResult{}, err
	}
	if _, err := writeIfChanged(docPath, oldDoc, []byte(openclawHookDoc())); err != nil {
		return installResult{}, err
	}
	handlerPath := filepath.Join(dir, "handler.js")
	oldHandler, err := readConfig(handlerPath)
	if err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(handlerPath, oldHandler, []byte(openclawHandlerJS(exe)))
	if err != nil {
		return installResult{}, err
	}
	if _, err := setOpenClawHookEnabled(true); err != nil {
		return installResult{}, err
	}
	return installResult{Path: dir, Action: a}, nil
}

// setOpenClawHookEnabled flips hooks.internal.enabled and our entry. Without
// both, the pack is discovered and listed as ready but never invoked.
func setOpenClawHookEnabled(on bool) (string, error) {
	path := filepath.Join(sources.OpenClawStateDir(), "openclaw.json")
	old, err := readConfig(path)
	if err != nil {
		return "", err
	}
	var root map[string]any
	if len(bytes.TrimSpace(old)) == 0 {
		if !on {
			return "unchanged", nil
		}
		root = map[string]any{}
	} else if err := json.Unmarshal(old, &root); err != nil {
		return "", configParseError(path, err)
	}
	hooks, _ := root["hooks"].(map[string]any)
	internal, _ := mapAt(hooks, "internal")
	entries, _ := mapAt(internal, "entries")
	if !on {
		if entries == nil {
			return "unchanged", nil
		}
		delete(entries, openclawHookName)
		// Leave the user's other hooks — and the master switch — alone.
		if len(entries) == 0 {
			delete(internal, "entries")
			delete(internal, "enabled")
		}
		if len(internal) == 0 {
			delete(hooks, "internal")
		}
		if len(hooks) == 0 {
			delete(root, "hooks")
		}
	} else {
		if hooks == nil {
			hooks = map[string]any{}
			root["hooks"] = hooks
		}
		if internal == nil {
			internal = map[string]any{}
			hooks["internal"] = internal
		}
		if entries == nil {
			entries = map[string]any{}
			internal["entries"] = entries
		}
		internal["enabled"] = true
		entries[openclawHookName] = map[string]any{"enabled": true}
	}
	next, err := marshalConfigLike(old, root)
	if err != nil {
		return "", err
	}
	next = append(next, '\n')
	return writeIfChanged(path, old, next)
}

func mapAt(parent map[string]any, key string) (map[string]any, bool) {
	if parent == nil {
		return nil, false
	}
	m, ok := parent[key].(map[string]any)
	return m, ok
}

func openclawHookDoc() string {
	return `---
name: ` + openclawHookName + `
description: "Recall the user's past sessions from deja at agent bootstrap"
metadata:
  {
    "openclaw":
      {
        "emoji": "🧠",
        "events": ["agent:bootstrap"],
      },
  }
---

# deja recall

Generated by ` + "`deja install openclaw-auto`" + ` — safe to delete.

Adds one Project Context entry holding deja's digest of the user's prior
sessions, so a fresh OpenClaw session starts knowing what was already done.
`
}

func openclawHandlerJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install openclaw-auto
import { execFileSync } from "node:child_process";

const DEJA = %q;

export default async (event) => {
  if (event?.type !== "agent" || event?.action !== "bootstrap") return;
  const context = event.context;
  if (!context || !Array.isArray(context.bootstrapFiles)) return;
  try {
    const digest = execFileSync(DEJA, ["hook-context", "--plain"], {
      encoding: "utf8",
      timeout: 10000,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (!digest) return;
    context.bootstrapFiles.push({
      name: "DEJA-RECALL.md",
      path: "deja://recall",
      content: digest,
      missing: false,
    });
  } catch {
    // memory is optional: never break the session over it
  }
};
`, exe)
}
