package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// A snapshot that holds nothing but deja's own block is deja's, and the
// uninstall said it was a config the reader already had. The rule was there —
// writeIfChanged drops a backup that mentionsDeja — but the two "removed" fast
// paths return before the defer that applies it, and taking deja's whole block
// out of a file deja wrote is exactly that path (#3340).
func TestUninstallDropsASnapshotThatIsOnlyDejas(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "cordis.patch.yml")
	own := "# deja mcp:start — generated by deja install, safe to delete\n- insert:\n    - id: mcp-deja\n# deja mcp:end\n"
	if err := os.WriteFile(path, []byte(own), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path+".bak", []byte(own), 0o644); err != nil {
		t.Fatal(err)
	}

	removingWiring = true
	createdByThisRun = append(createdByThisRun, path)
	rememberSnapshot(path + ".bak")
	defer func() { removingWiring = false; createdByThisRun = nil; snapshotsByThisRun = nil }()

	got, err := writeIfChanged(path, []byte(own), nil)
	if err != nil {
		t.Fatal(err)
	}
	if got != "removed" {
		t.Fatalf("state = %q, want removed", got)
	}
	if _, err := os.Stat(path + ".bak"); err == nil {
		t.Error("the snapshot of deja's own block is still there, and uninstall calls it a config the reader already had")
	}
}

// And the other side, unchanged since #2604: a snapshot of the reader's own
// config stays, whatever deja does to the live file.
func TestUninstallKeepsASnapshotThatIsTheReadersOwn(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "cordis.patch.yml")
	if err := os.WriteFile(path, []byte("# deja mcp:start\n- insert: []\n# deja mcp:end\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	theirs := "plugins:\n  - name: something-of-mine\n"
	if err := os.WriteFile(path+".bak", []byte(theirs), 0o644); err != nil {
		t.Fatal(err)
	}
	removingWiring = true
	defer func() { removingWiring = false }()

	if _, err := writeIfChanged(path, nil, nil); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(path + ".bak")
	if err != nil {
		t.Fatalf("the reader's own snapshot was deleted: %v", err)
	}
	if !strings.Contains(string(b), "something-of-mine") {
		t.Errorf("snapshot = %q, want the reader's own config", b)
	}
}

// And the guard on that: a config the reader wrote themselves is not deja's to
// delete, whatever its snapshot happens to say. mentionsDeja matches a comment
// with the word in it, so on a file deja never created the snapshot stays
// (review of #3340).
func TestUninstallKeepsASnapshotBesideAFileDejaDidNotCreate(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "cordis.patch.yml")
	if err := os.WriteFile(path, []byte("# deja mcp:start\n- insert: []\n# deja mcp:end\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	theirs := "# my note: I looked at \"deja\" last year\nplugins:\n  - name: something-of-mine\n"
	if err := os.WriteFile(path+".bak", []byte(theirs), 0o644); err != nil {
		t.Fatal(err)
	}

	removingWiring = true
	defer func() { removingWiring = false }()

	if _, err := writeIfChanged(path, []byte("x"), nil); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(path + ".bak")
	if err != nil {
		t.Fatalf("a snapshot beside a file deja never created was deleted: %v", err)
	}
	if !strings.Contains(string(b), "something-of-mine") {
		t.Errorf("snapshot = %q, want the reader's own config", b)
	}
}

// Provenance, not content: a snapshot the reader put there themselves stays,
// even beside a file deja created and even when its text trips the marker
// list — a comment with the word in it is still their comment (second review
// of #3340).
func TestUninstallKeepsASnapshotDejaDidNotTake(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "cordis.patch.yml")
	own := "# deja mcp:start — generated by deja install\n- insert:\n    - id: mcp-deja\n# deja mcp:end\n"
	if err := os.WriteFile(path, []byte(own), 0o644); err != nil {
		t.Fatal(err)
	}
	theirs := "# I disabled deja: here for now, keeping my own notes\nplugins:\n  - name: something-of-mine\n"
	if err := os.WriteFile(path+".bak", []byte(theirs), 0o644); err != nil {
		t.Fatal(err)
	}

	removingWiring = true
	createdByThisRun = append(createdByThisRun, path)
	defer func() { removingWiring = false; createdByThisRun = nil; snapshotsByThisRun = nil }()

	if _, err := writeIfChanged(path, []byte(own), nil); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(path + ".bak")
	if err != nil {
		t.Fatalf("a snapshot deja never took was deleted: %v", err)
	}
	if !strings.Contains(string(b), "something-of-mine") {
		t.Errorf("snapshot = %q, want the reader's own file", b)
	}
}

// The write side follows a symlink before taking the snapshot, so the record
// holds the resolved name while the uninstall still has the one it was given —
// on macOS every t.TempDir() path is /var, resolving to /private/var, and a
// config in a dotfiles repository is the real-world case. Both spellings are
// asked, or deja would keep its own snapshot forever (second review of #3340).
func TestUninstallDropsItsOwnSnapshotThroughASymlink(t *testing.T) {
	tmp := t.TempDir()
	real := filepath.Join(tmp, "real")
	if err := os.MkdirAll(real, 0o755); err != nil {
		t.Fatal(err)
	}
	link := filepath.Join(tmp, "link")
	if err := os.Symlink(real, link); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	path := filepath.Join(link, "cordis.patch.yml")
	own := "# deja mcp:start\n- insert:\n    - id: mcp-deja\n      command: \"deja\"\n# deja mcp:end\n"
	// The file already holds deja's block from an earlier run, so the snapshot
	// taken now is deja's own — the case the drop rule is about.
	if err := os.WriteFile(path, []byte(own), 0o644); err != nil {
		t.Fatal(err)
	}

	// Install: the snapshot is taken through the link and recorded resolved.
	if _, err := writeIfChanged(path, []byte(own), []byte(own+"# again\n")); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path + ".bak"); err != nil {
		t.Fatalf("install took no snapshot: %v", err)
	}

	removingWiring = true
	createdByThisRun = append(createdByThisRun, path)
	defer func() { removingWiring = false; createdByThisRun = nil; snapshotsByThisRun = nil }()

	if _, err := writeIfChanged(path, []byte(own), nil); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path + ".bak"); err == nil {
		t.Error("deja kept its own snapshot because the recorded path was the resolved one")
	}
}

// Either spelling finds it: the record now carries the name the caller gave
// as well as the resolved one, because nothing can resolve a real path back to
// the link that pointed at it (second review of #3340).
func TestUninstallDropsASnapshotRecordedUnderTheOtherSpelling(t *testing.T) {
	tmp := t.TempDir()
	real := filepath.Join(tmp, "real")
	if err := os.MkdirAll(real, 0o755); err != nil {
		t.Fatal(err)
	}
	link := filepath.Join(tmp, "link")
	if err := os.Symlink(real, link); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	own := "# deja mcp:start\n- insert:\n    - id: mcp-deja\n      command: \"deja\"\n# deja mcp:end\n"
	viaLink := filepath.Join(link, "cordis.patch.yml")
	if err := os.WriteFile(viaLink, []byte(own), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(viaLink+".bak", []byte(own), 0o600); err != nil {
		t.Fatal(err)
	}
	// The record holds the link spelling, which is what an older deja wrote
	// and what any write that did not resolve the path leaves behind.
	snapshotsByThisRun = nil
	rememberSnapshot(viaLink + ".bak")

	// The uninstall arrives with the real path, not the link.
	viaReal := filepath.Join(real, "cordis.patch.yml")
	removingWiring = true
	createdByThisRun = append(createdByThisRun, viaReal)
	defer func() { removingWiring = false; createdByThisRun = nil; snapshotsByThisRun = nil }()
	if _, err := writeIfChanged(viaReal, []byte(own), nil); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(viaReal + ".bak"); err == nil {
		t.Error("deja's own snapshot outlived the uninstall because it was recorded under the other spelling")
	}
}
