package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// DeepSeek Harness has no MCP config file. It composes a profile from plugin
// bundles and one user patch layer, and an MCP server is a plugin instance in
// that layer — one entry per server, as `@deepseek-ai/dsh-mcp-client`.
//
// So install writes `$DSH_HOME/cordis.patch.yml`, the home-level layer every
// profile composes over its own. The per-profile file would work too and is
// what a person edits by hand, but which profile is active is a launch flag:
// writing one home layer reaches the profiles that exist, the ones generated
// later, and a machine where dsh has never run at all.
//
// The block is marked and rewritten in place, the way deja edits every file it
// does not own. A freshly generated layer holds the empty array `[]`, which
// cannot carry a list entry after it, so that literal is replaced rather than
// appended to.

const (
	dshBlockStart = "# deja mcp:start — generated by deja install, safe to delete"
	dshBlockEnd   = "# deja mcp:end"
)

// dshCommandPath is deja's own plugin file. dsh registers slash commands in
// code rather than from a directory of markdown, so /deja is a plugin that
// calls ctx.commands.register — and a profile row may name an absolute path,
// which is how deja ships one without publishing a package.
func dshCommandPath() string {
	return filepath.Join(sources.DSHHome(), "plugins", "deja", "command.js")
}

// dshCommandJS registers /deja. The shape came from running dsh against it:
// the dependency is declared as `apply.inject`, the handler field is `handler`
// rather than `handle`, and a wrong spelling of either fails the whole profile
// load rather than skipping the plugin.
func dshCommandJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install deepseek
import { execFileSync } from "node:child_process";

const DEJA = %q;

function apply(ctx) {
  ctx.commands.register({
    name: "deja",
    description: "Search this machine's past AI coding sessions",
    input: { hint: "what to look for" },
    async handler(invocation) {
      const query = String((invocation && invocation.rawInput) || "").trim();
      if (!query) {
        return { kind: "error", text: "Say what to look for: /deja <error, file, or decision>" };
      }
      try {
        const out = execFileSync(DEJA, [query], {
          encoding: "utf8",
          timeout: 20000,
          maxBuffer: 4 * 1024 * 1024,
          stdio: ["ignore", "pipe", "ignore"],
        }).trim();
        return { kind: "success", text: out || "Nothing in this machine's history matches that." };
      } catch (err) {
        return { kind: "error", text: "deja: " + String((err && err.message) || err) };
      }
    },
  });
}

apply.inject = ["commands"];

export default apply;
`, exe)
}

// dshAutoPath is the plugin that puts recall in front of the model without
// anyone asking for it.
func dshAutoPath() string {
	return filepath.Join(sources.DSHHome(), "plugins", "deja", "auto.js")
}

// dshAutoJS injects recall through `ctx.systemPrompt.context`, the seam the
// host evaluates on every assembly, so the answer arrives inside the runtime
// context the model already reads.
//
// The obvious alternative is a middleware on `agent/pre-step` that splices a
// message into the step. It looks like it works — the turn completes and
// nothing is reported — but a later listener in that waterfall rebuilds its
// answer from the payload and the added message is dropped before the request
// is built. Verified against dsh 0.1.1-rc.2 by reading the request the harness
// actually sent: with the splice the recall was absent, with this seam the
// runtime-context message grew by exactly the recalled bytes.
//
// At assembly time the prompt has left the inbox and has not been appended as
// a "user/message" yet, so the only durable record of it is the inbox splice
// that carried it in.
func dshAutoJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install deepseek-auto
import { execFileSync } from "node:child_process";

const DEJA = %q;

function recall(prompt) {
  try {
    return execFileSync(DEJA, ["hook-prompt", "--plain"], {
      input: JSON.stringify({ prompt, cwd: process.cwd() }),
      encoding: "utf8",
      timeout: 10000,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    // Memory is optional: a plugin that throws here ends the turn.
    return "";
  }
}

function userText(message) {
  const content = message && message.content;
  if (!Array.isArray(content)) return typeof content === "string" ? content.trim() : "";
  return content
    .filter((part) => part && part.type === "text" && typeof part.text === "string")
    .map((part) => part.text)
    .join("\n")
    .trim();
}

function isHuman(message) {
  return Boolean(message) && (!message.source || message.source.kind === "user");
}

function lastHumanText(agent) {
  const events = agent && agent.session && agent.session.events;
  if (!Array.isArray(events)) return "";
  for (let i = events.length - 1; i >= 0; i--) {
    const event = events[i];
    if (!event) continue;
    if (event.type === "user/message" && isHuman(event.data)) return userText(event.data);
    if (event.type === "agent/inbox/spliced") {
      const inserted = event.data && event.data.inserted;
      if (!Array.isArray(inserted)) continue;
      for (let j = inserted.length - 1; j >= 0; j--) {
        if (isHuman(inserted[j])) return userText(inserted[j]);
      }
    }
  }
  return "";
}

function apply(ctx) {
  let asked = "";
  let recalled = "";

  ctx.systemPrompt.context({
    name: "deja:recall",
    order: 120,
    text: (assembly) => {
      const agent = assembly && assembly.agent;
      if (!agent) return "";
      const prompt = lastHumanText(agent);
      if (!prompt) return "";
      if (prompt !== asked) {
        asked = prompt;
        recalled = recall(prompt);
      }
      // Silence is the common case: this speaks only when the history answers.
      return recalled;
    },
  });
}

apply.inject = ["systemPrompt"];

export default apply;
`, exe)
}

func dshPatchBlock(exe string, withAuto bool) string {
	// `insert`, not a bare row: a patch entry addresses a row that already
	// exists ("entry \"mcp-deja\" not found" when it does not), and adding a
	// plugin is an insert list — the shape dsh's own bundles use.
	return dshBlockStart + "\n" +
		"- insert:\n" +
		"    - id: mcp-deja\n" +
		"      name: '@deepseek-ai/dsh-mcp-client'\n" +
		"      config:\n" +
		"        serverName: deja\n" +
		"        transport: stdio\n" +
		"        command: " + yamlQuote(exe) + "\n" +
		"        args: ['mcp']\n" +
		"    - id: deja-command\n" +
		"      name: " + yamlQuote(dshCommandPath()) + "\n" +
		autoRow(withAuto) +
		dshBlockEnd
}

// autoRow names the auto-recall plugin only when it is on disk: the profile
// refuses to load when a row points at a file that is not there.
func autoRow(withAuto bool) string {
	if !withAuto {
		return ""
	}
	return "    - id: deja-auto\n" +
		"      name: " + yamlQuote(dshAutoPath()) + "\n"
}

// dshPatchWith returns the layer with deja's block present exactly once.
func dshPatchWith(old, block string) (string, error) {
	// One marker without the other means the block cannot be bounded. Skipping
	// from the start marker to end of file deleted a patch the user had written
	// below it; leaving an unmarked block in place installed deja twice, with
	// the orphan invisible to every later run (#1701). The first line of the
	// block says "safe to delete", which is an invitation to edit exactly this.
	if err := checkDSHMarkers(old); err != nil {
		return "", err
	}
	if trimmed := stripDSHBlock(old); trimmed != "" {
		return trimmed + "\n" + block + "\n", nil
	}
	return block + "\n", nil
}

// checkDSHMarkers reports whether deja's block can be bounded: both markers
// present, each on a line of its own, the start before the end.
//
// One without the other, or the two in the wrong order, sends stripDSHBlock's
// skip to the end of the file and deletes whatever the user wrote below —
// which the block's own "safe to delete" invites them to have edited (#1701).
// Matching whole lines rather than substrings keeps a marker quoted inside a
// value from counting.
func checkDSHMarkers(doc string) error {
	start, end := -1, -1
	for i, line := range strings.Split(doc, "\n") {
		switch t := strings.TrimSpace(line); {
		case strings.HasPrefix(t, dshBlockStart):
			if start < 0 {
				start = i
			}
		case t == dshBlockEnd:
			if end < 0 {
				end = i
			}
		}
	}
	switch {
	case start < 0 && end < 0:
		return nil
	case start < 0:
		return fmt.Errorf("deja's block in cordis.patch.yml has no start marker — put it back, or delete the block entirely")
	case end < 0:
		return fmt.Errorf("deja's block in cordis.patch.yml has no end marker — put it back, or delete the block entirely")
	case end < start:
		return fmt.Errorf("deja's block in cordis.patch.yml has its end marker above its start marker — put them in order, or delete the block entirely")
	}
	return nil
}

// stripDSHBlock removes deja's block and the empty-array literal a generated
// layer starts with, leaving whatever the user wrote.
func stripDSHBlock(s string) string {
	var out []string
	skipping := false
	for _, line := range strings.Split(s, "\n") {
		switch {
		case strings.HasPrefix(strings.TrimSpace(line), dshBlockStart):
			skipping = true
			continue
		case strings.TrimSpace(line) == dshBlockEnd:
			skipping = false
			continue
		case skipping:
			continue
		case strings.TrimSpace(line) == "[]":
			// The generated placeholder for "no entries"; a list entry cannot
			// follow it.
			continue
		}
		out = append(out, line)
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n")
}

func installDeepSeekMCP(exe string, uninstall bool) (installResult, error) {
	return installDeepSeek(exe, uninstall, false)
}

// installDeepSeekAuto adds the plugin that puts recall in front of the model
// without anyone asking. It writes the server too: `deja install --auto`
// installs only the -auto target.
func installDeepSeekAuto(exe string, uninstall bool) (installResult, error) {
	return installDeepSeek(exe, uninstall, true)
}

func installDeepSeek(exe string, uninstall, withAuto bool) (installResult, error) {
	path := filepath.Join(sources.DSHHome(), "cordis.patch.yml")
	old, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return installResult{}, err
	}
	if uninstall {
		if len(old) == 0 || !strings.Contains(string(old), dshBlockStart) {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		// The same check the install side makes: skipping from a start marker
		// with no end runs to end of file and takes the user's own patch with
		// it, and uninstall is exactly when someone with a hand-edited file
		// needs their content left alone (#1701).
		if err := checkDSHMarkers(lfText(old)); err != nil {
			return installResult{}, err
		}
		rest := stripDSHBlock(string(old))
		if strings.TrimSpace(rest) == "" {
			// An empty layer is the empty array, not an empty file: a patch
			// file with nothing in it fails the profile load.
			rest = "[]"
		}
		a, err := writeIfChanged(path, old, []byte(rest+"\n"))
		if err != nil {
			return installResult{}, err
		}
		// The layer stops naming the plugin before the plugin goes, so a
		// profile is never left pointing at a file that is not there.
		if err := os.RemoveAll(filepath.Dir(dshCommandPath())); err != nil {
			return installResult{}, err
		}
		return installResult{Path: path, Action: a}, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return installResult{}, err
	}
	// The command plugin first: a profile row naming a file that is not there
	// fails the whole profile load, so the layer is written last.
	cmdPath := dshCommandPath()
	if err := os.MkdirAll(filepath.Dir(cmdPath), 0o755); err != nil {
		return installResult{}, err
	}
	oldCmd, _ := os.ReadFile(cmdPath)
	if _, err := writeIfChanged(cmdPath, oldCmd, []byte(dshCommandJS(exe))); err != nil {
		return installResult{}, err
	}
	if withAuto {
		autoPath := dshAutoPath()
		oldAuto, _ := os.ReadFile(autoPath)
		if _, err := writeIfChanged(autoPath, oldAuto, []byte(dshAutoJS(exe))); err != nil {
			return installResult{}, err
		}
	} else if err := os.Remove(dshAutoPath()); err != nil && !os.IsNotExist(err) {
		return installResult{}, err
	}
	patched, perr := dshPatchWith(lfText(old), dshPatchBlock(exe, withAuto))
	if perr != nil {
		return installResult{}, perr
	}
	a, err := writeIfChanged(path, old, []byte(patched))
	return installResult{Path: path, Action: a}, err
}
