package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// DeepSeek Harness has no MCP config file. It composes a profile from plugin
// bundles and one user patch layer, and an MCP server is a plugin instance in
// that layer — one entry per server, as `@deepseek-ai/dsh-mcp-client`.
//
// So install writes `$DSH_HOME/cordis.patch.yml`, the home-level layer every
// profile composes over its own. The per-profile file would work too and is
// what a person edits by hand, but which profile is active is a launch flag:
// writing one home layer reaches the profiles that exist, the ones generated
// later, and a machine where dsh has never run at all.
//
// The block is marked and rewritten in place, the way deja edits every file it
// does not own. A freshly generated layer holds the empty array `[]`, which
// cannot carry a list entry after it, so that literal is replaced rather than
// appended to.

const (
	dshBlockStart = "# deja mcp:start — generated by deja install, safe to delete"
	dshBlockEnd   = "# deja mcp:end"
	// dshArrayNote rides inside the block when it replaced the generated
	// layer's empty array, so uninstall knows to put the array back (#3271).
	dshArrayNote = "# (this block stands in for the empty array the layer held)"
)

// dshCommandPath is deja's own plugin file. dsh registers slash commands in
// code rather than from a directory of markdown, so /deja is a plugin that
// calls ctx.commands.register — and a profile row may name an absolute path,
// which is how deja ships one without publishing a package.
func dshCommandPath() string {
	return filepath.Join(sources.DSHHome(), "plugins", "deja", "command.js")
}

// dshCommandJS registers /deja. The shape came from running dsh against it:
// the dependency is declared as `apply.inject`, the handler field is `handler`
// rather than `handle`, and a wrong spelling of either fails the whole profile
// load rather than skipping the plugin.
func dshCommandJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install; cordis.patch.yml loads this file and dsh will not start without it — remove with: deja uninstall deepseek
import { execFileSync } from "node:child_process";

const DEJA = %q;

function apply(ctx) {
  // Loaded twice in one profile the host throws "command deja is already
  // registered" and the whole profile fails to load, which costs the user
  // their agent over a duplicate search command. One /deja is enough.
  try {
  ctx.commands.register({
    name: "deja",
    description: "Search this machine's past AI coding sessions",
    input: { hint: "what to look for" },
    async handler(invocation) {
      const query = String((invocation && invocation.rawInput) || "").trim();
      if (!query) {
        return { kind: "error", text: "Say what to look for: /deja <error, file, or decision>" };
      }
      // "search" is named rather than handed over as deja's first word: the
      // bare-query path dispatches a word that happens to be a command, so
      // /deja version printed a version number and /deja index rebuilt the
      // index. "--" then keeps a query that starts with a dash from being read
      // as a flag, which came back as an error the caller cannot tell from an
      // empty history.
      const args = query.startsWith("-") ? ["search", "--", query] : ["search", query];
      try {
        const out = execFileSync(DEJA, args, {
          encoding: "utf8",
          timeout: 20000,
          maxBuffer: 4 * 1024 * 1024,
          stdio: ["ignore", "pipe", "ignore"],
        }).trim();
        return { kind: "success", text: out || "Nothing in this machine's history matches that." };
      } catch (err) {
        return { kind: "error", text: "deja: " + String((err && err.message) || err) };
      }
    },
  });
  } catch {}
}

apply.inject = ["commands"];

export default apply;
`, exe)
}

// dshAutoPath is the plugin that puts recall in front of the model without
// anyone asking for it.
func dshAutoPath() string {
	return filepath.Join(sources.DSHHome(), "plugins", "deja", "auto.js")
}

// dshAutoJS injects recall through `ctx.systemPrompt.context`, the seam the
// host evaluates on every assembly, so the answer arrives inside the runtime
// context the model already reads.
//
// The obvious alternative is a middleware on `agent/pre-step` that splices a
// message into the step. It looks like it works — the turn completes and
// nothing is reported — but a later listener in that waterfall rebuilds its
// answer from the payload and the added message is dropped before the request
// is built. Verified against dsh 0.1.1-rc.2 by reading the request the harness
// actually sent: with the splice the recall was absent, with this seam the
// runtime-context message grew by exactly the recalled bytes.
//
// At assembly time the prompt has left the inbox and has not been appended as
// a "user/message" yet, so the only durable record of it is the inbox splice
// that carried it in.
func dshAutoJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install; cordis.patch.yml loads this file and dsh will not start without it — to drop auto-recall alone, run: deja install deepseek
import { execFile, execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";

const DEJA = %q;

// Memory is optional: a plugin that throws in an assembly ends the turn, so
// every call deja makes is swallowed to "".
function ask(args, payload) {
  try {
    return execFileSync(DEJA, args, {
      input: JSON.stringify(payload),
      encoding: "utf8",
      timeout: 10000,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

// askAsync is ask for the tool seam, which dsh awaits: the event loop goes on
// while deja answers, so one slow lookup does not stall every session the
// process serves. It never rejects.
function askAsync(args, payload) {
  return new Promise((resolve) => {
    try {
      const child = execFile(
        DEJA,
        args,
        { encoding: "utf8", timeout: 10000, maxBuffer: 4 * 1024 * 1024 },
        (err, stdout) => resolve(err ? "" : String(stdout || "").trim()),
      );
      child.on("error", () => resolve(""));
      child.stdin.on("error", () => {});
      child.stdin.end(JSON.stringify(payload));
    } catch {
      resolve("");
    }
  });
}

// The session goes with the prompt: a compaction's recovery packet is kept
// for this session, and only a prompt that names it gets the packet back.
function recall(prompt, cwd, sid) {
  return ask(["hook-prompt", "--plain"], { prompt, cwd, session_id: sid });
}

// dsh names a session "session-<uuid>" and its log's folder the same; deja
// indexes it by the uuid, so that is the id every hook is given.
function bareSessionId(id) {
  return String(id || "").replace(/^session-/, "");
}

function sessionId(agent) {
  return bareSessionId((agent && (agent.sessionId || (agent.session && agent.session.id))) || "");
}

// Compaction shadows the turns it summarises but leaves them in the session
// log, so deja reads the session there as compaction/start lands and keeps a
// recovery packet: the task, each command with how it went, what was still
// open. The log is written behind the session, so it is flushed first. dsh
// assembles a step's context before its agent/pre-step waterfall, where the
// compaction runs, so the step that compacts waits there for the capture and
// the packet rides the recall of the next step, or of the next turn.
function watchCompaction(ctx, capturing, compacted) {
  const listen = (c) =>
    c.on("session/event", (session, event) => {
      if (!session || !event || event.type !== "compaction/start") return;
      const sid = bareSessionId(session.id || (session.header && session.header.id));
      if (!sid) return;
      const cwd = (session.header && session.header.cwd) || process.cwd();
      // One compaction can follow another inside a step; two captures at once
      // contend for the index and the loser marks the packet unavailable, so
      // each waits for the one before it.
      const before = capturing.get(sid) || Promise.resolve();
      const capture = before.then(async () => {
        try {
          if (c.sessions && typeof c.sessions.flush === "function") await c.sessions.flush(session);
        } catch {}
        await askAsync(["hook-precompact"], { session_id: sid, cwd, harness: "deepseek" });
        compacted.add(sid);
      });
      capturing.set(sid, capture);
      capture.then(() => {
        if (capturing.get(sid) === capture) capturing.delete(sid);
      });
    });
  try {
    if (typeof ctx.inject === "function") ctx.inject(["sessions"], listen);
    else listen(ctx);
  } catch {}
  try {
    ctx.on("agent/pre-step", async (step, next) => {
      const sid = sessionId(step && step.agent);
      if (capturing.has(sid)) await capturing.get(sid);
      const decision = await next();
      if (capturing.has(sid)) await capturing.get(sid);
      return decision;
    });
  } catch {}
}

// The workspace a session belongs to. One web or tui process serves sessions
// from every workspace and never changes directory, so process.cwd() is only
// where dsh was launched; the session header carries the directory the session
// was opened in.
function sessionCwd(agent) {
  const header = agent && agent.session && agent.session.header;
  return (header && header.cwd) || process.cwd();
}

// The project digest, once at the start of the session. deja_once keys the
// one-shot on the session id in deja's ledger, which survives a resume in a new
// process; the Set is the in-process guard that keeps the long-lived web and
// tui profiles from spawning deja on every assembly of a session already shown.
function projectDigest(agent, seen) {
  const sid = sessionId(agent);
  if (sid && seen.has(sid)) return "";
  if (sid) seen.add(sid);
  return ask(["hook-context", "--plain"], {
    session_id: sid,
    cwd: sessionCwd(agent),
    source: "startup",
    deja_once: true,
  });
}

function userText(message) {
  const content = message && message.content;
  if (!Array.isArray(content)) return typeof content === "string" ? content.trim() : "";
  return content
    .filter((part) => part && part.type === "text" && typeof part.text === "string")
    .map((part) => part.text)
    .join("\n")
    .trim();
}

function isHuman(message) {
  return Boolean(message) && (!message.source || message.source.kind === "user");
}

function lastHumanText(agent) {
  const events = agent && agent.session && agent.session.events;
  if (!Array.isArray(events)) return "";
  for (let i = events.length - 1; i >= 0; i--) {
    const event = events[i];
    if (!event) continue;
    if (event.type === "user/message" && isHuman(event.data)) return userText(event.data);
    if (event.type === "agent/inbox/spliced") {
      const inserted = event.data && event.data.inserted;
      if (!Array.isArray(inserted)) continue;
      for (let j = inserted.length - 1; j >= 0; j--) {
        if (isHuman(inserted[j])) return userText(inserted[j]);
      }
    }
  }
  return "";
}

function apply(ctx) {
  let asked = "";
  let askedIn = "";
  let askedBy = "";
  let recalled = "";
  const digestSeen = new Set();
  const capturing = new Map();
  const compacted = new Set();

  // A second copy of this file in the same profile — the npm package next to
  // the installer's, a --patch overlay naming it again — makes the host throw
  // "prompt context deja:recall is already registered", and that takes the
  // whole profile down: no agent at all, over an optional memory plugin.
  // One registration is all recall needs, so the loser stands down quietly.
  //
  // Two contexts are registered. deja:project is what this project settled,
  // once at the start of the session, ordered ahead of the per-prompt recall so
  // it reads as background rather than an answer to the question.
  // agent/session-start is emit-only — its return reaches nothing — so the
  // digest rides the same assembly seam the recall does, gated to one turn per
  // session.
  try {
    ctx.systemPrompt.context({
      name: "deja:project",
      order: 110,
      text: (assembly) => {
        const agent = assembly && assembly.agent;
        if (!agent) return "";
        return projectDigest(agent, digestSeen);
      },
    });
    ctx.systemPrompt.context({
      name: "deja:recall",
      order: 120,
      text: (assembly) => {
        const agent = assembly && assembly.agent;
        if (!agent) return "";
        const prompt = lastHumanText(agent);
        if (!prompt) return "";
        const cwd = sessionCwd(agent);
        const sid = sessionId(agent);
        const afterCompaction = compacted.delete(sid);
        // The same question asked in another workspace is a different question,
        // and so is one asked again after its session compacted: deja then
        // answers with the recovery packet.
        if (prompt !== asked || cwd !== askedIn || sid !== askedBy || afterCompaction) {
          asked = prompt;
          askedIn = cwd;
          askedBy = sid;
          recalled = recall(prompt, cwd, sid);
        }
        // Silence is the common case: this speaks only when the history answers.
        return recalled;
      },
    });
  } catch {}

  // The point of action. tools/post-execute runs on every tool result, and an
  // accept decision's additionalContexts reach the model on the next step: a
  // read, edit or write gets what deja knows about the file, a bash that
  // exited non-zero gets the fix this machine found for that error before
  // (#4293). The before-seam, tools/execute, has no channel to the model.
  if (typeof ctx.on !== "function") return;
  watchCompaction(ctx, capturing, compacted);
  // A session is over when dsh disposes of it, or when the process goes:
  // measured on 0.1.1-rc.2, the headless profile exits without disposing
  // anything, and only process "exit" runs. The digest and the tool notes
  // stamp a session live, which keeps it out of its own MCP recall; dropping
  // the stamp lets the next session be answered with it now rather than
  // twenty minutes from now.
  const live = new Set();
  const end = (sid) => {
    if (!sid || !live.has(sid)) return;
    live.delete(sid);
    ask(["hook-session-end"], { session_id: sid });
  };
  try {
    // The stamp is under the bare uuid, so the end has to name that too: the
    // "session-<uuid>" dsh hands over matched nothing and the stamp stayed.
    ctx.on("session/created", (session) => {
      const sid = bareSessionId(session && session.id);
      if (sid) live.add(sid);
    });
    ctx.on("session/disposed", (session) => end(bareSessionId(session && session.id)));
    process.on("exit", () => {
      for (const sid of [...live]) end(sid);
    });
  } catch {}
  try {
    ctx.on("tools/post-execute", async (exec, result, next) => {
      const decision = await next();
      try {
        if (!decision || decision.kind !== "accept" || !exec) return decision;
        const note = await toolNote(exec, result);
        if (!note) return decision;
        return {
          ...decision,
          additionalContexts: [...(decision.additionalContexts || []), noteMessage(note)],
        };
      } catch {
        return decision;
      }
    });
  } catch {}
}

function resultText(result) {
  const content = result && result.content;
  if (!Array.isArray(content)) return "";
  return content
    .filter((part) => part && part.type === "text" && typeof part.text === "string")
    .map((part) => part.text)
    .join("\n");
}

function exitStatus(text) {
  const signal = /\n\[killed by signal: [^\]\n]+\]$/.exec(text);
  if (signal) return { body: text.slice(0, signal.index), failed: true };
  const exit = /\n\[exit code: (\d+)\]$/.exec(text);
  if (exit) return { body: text.slice(0, exit.index), failed: exit[1] !== "0" };
  return { body: text, failed: false };
}

async function toolNote(exec, result) {
  const args = exec.arguments || {};
  const base = { session_id: sessionId(exec.agent), cwd: sessionCwd(exec.agent) };
  if ((exec.name === "read" || exec.name === "edit" || exec.name === "write") && args.file_path) {
    return askAsync(["hook-tool", "--plain"], {
      tool_name: exec.name,
      tool_input: { file_path: String(args.file_path) },
      ...base,
    });
  }
  // The profile's other editor names the file "path"; view is its read.
  if (exec.name === "str_replace_editor" && args.path) {
    return askAsync(["hook-tool", "--plain"], {
      tool_name: args.command === "view" ? "read" : "edit",
      tool_input: { file_path: String(args.path) },
      ...base,
    });
  }
  // pwsh is the Windows shell, with the same markers.
  if (exec.name === "bash" || exec.name === "pwsh") {
    // dsh reports how a command ended in the text, not as an error result: a
    // last line of "[exit code: N]" for a non-zero exit, or "[killed by
    // signal: X]". Read only there, the way dsh's own parseExitStatus reads
    // it, since output may quote a marker anywhere else.
    const output = resultText(result);
    const status = exitStatus(output);
    if (!(result && result.isError) && !status.failed) return "";
    // The marker goes before the lookup, as the index drops it: an error
    // whose last line is "[exit code: 1]" matches nothing on file.
    const response = status.body;
    return askAsync(["hook-tool-after", "--plain"], {
      tool_name: exec.name === "pwsh" ? "powershell" : "bash",
      tool_input: { command: String(args.command || "") },
      tool_response: response,
      ...base,
    });
  }
  return "";
}

// A context message the way dsh's own plugins build one: user role, a plugin
// source so it is not read back as something the person typed, a fresh id,
// frozen.
function noteMessage(text) {
  const message = {
    role: "user",
    content: [{ type: "text", text }],
    source: { kind: "plugin", plugin: "deja", form: "notice" },
    id: randomUUID(),
  };
  Object.freeze(message.content[0]);
  Object.freeze(message.content);
  Object.freeze(message.source);
  return Object.freeze(message);
}

apply.inject = ["systemPrompt"];

export default apply;
`, exe)
}

func dshPatchBlock(exe string, withAuto bool) string {
	// `insert`, not a bare row: a patch entry addresses a row that already
	// exists ("entry \"mcp-deja\" not found" when it does not), and adding a
	// plugin is an insert list — the shape dsh's own bundles use.
	return dshBlockStart + "\n" +
		"- insert:\n" +
		"    - id: mcp-deja\n" +
		"      name: '@deepseek-ai/dsh-mcp-client'\n" +
		"      config:\n" +
		"        serverName: deja\n" +
		"        transport: stdio\n" +
		"        command: " + yamlQuote(exe) + "\n" +
		"        args: ['mcp']\n" +
		"    - id: deja-command\n" +
		"      name: " + yamlQuote(dshCommandPath()) + "\n" +
		autoRow(withAuto) +
		dshBlockEnd
}

// autoRow names the auto-recall plugin only when it is on disk: the profile
// refuses to load when a row points at a file that is not there.
func autoRow(withAuto bool) string {
	if !withAuto {
		return ""
	}
	return "    - id: deja-auto\n" +
		"      name: " + yamlQuote(dshAutoPath()) + "\n"
}

// dshPatchWith returns the layer with deja's block present exactly once.
func dshPatchWith(old, block string) (string, error) {
	// One marker without the other means the block cannot be bounded. Skipping
	// from the start marker to end of file deleted a patch the user had written
	// below it; leaving an unmarked block in place installed deja twice, with
	// the orphan invisible to every later run (#1701). The first line of the
	// block says "safe to delete", which is an invitation to edit exactly this.
	if err := checkDSHMarkers(old); err != nil {
		return "", err
	}
	if dshHadArrayLine(old) || strings.Contains(old, dshArrayNote) {
		block = strings.Replace(block, dshBlockStart+"\n", dshBlockStart+"\n"+dshArrayNote+"\n", 1)
	}
	if trimmed := stripDSHBlock(old); trimmed != "" {
		return trimmed + "\n" + block + "\n", nil
	}
	return block + "\n", nil
}

// checkDSHMarkers reports whether deja's block can be bounded: both markers
// present, each on a line of its own, the start before the end.
//
// One without the other, or the two in the wrong order, sends stripDSHBlock's
// skip to the end of the file and deletes whatever the user wrote below —
// which the block's own "safe to delete" invites them to have edited (#1701).
// Matching whole lines rather than substrings keeps a marker quoted inside a
// value from counting.
func checkDSHMarkers(doc string) error {
	start, end := -1, -1
	for i, line := range strings.Split(doc, "\n") {
		switch t := strings.TrimSpace(line); {
		case strings.HasPrefix(t, dshBlockStart):
			if start < 0 {
				start = i
			}
		case t == dshBlockEnd:
			if end < 0 {
				end = i
			}
		}
	}
	switch {
	case start < 0 && end < 0:
		return nil
	case start < 0:
		return fmt.Errorf("deja's block in cordis.patch.yml has no start marker — put it back, or delete the block entirely")
	case end < 0:
		return fmt.Errorf("deja's block in cordis.patch.yml has no end marker — put it back, or delete the block entirely")
	case end < start:
		return fmt.Errorf("deja's block in cordis.patch.yml has its end marker above its start marker — put them in order, or delete the block entirely")
	}
	return nil
}

// stripDSHBlock removes deja's block and the empty-array literal a generated
// layer starts with, leaving whatever the user wrote.
func stripDSHBlock(s string) string {
	var out []string
	skipping := false
	for _, line := range strings.Split(s, "\n") {
		switch {
		case strings.HasPrefix(strings.TrimSpace(line), dshBlockStart):
			skipping = true
			continue
		case strings.TrimSpace(line) == dshBlockEnd:
			skipping = false
			continue
		case skipping:
			continue
		case strings.TrimSpace(line) == "[]":
			// The generated placeholder for "no entries"; a list entry cannot
			// follow it.
			continue
		}
		out = append(out, line)
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n")
}

// dshHadArrayLine reports whether the layer carries the `[]` placeholder on a
// line of its own — the shape a generated layer has, and what install replaced.
func dshHadArrayLine(doc string) bool {
	for _, line := range strings.Split(doc, "\n") {
		if strings.TrimSpace(line) == "[]" {
			return true
		}
	}
	return false
}

// dshLayerHasEntry reports whether a layer still carries anything YAML would
// read as content — a line that is neither blank nor a comment.
func dshLayerHasEntry(doc string) bool {
	for _, line := range strings.Split(doc, "\n") {
		t := strings.TrimSpace(line)
		if t != "" && !strings.HasPrefix(t, "#") {
			return true
		}
	}
	return false
}

func installDeepSeekMCP(exe string, uninstall bool) (installResult, error) {
	return installDeepSeek(exe, uninstall, false)
}

// installDeepSeekAuto adds the plugin that puts recall in front of the model
// without anyone asking. It writes the server too: `deja install --auto`
// installs only the -auto target.
func installDeepSeekAuto(exe string, uninstall bool) (installResult, error) {
	return installDeepSeek(exe, uninstall, true)
}

func installDeepSeek(exe string, uninstall, withAuto bool) (installResult, error) {
	path := filepath.Join(sources.DSHHome(), "cordis.patch.yml")
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	if uninstall {
		if len(old) == 0 || !strings.Contains(string(old), dshBlockStart) {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		// The same check the install side makes: skipping from a start marker
		// with no end runs to end of file and takes the user's own patch with
		// it, and uninstall is exactly when someone with a hand-edited file
		// needs their content left alone (#1701).
		if err := checkDSHMarkers(lfText(old)); err != nil {
			return installResult{}, err
		}
		rest := stripDSHBlock(string(old))
		if !dshLayerHasEntry(rest) && (strings.TrimSpace(rest) == "" || strings.Contains(string(old), dshArrayNote)) {
			// An empty layer is the empty array, not an empty file or a
			// comment alone: dsh parses either as null and refuses to load
			// the profile. The generated layer is a comment and `[]`; the
			// install replaced the array and said so inside its block, so
			// uninstall puts it back under the comment (#3271). A file that
			// never held one is handed back as it was.
			rest = strings.TrimRight(rest, "\n")
			if rest != "" {
				rest += "\n"
			}
			rest += "[]"
		}
		a, err := writeIfChanged(path, old, []byte(rest+"\n"))
		if err != nil {
			return installResult{}, err
		}
		// The layer stops naming the plugin before the plugin goes, so a
		// profile is never left pointing at a file that is not there.
		if err := os.RemoveAll(filepath.Dir(dshCommandPath())); err != nil {
			return installResult{}, err
		}
		// And the plugins directory above it, when deja made it (#3698).
		pruneCreatedDir(filepath.Dir(filepath.Dir(dshCommandPath())))
		return installResult{Path: path, Action: a}, nil
	}
	// The layer is worked out before the plugins are written, so a layer deja
	// cannot patch refuses the target with nothing written (#4555).
	block, note := dshKeepSwitches(lfText(old), dshPatchBlock(exe, withAuto))
	patched, perr := dshPatchWith(lfText(old), block)
	if perr != nil {
		return installResult{}, perr
	}
	if err := yamlWriteBreaks(path, old, []byte(patched)); err != nil {
		return installResult{}, err
	}
	noteCreatedDirs(filepath.Dir(path))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return installResult{}, err
	}
	// The command plugin first: a profile row naming a file that is not there
	// fails the whole profile load, so the layer is written last.
	cmdPath := dshCommandPath()
	noteCreatedDirs(filepath.Dir(cmdPath))
	if err := os.MkdirAll(filepath.Dir(cmdPath), 0o755); err != nil {
		return installResult{}, err
	}
	// The plugins are ES modules, and Node takes a file's module type from the
	// nearest package.json above it. A home directory whose own package.json
	// declares CommonJS made dsh refuse both plugins ("Failed to load the ES
	// module"), so the directory states its own type before either is written.
	// The name is what lets mentionsDeja recognise the file as deja's wiring,
	// so an uninstall takes its snapshot too.
	pkgPath := filepath.Join(filepath.Dir(cmdPath), "package.json")
	oldPkg, err := readConfig(pkgPath)
	if err != nil {
		return installResult{}, err
	}
	pkgAction, err := writeIfChanged(pkgPath, oldPkg, []byte("{\n  \"name\": \"deja\",\n  \"type\": \"module\"\n}\n"))
	if err != nil {
		return installResult{}, err
	}
	oldCmd, err := readConfig(cmdPath)
	if err != nil {
		return installResult{}, err
	}
	// The launcher for the plugins dsh loads, the binary for the server in
	// the patch block: a plugin that names the build it was installed from
	// stops working the day that build moves (#3682).
	hookExe := hookExeFor(exe, uninstall)
	cmdAction, err := writeIfChanged(cmdPath, oldCmd, []byte(dshCommandJS(hookExe)))
	if err != nil {
		return installResult{}, err
	}
	if pkgAction != "unchanged" {
		cmdAction = pkgAction
	}
	if withAuto {
		autoPath := dshAutoPath()
		oldAuto, err := readConfig(autoPath)
		if err != nil {
			return installResult{}, err
		}
		autoAction, aerr := writeIfChanged(autoPath, oldAuto, []byte(dshAutoJS(hookExe)))
		if aerr != nil {
			return installResult{}, aerr
		}
		if autoAction != "unchanged" {
			cmdAction = autoAction
		}
	} else if err := os.Remove(dshAutoPath()); err != nil && !os.IsNotExist(err) {
		return installResult{}, err
	}
	a, err := writeIfChanged(path, old, []byte(patched))
	if err != nil {
		return installResult{}, err
	}
	// The plugin directory rides along: the files in it are deja's own and
	// went unnamed on the screen whose job is saying what was touched (#3254).
	plugins := installResult{Path: filepath.Dir(cmdPath), Action: cmdAction}
	return wroteAll(installResult{Path: path, Action: a, Note: note}, plugins), nil
}

// dshKeepSwitches carries a `disabled: true` the reader put on one of deja's
// rows over into the block that replaces them. The block is regenerated whole,
// so the switch was dropped and dsh loaded deja again (#4467).
func dshKeepSwitches(old, block string) (string, string) {
	off := map[string]bool{}
	in, row, field := false, "", 0
	for _, line := range strings.Split(old, "\n") {
		t := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(t, dshBlockStart):
			in = true
		case t == dshBlockEnd:
			in, row = false, ""
		case !in:
		case strings.HasPrefix(t, "- id:"):
			row, field = hermesYAMLScalar(strings.TrimPrefix(t, "- id:")), yamlIndentWidth(line)+2
		case row != "" && yamlIndentWidth(line) == field:
			if key, rest, ok := hermesKeyLine(line); ok && hermesKeyName(key) == "disabled" && strings.ToLower(hermesYAMLScalar(rest)) == "true" {
				off[row] = true
			}
		}
	}
	if len(off) == 0 {
		return block, ""
	}
	lines := strings.Split(block, "\n")
	out := make([]string, 0, len(lines)+len(off))
	for _, line := range lines {
		out = append(out, line)
		t := strings.TrimSpace(line)
		if strings.HasPrefix(t, "- id:") && off[hermesYAMLScalar(strings.TrimPrefix(t, "- id:"))] {
			out = append(out, line[:yamlIndentWidth(line)]+"  disabled: true")
		}
	}
	return strings.Join(out, "\n"), switchedOffNote
}
