package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// omp loads extension modules from the active agent directory's extensions/,
// one directory per module. An extension registers handlers on omp's event bus,
// and the one that matters here is `context`: a handler returning `{ messages }`
// replaces what goes to the provider, which is the only seam that reaches the
// model before it answers.
//
// Which event, and that a returned list is honoured at all, came from running a
// probe extension against omp 17.4.1 and watching what fired: `input` never
// does in print mode, `before_agent_start` carries the prompt but not the
// context, and a marker prepended in `context` came back out of the model.

func ompExtensionDir() string {
	return filepath.Join(sources.OmpConfigDir(), "extensions", "deja")
}

// installOmpAuto writes the extension and the MCP server both: `deja install
// --auto` installs the -auto target alone, so an -auto that skipped the server
// would leave the agent with injected memory and no tool to follow it up with.
func installOmpAuto(exe string, uninstall bool) (installResult, error) {
	if _, err := installMCPJSON(filepath.Join(sources.OmpConfigDir(), "mcp.json"), exe, uninstall); err != nil {
		return installResult{}, err
	}
	dir := ompExtensionDir()
	path := filepath.Join(dir, "index.js")
	if uninstall {
		if _, err := os.Stat(path); err != nil {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.RemoveAll(dir); err != nil {
			return installResult{}, err
		}
		return installResult{Path: path, Action: "removed"}, nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return installResult{}, err
	}
	old, _ := os.ReadFile(path)
	a, err := writeIfChanged(path, old, []byte(ompExtensionJS(exe)))
	return installResult{Path: path, Action: a}, err
}

func ompExtensionJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install — safe to delete; regenerate with: deja install omp-auto
import { execFileSync } from "node:child_process";

const DEJA = %q;

function recall(prompt, cwd) {
  try {
    return execFileSync(DEJA, ["hook-prompt", "--plain"], {
      input: JSON.stringify({ prompt, cwd }),
      encoding: "utf8",
      timeout: 10000,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    // Memory is optional: an extension that throws here takes the session with
    // it, because extensions run in-process with no isolation.
    return "";
  }
}

function userText(message) {
  if (!message || message.role !== "user" || !Array.isArray(message.content)) return "";
  return message.content
    .filter((part) => part && part.type === "text" && typeof part.text === "string")
    .map((part) => part.text)
    .join("\n")
    .trim();
}

export default function extension(pi) {
  // The same prompt reaches the context event more than once in a turn — once per
  // provider request — so the answer is cached rather than asked again.
  let asked = "";
  let recalled = "";

  pi.on("context", async (event, ctx) => {
    const messages = Array.isArray(event && event.messages) ? event.messages : null;
    if (!messages || messages.length === 0) return;
    let at = -1;
    for (let i = messages.length - 1; i >= 0; i--) {
      if (messages[i] && messages[i].role === "user") {
        at = i;
        break;
      }
    }
    if (at < 0) return;
    const prompt = userText(messages[at]);
    if (!prompt) return;
    if (prompt !== asked) {
      asked = prompt;
      recalled = recall(prompt, (ctx && ctx.cwd) || process.cwd());
    }
    // Silence is the common case: the hook speaks only when this machine's
    // history actually answers the question.
    if (!recalled) return;
    const out = messages.slice();
    out[at] = {
      ...messages[at],
      content: [{ type: "text", text: recalled }, ...messages[at].content],
    };
    return { messages: out };
  });
}
`, exe)
}
