package main

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// DeepSeek Harness has no MCP config file. It composes a profile from plugin
// bundles and one user patch layer, and an MCP server is a plugin instance in
// that layer — one entry per server, as `@deepseek-ai/dsh-mcp-client`.
//
// So install writes `$DSH_HOME/cordis.patch.yml`, the home-level layer every
// profile composes over its own. The per-profile file would work too and is
// what a person edits by hand, but which profile is active is a launch flag:
// writing one home layer reaches the profiles that exist, the ones generated
// later, and a machine where dsh has never run at all.
//
// The block is marked and rewritten in place, the way deja edits every file it
// does not own. A freshly generated layer holds the empty array `[]`, which
// cannot carry a list entry after it, so that literal is replaced rather than
// appended to.

const (
	dshBlockStart = "# deja mcp:start — generated by deja install, safe to delete"
	dshBlockEnd   = "# deja mcp:end"
)

func dshPatchBlock(exe string) string {
	// `insert`, not a bare row: a patch entry addresses a row that already
	// exists ("entry \"mcp-deja\" not found" when it does not), and adding a
	// plugin is an insert list — the shape dsh's own bundles use.
	return dshBlockStart + "\n" +
		"- insert:\n" +
		"    - id: mcp-deja\n" +
		"      name: '@deepseek-ai/dsh-mcp-client'\n" +
		"      config:\n" +
		"        serverName: deja\n" +
		"        transport: stdio\n" +
		"        command: " + yamlQuote(exe) + "\n" +
		"        args: ['mcp']\n" +
		dshBlockEnd
}

// dshPatchWith returns the layer with deja's block present exactly once.
func dshPatchWith(old, block string) string {
	if trimmed := stripDSHBlock(old); trimmed != "" {
		return trimmed + "\n" + block + "\n"
	}
	return block + "\n"
}

// stripDSHBlock removes deja's block and the empty-array literal a generated
// layer starts with, leaving whatever the user wrote.
func stripDSHBlock(s string) string {
	var out []string
	skipping := false
	for _, line := range strings.Split(s, "\n") {
		switch {
		case strings.HasPrefix(strings.TrimSpace(line), dshBlockStart):
			skipping = true
			continue
		case strings.TrimSpace(line) == dshBlockEnd:
			skipping = false
			continue
		case skipping:
			continue
		case strings.TrimSpace(line) == "[]":
			// The generated placeholder for "no entries"; a list entry cannot
			// follow it.
			continue
		}
		out = append(out, line)
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n")
}

func installDeepSeekMCP(exe string, uninstall bool) (installResult, error) {
	path := filepath.Join(sources.DSHHome(), "cordis.patch.yml")
	old, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return installResult{}, err
	}
	if uninstall {
		if len(old) == 0 || !strings.Contains(string(old), dshBlockStart) {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		rest := stripDSHBlock(string(old))
		if strings.TrimSpace(rest) == "" {
			// An empty layer is the empty array, not an empty file: a patch
			// file with nothing in it fails the profile load.
			rest = "[]"
		}
		a, err := writeIfChanged(path, old, []byte(rest+"\n"))
		return installResult{Path: path, Action: a}, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(path, old, []byte(dshPatchWith(string(old), dshPatchBlock(exe))))
	return installResult{Path: path, Action: a}, err
}
