package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// dsh has no terminal UI; the web client is built from client plugins that
// register components into slots. deja's status line is one: a package with a
// node half that answers GET /deja/statusline on dsh's own web server, and a
// browser half that polls it and renders the line in the
// conversation.composer.dock slot, beside dsh's own token and speed pills.
//
// A profile row may name a file, and the client-modules scan then reads the
// nearest package.json for dsh.client and its "./client" export
// (locatePkgJson in dsh-client-modules 0.2.0-rc.2). The package needs a
// directory of its own: two rows resolving to one package name are refused,
// and the command and auto-recall plugins already own plugins/deja. A stand on
// dsh 0.2.0-rc.2 rendered the line under the composer in headless Chromium.

const dshStatusPackage = "deja-status"

func dshStatusDir() string {
	return filepath.Join(sources.DSHHome(), "plugins", dshStatusPackage)
}

func dshStatusPath() string { return filepath.Join(dshStatusDir(), "index.js") }

// dshStatusRow names the status plugin only when it is on disk, the same rule
// as the auto-recall row.
func dshStatusRow(withAuto bool) string {
	if !withAuto {
		return ""
	}
	return "    - id: deja-status\n" +
		"      name: " + yamlQuote(dshStatusPath()) + "\n"
}

// dsh's plugin inventory refuses a package.json without a version, and that
// refusal fails every model request rather than the one plugin (0.2.0-rc.2).
const dshStatusPackageJSON = `{
  "name": "deja-status",
  "version": "1.0.0",
  "type": "module",
  "exports": {
    ".": "./index.js",
    "./client": "./client.js"
  },
  "dsh": {
    "client": {
      "platform": "web",
      "inject": [
        "@deepseek-ai/dsh-client-ui-renderer",
        "@deepseek-ai/dsh-client-ui-conversation"
      ]
    }
  }
}
`

// dshStatusServerJS is the node half. Only the web profile has a web server,
// so the route is registered inside ctx.inject: the headless profile loads the
// row without waiting on a service it will never get.
func dshStatusServerJS(exe string) string {
	return fmt.Sprintf(`// generated by deja install; cordis.patch.yml loads this file — remove with: deja install deepseek
import { execFile } from "node:child_process";

const DEJA = %q;
const ROUTE = "/deja/statusline";

// The page polls every few seconds; one deja call answers them all.
let cached = { at: 0, line: "" };

function statusline() {
  if (Date.now() - cached.at < 2000) return Promise.resolve(cached.line);
  return new Promise((resolve) => {
    const child = execFile(DEJA, ["statusline"], { encoding: "utf8", timeout: 3000, maxBuffer: 64 * 1024 }, (err, out) => {
      const line = err ? "" : String(out).split("\n")[0].trim();
      cached = { at: Date.now(), line };
      resolve(line);
    });
    child.stdin && child.stdin.end("{}");
  });
}

// The web server answers any page that reaches it; the line is for the one
// on this machine, not for a page some other site points at 127.0.0.1.
function loopback(req) {
  const host = String(req.headers.host || "").replace(/:\d+$/, "").toLowerCase();
  return host === "localhost" || host === "127.0.0.1" || host === "[::1]";
}

function apply(ctx) {
  ctx.inject(["webServer"], (ctx) => {
    const dispose = ctx.webServer.register({
      kind: "exact",
      path: ROUTE,
      async handler(req, res) {
        if (!loopback(req)) {
          res.writeHead(403).end();
          return;
        }
        const line = await statusline();
        res.writeHead(200, { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" });
        res.end(line);
      },
    });
    ctx.effect(() => dispose);
  });
}

export default apply;
`, exe)
}

// dshStatusClientJS is the browser half, in the factory form dsh's module
// loader takes; react comes from the page's shared module table.
const dshStatusClientJS = `// generated by deja install
window.__ModuleLoader__.load({
  id: "deja-status",
  factory: (require) => {
    var module = { exports: {} };
    const react = require("react");
    const jsx = require("react/jsx-runtime");

    function DejaStatus() {
      const [line, setLine] = react.useState("");
      react.useEffect(() => {
        let live = true;
        const tick = async () => {
          try {
            const r = await fetch("/deja/statusline", { cache: "no-store" });
            if (r.ok && live) setLine((await r.text()).trim());
          } catch {}
        };
        tick();
        const id = setInterval(tick, 5000);
        return () => {
          live = false;
          clearInterval(id);
        };
      }, []);
      if (!line) return null;
      return jsx.jsx("div", {
        "data-deja-status": true,
        title: line,
        style: { fontSize: "12px", opacity: 0.7, padding: "2px 8px", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
        children: line,
      });
    }

    function apply(ctx) {
      ctx.slots.inject("conversation.composer.dock", () =>
        ctx.slots.register({ name: "conversation.composer.dock", id: "deja-status", order: 90 }, DejaStatus));
    }

    module.exports.apply = apply;
    module.exports.inject = ["slots"];
    return module.exports;
  },
});
`

// writeDSHStatus writes the three files and returns what happened to them as
// one action.
func writeDSHStatus(exe string) (string, error) {
	dir := dshStatusDir()
	noteCreatedDirs(dir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	action := "unchanged"
	for _, f := range []struct{ name, body string }{
		{"package.json", dshStatusPackageJSON},
		{"index.js", dshStatusServerJS(exe)},
		{"client.js", dshStatusClientJS},
	} {
		p := filepath.Join(dir, f.name)
		old, err := readConfig(p)
		if err != nil {
			return "", err
		}
		a, err := writeIfChanged(p, old, []byte(f.body))
		if err != nil {
			return "", err
		}
		if a != "unchanged" && action == "unchanged" {
			action = a
		}
	}
	return action, nil
}
