package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
)

// opencode and Kilo CLI have no command status line. Their TUI takes plugins
// that put text in its own slots, so deja's line goes there: a TUI plugin that
// runs `deja statusline` and shows the first line. opencode 1.x and Kilo load
// one listed in tui.json (no directory discovery for TUI plugins) and give it
// sidebar_content, session_prompt_right and home_bottom; opencode 2.x finds
// <config>/plugins/<name>/tui.tsx itself and has footer slots instead. Both
// shapes were rendered live: opencode 1.18.34 and 2.0.24, Kilo 7.8.8.

const opencodeTUIMarker = "// generated by deja install"

// opencodeTUIPluginV1 is the 1.x TUI plugin. The session id comes from the
// sidebar, which renders only above 120 columns, and from the prompt row,
// which is always there.
func opencodeTUIPluginV1(exe, target string) string {
	return `/** @jsxImportSource @opentui/solid */
` + opencodeTUIMarker + ` — safe to delete; regenerate with: deja install ` + target + `
import { createSignal } from "solid-js"
import { execFile } from "node:child_process"

const DEJA = ` + strconv.Quote(exe) + `

const tui = async (api) => {
  const [line, setLine] = createSignal("")
  let sid = ""
  const refresh = () => {
    const cwd = api.state?.path?.directory || process.cwd()
    try {
      const child = execFile(DEJA, ["statusline"], { cwd, timeout: 2000 }, (err, out) => {
        if (!err) setLine(String(out).split("\n")[0].trim())
      })
      child.stdin?.on("error", () => {})
      child.stdin?.end(JSON.stringify({ session_id: sid }) + "\n")
    } catch {}
  }
  const follow = (id) => {
    if (id && id !== sid) {
      sid = id
      refresh()
    }
  }
  refresh()
  const offs = ["session.idle", "session.created"].map((t) => api.event.on(t, refresh))
  const tick = setInterval(refresh, 10000)
  api.lifecycle.onDispose(() => {
    clearInterval(tick)
    offs.forEach((off) => off())
  })
  const view = (ctx) => <text fg={ctx.theme.current.textMuted}>{line()}</text>
  api.slots.register({
    order: 50,
    slots: {
      sidebar_content(ctx, props) {
        follow(props?.session_id)
        return view(ctx)
      },
      session_prompt_right(ctx, props) {
        follow(props?.session_id)
        return view(ctx)
      },
      home_bottom(ctx) {
        return view(ctx)
      },
    },
  })
}

export default { id: "deja.status", tui }
`
}

// opencodeTUIPluginV2 is the 2.x TUI plugin: footer slots, the session id
// from the prompt footer's input.
func opencodeTUIPluginV2(exe string) string {
	return `/** @jsxImportSource @opentui/solid */
` + opencodeTUIMarker + ` — safe to delete; regenerate with: deja install opencode-auto
import { createSignal, createEffect } from "solid-js"
import { execFile } from "node:child_process"

const DEJA = ` + strconv.Quote(exe) + `

export default {
  id: "deja.status",
  setup(ctx) {
    const [line, setLine] = createSignal("")
    let sid = ""
    const refresh = () => {
      const cwd = ctx.location?.directory || process.cwd()
      try {
        const child = execFile(DEJA, ["statusline"], { cwd, timeout: 2000 }, (err, out) => {
          if (!err) setLine(String(out).split("\n")[0].trim())
        })
        child.stdin?.on("error", () => {})
        child.stdin?.end(JSON.stringify({ session_id: sid }) + "\n")
      } catch {}
    }
    const view = () => <text fg={ctx.theme.textMuted}>{line()}</text>
    refresh()
    const tick = setInterval(refresh, 10000)
    const offs = [
      ctx.ui.slot({
        append: "prompt.footer.status",
        render: (input) => {
          createEffect(() => {
            const next = input.sessionID || ""
            if (next !== sid) {
              sid = next
              refresh()
            }
          })
          // The home screen's prompt box is too narrow for the line and has
          // home.footer.status below it; the prompt footer carries it only in
          // a session.
          return <text fg={ctx.theme.textMuted}>{input.sessionID ? line() : ""}</text>
        },
      }),
      ctx.ui.slot({ append: "home.footer.status", render: view }),
    ]
    return () => {
      clearInterval(tick)
      offs.forEach((off) => off())
    }
  },
}
`
}

// writeGeneratedFile writes body to path, or on uninstall removes a file deja
// generated there, leaving one somebody wrote by hand.
func writeGeneratedFile(path, body string, uninstall bool) (installResult, error) {
	if uninstall {
		b, err := os.ReadFile(path)
		if err != nil || !strings.Contains(headLines(string(b), 3), opencodeTUIMarker) {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.Remove(path); err != nil {
			return installResult{}, err
		}
		pruneCreatedDir(filepath.Dir(path))
		return installResult{Path: path, Action: "removed"}, nil
	}
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(path, old, []byte(body))
	return installResult{Path: path, Action: a}, err
}

func headLines(s string, n int) string {
	for i, c := 0, 0; i < len(s); i++ {
		if s[i] == '\n' {
			if c++; c == n {
				return s[:i]
			}
		}
	}
	return s
}

// installTUIPluginList adds entry to the plugin list of dir's tui.json, or
// takes it out. A tui.jsonc deja does not edit: the note says what to add.
func installTUIPluginList(dir, schema, entry string, uninstall bool) (installResult, error) {
	path := filepath.Join(dir, "tui.json")
	if _, err := os.Stat(path); err != nil {
		if _, jerr := os.Stat(filepath.Join(dir, "tui.jsonc")); jerr == nil {
			r := installResult{Path: filepath.Join(dir, "tui.jsonc"), Action: "unchanged"}
			if !uninstall {
				r.Note = "add " + strconv.Quote(entry) + " to its plugin list to show deja's status line"
			}
			return r, nil
		}
		if uninstall {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
	}
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	root := map[string]any{}
	if len(bytes.TrimSpace(old)) > 0 {
		if err := json.Unmarshal(old, &root); err != nil {
			return installResult{}, configParseError(path, err)
		}
	}
	raw, _ := root["plugin"].([]any)
	var list []any
	for _, p := range raw {
		if s, _ := p.(string); s != entry {
			list = append(list, p)
		}
	}
	if !uninstall {
		list = append(list, entry)
	}
	if len(list) == 0 {
		delete(root, "plugin")
	} else {
		root["plugin"] = list
	}
	if uninstall && len(root) == 0 || uninstall && len(root) == 1 && root["$schema"] == schema {
		// Nothing but what deja wrote: the file goes with the entry.
		if len(old) > 0 && !slices.Contains(raw, any(entry)) {
			return installResult{Path: path, Action: "unchanged"}, nil
		}
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return installResult{}, err
		}
		pruneCreatedDir(dir)
		return installResult{Path: path, Action: "removed"}, nil
	}
	if _, ok := root["$schema"]; !ok && len(bytes.TrimSpace(old)) == 0 {
		root["$schema"] = schema
	}
	next, err := marshalConfigLike(old, root)
	if err != nil {
		return installResult{}, err
	}
	next = append(next, '\n')
	a, err := writeIfChanged(path, old, next)
	return installResult{Path: path, Action: a}, err
}

// installOpencodeTUI puts deja's status line in opencode's TUI: the plugin
// the installed major version loads, and on uninstall both.
func installOpencodeTUI(exe string, uninstall bool) (installResult, error) {
	dir := filepath.Join(opencodeConfigHome(), "opencode")
	exe = hookExeFor(exe, uninstall)
	v1 := filepath.Join(dir, "plugins", "deja-status.tsx")
	v2 := filepath.Join(dir, "plugins", "deja-status", "tui.tsx")
	if uninstall {
		a, err := writeGeneratedFile(v1, "", true)
		if err != nil {
			return installResult{}, err
		}
		list, err := installTUIPluginList(dir, "https://opencode.ai/tui.json", "./plugins/deja-status.tsx", true)
		if err != nil {
			return installResult{}, err
		}
		b, err := writeGeneratedFile(v2, "", true)
		if err != nil {
			return installResult{}, err
		}
		return wroteAll(a, list, b), nil
	}
	if opencodeIsV1() {
		file, err := writeGeneratedFile(v1, opencodeTUIPluginV1(exe, "opencode-auto"), false)
		if err != nil {
			return installResult{}, err
		}
		list, err := installTUIPluginList(dir, "https://opencode.ai/tui.json", "./plugins/deja-status.tsx", false)
		if err != nil {
			return installResult{}, err
		}
		return wroteAll(file, list), nil
	}
	return writeGeneratedFile(v2, opencodeTUIPluginV2(exe), false)
}

// installKiloTUI is the 1.x plugin in Kilo CLI's config, which reads tui.json
// the way opencode 1.x does (schema https://app.kilo.ai/tui.json, 7.8.8).
func installKiloTUI(exe string, uninstall bool) (installResult, error) {
	dir := kilocodeCLIConfigDir()
	exe = hookExeFor(exe, uninstall)
	file, err := writeGeneratedFile(filepath.Join(dir, "plugins", "deja-status.tsx"), opencodeTUIPluginV1(exe, "kilocode-auto"), uninstall)
	if err != nil {
		return installResult{}, err
	}
	list, err := installTUIPluginList(dir, "https://app.kilo.ai/tui.json", "./plugins/deja-status.tsx", uninstall)
	if err != nil {
		return installResult{}, err
	}
	return wroteAll(file, list), nil
}
