package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// A hook entry holds the absolute path of the build that installed it, so
// every move breaks every config at once: Homebrew upgrading, npm installing
// somewhere else, a binary dropped in ~/bin. The repair that answers a broken
// link writes the running binary into all of them, which is how one machine
// collected eight entries per event, each naming a different build and each
// firing on every prompt (#3421).
//
// The launcher is the path that does not move. Configs name it, it resolves
// the real binary when the hook runs, and an upgrade rewrites one file instead
// of twenty-eight. The opencode plugin has resolved this way since a moved
// binary left it dead; this brings the hooks in line with it (#3422).
//
// Not on Windows: a .cmd cannot be exec'd the way a shebang script can, and a
// harness that spawns the command without a shell would find nothing at all.
// There the entry keeps the binary's own path, as before.
func dejaLauncherPath() string {
	if runtime.GOOS == "windows" {
		return ""
	}
	// Beside the wiring record, which is the other file that is deja's own
	// rather than a mirror of some harness's path logic.
	return filepath.Join(xdgConfigHome(), "deja", "bin", "deja-hook")
}

// hookExeFor is what a hook writer names in the config: the launcher on the
// way in, and the binary's own path on the way out — an uninstall matches
// entries by what they say, and writing a launcher for a run that is taking
// the wiring away would leave the file behind.
func hookExeFor(exe string, uninstall bool) string {
	if uninstall {
		return exe
	}
	return hookCommandExe(exe)
}

// hookCommandExe is the path a hook entry should name. It writes the launcher
// and returns it; if that cannot be done — a read-only home, a platform
// without one — the caller gets the binary's own path and the wiring is what
// it always was.
func hookCommandExe(exe string) string {
	p, err := writeDejaLauncher(exe)
	if err != nil || p == "" {
		return exe
	}
	return p
}

// writeDejaLauncher writes the resolver and returns its path.
func writeDejaLauncher(exe string) (string, error) {
	path := dejaLauncherPath()
	if path == "" {
		return "", nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	old, err := os.ReadFile(path)
	next := []byte(dejaLauncherScript(exe))
	if err == nil && string(old) == string(next) {
		return path, nil
	}
	if err := os.WriteFile(path, next, 0o755); err != nil {
		return "", err
	}
	return path, nil
}

// removeDejaLauncher takes the resolver out. Only on a full uninstall: a
// target that stays wired is still pointing at it.
func removeDejaLauncher() {
	if path := dejaLauncherPath(); path != "" {
		_ = os.Remove(path)
	}
}

// dejaLauncherScript is the resolver itself. Order matters and is the one from
// #3422: an explicit DEJA_BIN, then the path this install ran from, then the
// PATH, then where the installers put it.
//
// It ends by exiting 0 with nothing on stdout. A hook that cannot find deja has
// no memory to add, and saying so on stderr every turn — or failing, which some
// harnesses read as a reason to stop — costs the reader more than silence.
func dejaLauncherScript(exe string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# generated by deja install — finds the deja binary at run time so an\n")
	b.WriteString("# upgrade that moves it does not have to rewrite every agent's config.\n")
	b.WriteString("# Safe to delete; `deja install` writes it again.\n")
	b.WriteString("if [ -n \"$DEJA_BIN\" ] && [ -x \"$DEJA_BIN\" ]; then exec \"$DEJA_BIN\" \"$@\"; fi\n")
	b.WriteString("for c in \\\n")
	for _, c := range launcherCandidates(exe) {
		fmt.Fprintf(&b, "  %s \\\n", shellQuote(c))
	}
	b.WriteString("  ; do\n")
	b.WriteString("  [ -x \"$c\" ] && exec \"$c\" \"$@\"\n")
	b.WriteString("done\n")
	b.WriteString("c=$(command -v deja 2>/dev/null) || c=\"\"\n")
	b.WriteString("[ -n \"$c\" ] && exec \"$c\" \"$@\"\n")
	b.WriteString("exit 0\n")
	return b.String()
}

// launcherWellKnown is where the supported installers leave the binary. A
// variable so a test can take the machine's own deja out of the list it is
// exercising.
var launcherWellKnown = []string{"/usr/local/bin/deja", "/opt/homebrew/bin/deja", "/usr/bin/deja"}

// launcherCandidates are the paths tried before the PATH, the install's own
// first. The rest are where the three supported installers leave the binary,
// so a machine whose PATH the harness does not inherit — a GUI-launched agent
// has a short one — still finds it.
func launcherCandidates(exe string) []string {
	out := []string{}
	seen := map[string]bool{}
	add := func(p string) {
		if p == "" || seen[p] {
			return
		}
		seen[p] = true
		out = append(out, p)
	}
	add(exe)
	home := sources.Home()
	if home != "" {
		add(filepath.Join(home, ".local", "bin", "deja"))
		add(filepath.Join(home, "bin", "deja"))
	}
	for _, p := range launcherWellKnown {
		add(p)
	}
	return out
}
