package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The harnesses page is generated by scripts/genmatrix, and nothing checked
// that it had been re-run. It sat a store path behind the registry: newer VS
// Code Copilot Chat builds write
// `<vscode-User>/workspaceStorage/*/GitHub.copilot-chat/transcripts/*.jsonl`,
// the parser learned it, the registry recorded it, and the page — the one the
// site answers "where does my agent keep its history" with — still named the
// older directory only (#3781).
//
// TestCapabilityRegistryMatchesCode checks that a row exists per harness,
// which is why this hid: every row was there and the paths inside them are
// what drifted. Measured before the fix, exactly one of 121 paths was missing,
// so this is a precise check rather than a noisy one.
func TestTheHarnessMatrixNamesEveryStorePath(t *testing.T) {
	root := filepath.Join("..", "..")
	b, err := os.ReadFile(filepath.Join(root, "docs", "registry", "registry.json"))
	if err != nil {
		t.Fatal(err)
	}
	var reg struct {
		Harnesses []struct {
			ID         string   `json:"id"`
			StorePaths []string `json:"store_paths"`
		} `json:"harnesses"`
	}
	if err := json.Unmarshal(b, &reg); err != nil {
		t.Fatal(err)
	}
	page, err := os.ReadFile(filepath.Join(root, "docs", "guide", "harnesses.html"))
	if err != nil {
		t.Fatal(err)
	}
	html := string(page)

	checked := 0
	for _, h := range reg.Harnesses {
		if h.ID == "deja" {
			continue
		}
		for _, p := range h.StorePaths {
			checked++
			if !strings.Contains(html, p) {
				t.Errorf("the harnesses page does not name %s's %s — run `go run ./scripts/genmatrix`", h.ID, p)
			}
		}
	}
	if checked < 50 {
		t.Fatalf("only %d store paths read out of the registry; this test is looking at the wrong field", checked)
	}
}
