#!/usr/bin/env python3
"""Generate internal/nfcfold/table.go: canonical composition pairs (NFC).

deja's tokens are byte sequences, so the same accented word written NFC
(precomposed 'é') and NFD (base 'e' + combining U+0301) hash to two different
keys and never match — real on macOS, where APFS and some input paths emit NFD
while the keyboard emits NFC (#1098). Composing both sides to NFC before
tokenising makes them meet.

Only single base+mark canonical compositions whose base is a Latin, Greek or
Cyrillic letter are emitted, and composition exclusions are dropped (NFC would not recompose them),
so the table is a pure, lossless function.
"""
import sys, unicodedata

def is_composable_base(c):
    # Latin, Greek and Cyrillic letters — the scripts whose accented forms have
    # both a precomposed (NFC) and a base+combining (NFD) spelling a corpus can
    # carry either way. The mark (second element) is bounded to U+0300..U+036F
    # below, which is the combining range these three scripts use.
    o = ord(c)
    if 0x41 <= o <= 0x5A or 0x61 <= o <= 0x7A:       # Basic Latin
        return True
    if 0x00C0 <= o <= 0x024F:                        # Latin-1 Supplement, Ext-A/B
        return unicodedata.category(c).startswith('L')
    if 0x0370 <= o <= 0x03FF:                        # Greek
        return unicodedata.category(c).startswith('L')
    if 0x0400 <= o <= 0x04FF:                        # Cyrillic
        return unicodedata.category(c).startswith('L')
    return False

pairs = []
for cp in range(0x00C0, 0x2130):
    c = chr(cp)
    d = unicodedata.decomposition(c)
    if not d or d.startswith('<'):
        continue
    parts = d.split()
    if len(parts) != 2:
        continue
    base, mark = chr(int(parts[0], 16)), chr(int(parts[1], 16))
    if not (0x0300 <= ord(mark) <= 0x036F):
        continue
    if not is_composable_base(base):
        continue
    if unicodedata.normalize('NFC', base + mark) != c:  # composition exclusion
        continue
    pairs.append((base, mark, c))

out = []
out.append("package nfcfold")
out.append("")
out.append("// Code generated by tools/gen_nfc_fold.py; DO NOT EDIT.")
out.append("//")
out.append("// Canonical base+mark -> precomposed (Latin, Greek, Cyrillic), so an")
out.append("// NFD-typed accented word folds to the same token as its NFC form (#1098).")
out.append("")
out.append("var compose = map[[2]rune]rune{")
for base, mark, c in pairs:
    out.append("\t{0x%04X, 0x%04X}: 0x%04X," % (ord(base), ord(mark), ord(c)))
out.append("}")
sys.stdout.write("\n".join(out) + "\n")
sys.stderr.write("emitted %d composition pairs\n" % len(pairs))
